<xml scenarioFilename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry"><SCRIPT type="Initialize">import json
from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.
def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;id&apos;, &apos;reference&apos;, &apos;creation&apos;, &apos;travelers&apos;, &apos;products&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc2 + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=test_user_1A_extended_office, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;associatedPnrs&apos;]), expected=1, item_name=&apos;number of associatedPnrs&apos;)
        associatedPnrs_1 = openpnr[&apos;associatedPnrs&apos;][0]
        assert_equal(actual=associatedPnrs_1[&apos;reference&apos;], expected=recloc, item_name=&apos;RLOC reference&apos;)
        assert_equal(actual=associatedPnrs_1[&apos;associationType&apos;], expected=&quot;SPLIT&quot;, item_name=&apos;associationType&apos;)
        assert_equal(actual=associatedPnrs_1[&apos;direction&apos;], expected=&quot;PARENT&quot;, item_name=&apos;direction&apos;)

    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="66" beginLine="65" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:45.916230 - 27 Jun 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="08:18:45.968723 - 27 Jun 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" endLine="67" beginLine="66" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:45.969279 - 27 Jun 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="08:18:46.025380 - 27 Jun 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="3" endLine="68" beginLine="67" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:46.026130 - 27 Jun 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="08:18:46.096253 - 27 Jun 2024" filename="">&amp;
09CC2B44         NCE1A0950&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="74" beginLine="73" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:46.096493 - 27 Jun 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="08:18:46.154513 - 27 Jun 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="76" beginLine="75" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:48.174232 - 27 Jun 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="08:18:48.231484 - 27 Jun 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="80" responseBeginLine="80" endLine="78" beginLine="77" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:48.232304 - 27 Jun 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.DALWN0980-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[Yoanntesting123*]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="08:18:48.400240 - 27 Jun 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/27JUN/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" endLine="89" beginLine="88" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><COMMENT> 2.Create a PNR with 2pax 1seg + APM</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:48.401531 - 27 Jun 2024"><TEXT><![CDATA[ffawn-600659555]]></TEXT></QUERY><REPLY receiveAt="08:18:48.607310 - 27 Jun 2024" filename="">RP/DALWN0980/&amp;
  1.GERE/RICHARD&amp;
  2 *SSR FQTV YY HK/ WN600659555/0&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="8" endLine="90" beginLine="89" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:48.607897 - 27 Jun 2024"><TEXT><![CDATA[nm1smith/jane]]></TEXT></QUERY><REPLY receiveAt="08:18:48.712550 - 27 Jun 2024" filename="">RP/DALWN0980/&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3 *SSR FQTV YY HK/ WN600659555/0/P1&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="9" endLine="91" beginLine="90" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:48.713106 - 27 Jun 2024"><TEXT><![CDATA[SSWN2367Y10JULDALATL2]]></TEXT></QUERY><REPLY receiveAt="08:18:49.280949 - 27 Jun 2024" filename="">--- RLP SFP ---&amp;
RP/DALWN0980/&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   7M8 E 0&amp;
     SEE RTSVC - TRAFFIC RESTRICTION EXISTS&amp;
  4 AP 4567896341-H/P1&amp;
  5 APE X220222@WNCO.COM-H/P1&amp;
  6 *SSR FQTV YY HK/ WN600659555/0/P1&amp;
  7 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
  8 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
  9 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S3&amp;
 10 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US/P1&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="10" endLine="92" beginLine="91" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:49.281421 - 27 Jun 2024"><TEXT><![CDATA[TKOK;APNCE;RFME]]></TEXT></QUERY><REPLY receiveAt="08:18:49.487466 - 27 Jun 2024" filename="">--- RLP SFP ---&amp;
RP/DALWN0980/&amp;
RF ME&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   7M8 E 0&amp;
     SEE RTSVC - TRAFFIC RESTRICTION EXISTS&amp;
  4 AP 4567896341-H/P1&amp;
  5 AP NCE&amp;
  6 APE X220222@WNCO.COM-H/P1&amp;
  7 TK OK27JUN/DALWN0980&amp;
  8 *SSR FQTV YY HK/ WN600659555/0/P1&amp;
  9 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
 10 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
 11 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S3&amp;
 12 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US/P1&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="11" endLine="93" beginLine="92" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:49.487899 - 27 Jun 2024"><TEXT><![CDATA[SR DOCS WN HK1-A////01MAR80/F//smith/jane/P2]]></TEXT></QUERY><REPLY receiveAt="08:18:49.654144 - 27 Jun 2024" filename="">--- RLP SFP ---&amp;
RP/DALWN0980/&amp;
RF ME&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   7M8 E 0&amp;
     SEE RTSVC - TRAFFIC RESTRICTION EXISTS&amp;
  4 AP 4567896341-H/P1&amp;
  5 AP NCE&amp;
  6 APE X220222@WNCO.COM-H/P1&amp;
  7 TK OK27JUN/DALWN0980&amp;
  8 *SSR FQTV YY HK/ WN600659555/0/P1&amp;
  9 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
 10 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
 11 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE/P2&amp;
 12 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S3&amp;
 13 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US/P1&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="12" endLine="94" beginLine="93" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:49.654405 - 27 Jun 2024"><TEXT><![CDATA[sr erbd]]></TEXT></QUERY><REPLY receiveAt="08:18:49.948155 - 27 Jun 2024" filename="">--- RLP SFP ---&amp;
RP/DALWN0980/&amp;
RF ME&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   7M8 E 0&amp;
     SEE RTSVC - TRAFFIC RESTRICTION EXISTS&amp;
  4 AP 4567896341-H/P1&amp;
  5 AP NCE&amp;
  6 APE X220222@WNCO.COM-H/P1&amp;
  7 TK OK27JUN/DALWN0980&amp;
  8 *SSR FQTV YY HK/ WN600659555/0/P1&amp;
  9 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
 10 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
 11 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE/P2&amp;
 12 /SSR ERBD WN HK1/S3/P1&amp;
 13 /SSR ERBD WN HK1/S3/P2&amp;
 14 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S3&amp;
 15 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US/P1&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="13" endLine="95" beginLine="94" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:49.948802 - 27 Jun 2024"><TEXT><![CDATA[es nce1a0955-b]]></TEXT></QUERY><REPLY receiveAt="08:18:50.129673 - 27 Jun 2024" filename="">--- RLP SFP ---&amp;
RP/DALWN0980/&amp;
RF ME&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   7M8 E 0&amp;
     SEE RTSVC - TRAFFIC RESTRICTION EXISTS&amp;
  4 AP 4567896341-H/P1&amp;
  5 AP NCE&amp;
  6 APE X220222@WNCO.COM-H/P1&amp;
  7 TK OK27JUN/DALWN0980&amp;
  8 *SSR FQTV YY HK/ WN600659555/0/P1&amp;
  9 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
 10 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
 11 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE/P2&amp;
 12 /SSR ERBD WN HK1/S3/P1&amp;
 13 /SSR ERBD WN HK1/S3/P2&amp;
 14 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S3&amp;
 15 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US/P1&amp;
  * ES/G B NCE1A0955&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="14" endLine="96" beginLine="95" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:50.130200 - 27 Jun 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="08:18:50.592392 - 27 Jun 2024" filename="">--- RLR RLP SFP ---&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   4GXBQT&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   *1A/E*&amp;
  4 AP 4567896341-H/P1&amp;
  5 AP NCE&amp;
  6 APE X220222@WNCO.COM-H/P1&amp;
  7 TK OK27JUN/DALWN0980&amp;
  8 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
  9 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
 10 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE/P2&amp;
 11 /SSR ERBD WN HK1/S3/P1&amp;
 12 /SSR ERBD WN HK1/S3/P2&amp;
 13 *SSR FQTV WN HK/ WN600659555/0/P1&amp;
 14 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E11-12&amp;
 15 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E11-1&amp;
       2&amp;
 16 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S3&amp;
 17 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US/P1&amp;
)&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="15" endLine="99" beginLine="98" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:50.592873 - 27 Jun 2024"><TEXT><![CDATA[IR]]></TEXT></QUERY><REPLY receiveAt="08:18:50.777639 - 27 Jun 2024" filename="">--- RLR RLP SFP ---&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   4GXBQT&amp;
  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   *1A/E*&amp;
  4 AP 4567896341-H/P1&amp;
  5 AP NCE&amp;
  6 APE X220222@WNCO.COM-H/P1&amp;
  7 TK OK27JUN/DALWN0980&amp;
  8 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
  9 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
 10 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE/P2&amp;
 11 /SSR ERBD WN HK1/S3/P1&amp;
 12 /SSR ERBD WN HK1/S3/P2&amp;
 13 *SSR FQTV WN HK/ WN600659555/0/P1&amp;
 14 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E11-12&amp;
 15 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E11-1&amp;
       2&amp;
 16 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S3&amp;
 17 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US/P1&amp;
)&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="16" endLine="100" beginLine="99" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:50.778167 - 27 Jun 2024"><TEXT><![CDATA[SP2]]></TEXT></QUERY><REPLY receiveAt="08:18:51.048350 - 27 Jun 2024" filename="">--- RLR SFP ---&amp;
-ASSOCIATE PNR-&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   XXXXXX&amp;
  1.SMITH/JANE&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP NCE&amp;
  4 TK OK27JUN/DALWN0980&amp;
  5 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE&amp;
  6 /SSR ERBD WN HK1/S2&amp;
  7 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E6&amp;
  8 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E6&amp;
  9 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP 27JUN/YGSU/DALWN0980-4GXBQT&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="17" endLine="101" beginLine="100" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:51.048682 - 27 Jun 2024"><TEXT><![CDATA[XE6]]></TEXT></QUERY><REPLY receiveAt="08:18:51.326517 - 27 Jun 2024" filename="">--- RLR SFP ---&amp;
-ASSOCIATE PNR-&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   XXXXXX&amp;
  1.SMITH/JANE&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP NCE&amp;
  4 TK OK27JUN/DALWN0980&amp;
  5 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE&amp;
  6 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP 27JUN/YGSU/DALWN0980-4GXBQT&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="18" endLine="102" beginLine="101" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:51.327039 - 27 Jun 2024"><TEXT><![CDATA[RFF]]></TEXT></QUERY><REPLY receiveAt="08:18:51.567727 - 27 Jun 2024" filename="">--- RLR SFP ---&amp;
-ASSOCIATE PNR-&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   XXXXXX&amp;
RF F&amp;
  1.SMITH/JANE&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP NCE&amp;
  4 TK OK27JUN/DALWN0980&amp;
  5 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE&amp;
  6 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP 27JUN/YGSU/DALWN0980-4GXBQT&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="19" endLine="103" beginLine="102" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:51.568146 - 27 Jun 2024"><TEXT><![CDATA[EF]]></TEXT></QUERY><REPLY receiveAt="08:18:51.765722 - 27 Jun 2024" filename="">--- RLR RLP SFP ---&amp;
-PARENT PNR-&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   4GXBQT&amp;
  1.GERE/RICHARD&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP 4567896341-H&amp;
  4 AP NCE&amp;
  5 APE X220222@WNCO.COM-H&amp;
  6 TK OK27JUN/DALWN0980&amp;
  7 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S2&amp;
  8 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016&amp;
  9 /SSR ERBD WN HK1/S2&amp;
 10 *SSR FQTV WN HK/ WN600659555/0&amp;
 11 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E9&amp;
 12 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E9&amp;
 13 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
 14 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US&amp;
  * SP 27JUN/YGSU/DALWN0980-4GVUUA&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
)&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="20" endLine="104" beginLine="103" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:51.766091 - 27 Jun 2024"><TEXT><![CDATA[RFF]]></TEXT></QUERY><REPLY receiveAt="08:18:51.939746 - 27 Jun 2024" filename="">--- RLR RLP SFP ---&amp;
-PARENT PNR-&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   4GXBQT&amp;
RF F&amp;
  1.GERE/RICHARD&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP 4567896341-H&amp;
  4 AP NCE&amp;
  5 APE X220222@WNCO.COM-H&amp;
  6 TK OK27JUN/DALWN0980&amp;
  7 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S2&amp;
  8 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016&amp;
  9 /SSR ERBD WN HK1/S2&amp;
 10 *SSR FQTV WN HK/ WN600659555/0&amp;
 11 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E9&amp;
 12 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E9&amp;
 13 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
 14 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US&amp;
  * SP 27JUN/YGSU/DALWN0980-4GVUUA&amp;
)&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="21" endLine="105" beginLine="104" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:51.940228 - 27 Jun 2024"><TEXT><![CDATA[RF YG]]></TEXT></QUERY><REPLY receiveAt="08:18:52.132413 - 27 Jun 2024" filename="">--- RLR RLP SFP ---&amp;
-PARENT PNR-&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0618Z   4GXBQT&amp;
RF YG&amp;
  1.GERE/RICHARD&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP 4567896341-H&amp;
  4 AP NCE&amp;
  5 APE X220222@WNCO.COM-H&amp;
  6 TK OK27JUN/DALWN0980&amp;
  7 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S2&amp;
  8 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016&amp;
  9 /SSR ERBD WN HK1/S2&amp;
 10 *SSR FQTV WN HK/ WN600659555/0&amp;
 11 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E9&amp;
 12 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E9&amp;
 13 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
 14 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US&amp;
  * SP 27JUN/YGSU/DALWN0980-4GVUUA&amp;
)&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="22" endLine="106" beginLine="105" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:52.132771 - 27 Jun 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="08:18:52.437661 - 27 Jun 2024" filename="">SIMULTANEOUS CHANGES TO PNR - USE WRA/RT TO PRINT OR IGNORE&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="23" responseEndLine="112" responseBeginLine="110" endLine="108" beginLine="107" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:52.438249 - 27 Jun 2024"><TEXT><![CDATA[IR]]></TEXT></QUERY><COMPARISON compareAt="08:18:52.829623 - 27 Jun 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[RLP SFP ]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/DALWN0980/DALWN0980          ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  AA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[27JUN24/0618]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[4GXBQT]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  1.GERE/RICHARD   2.SMITH/JANE&amp;
  3  WN2367 Y 10JUL 3 DALATL HK2       1  0600 0905   *1A/E*&amp;
  4 AP 4567896341-H/P1&amp;
  5 AP NCE&amp;
  6 APE X220222@WNCO.COM-H/P1&amp;
  7 TK OK27JUN/DALWN0980&amp;
  8 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S3/P1&amp;
  9 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016/P1&amp;
 10 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE/P2&amp;
 11 /SSR ERBD WN HK1/S3/P1&amp;
 12 /SSR ERBD WN HK1/S3/P2&amp;
 13 *SSR FQTV WN HK/ WN600659555/0/P1&amp;
 14 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E11-12&amp;
 15 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E11-1&amp;
       2&amp;
 16 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S3/P1-2&amp;
 17 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
)&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="24" responseEndLine="125" responseBeginLine="117" endLine="115" beginLine="114" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:52.831592 - 27 Jun 2024"><TEXT><![CDATA[SP1]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 122: A character does not match, expected &apos;6&apos;, received &apos;W&apos;." compareAt="08:18:53.096392 - 27 Jun 2024"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[RLP SFP ]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
-ASSOCIATE PNR-&amp;
RP/DALWN0980/DALWN0980        ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[    AA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[27JUN24/0618]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   XXXXXX&amp;
  1.]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[GERE]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[RICHARD]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
  2  ]]></TEXT><UNMATCH validate="manual"><EXPECTED><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_1.pnr_format(&apos;&apos;)}]]></EXPRESSION><VALUE><![CDATA[6X 402 Y 16AUG 5 FRALHR ]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[{*}  1000 1100  {*}  E  6X/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[4GXBQT]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[  3 AP ]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[NCE]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[4567896341-H]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
  4 ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[TK {*}/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[AP NCE&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[  ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[{(local).*?SP} {*}/YGSU/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[4GXBQT]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[5 APE X220222@WNCO.COM-H&amp;
]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&gt;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[  6 TK OK27JUN/DALWN0980&amp;
  7 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S2&amp;
  8 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016&amp;
  9 /SSR ERBD WN HK1/S2&amp;
 10 *SSR FQTV WN HK/ WN600659555/0&amp;
 11 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E9&amp;
 12 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E9&amp;
 13 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S2&amp;
 14 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
 15 AM/H A1-2 LUV DR/ZP-41526/CI-LOVEFIELD/ST-AZ/CO-US&amp;
)&gt;]]></TEXT></RECEIVED></UNMATCH></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="25" endLine="128" beginLine="127" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:53.098947 - 27 Jun 2024"><TEXT><![CDATA[RF test]]></TEXT></QUERY><REPLY receiveAt="08:18:53.299799 - 27 Jun 2024" filename="">--- RLR RLP SFP ---&amp;
-ASSOCIATE PNR-&amp;
RP/DALWN0980/DALWN0980            AA/SU  27JUN24/0618Z   XXXXXX&amp;
RF TEST&amp;
  1.GERE/RICHARD&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP 4567896341-H&amp;
  4 AP NCE&amp;
  5 APE X220222@WNCO.COM-H&amp;
  6 TK OK27JUN/DALWN0980&amp;
  7 SSR DOCS WN HK1 ////01MAR80/M//GERE/RICHARD/S2&amp;
  8 SSR OTHS WN HK1 MEMBER SINCE - 21JUL2016&amp;
  9 /SSR ERBD WN HK1/S2&amp;
 10 *SSR FQTV WN HK/ WN600659555/0&amp;
 11 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E9&amp;
 12 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E9&amp;
 13 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S2&amp;
 14 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
)&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="26" responseEndLine="139" responseBeginLine="131" endLine="129" beginLine="128" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:53.300052 - 27 Jun 2024"><TEXT><![CDATA[EF]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 32: A character does not match, expected &apos;N&apos;, received &apos;D&apos;." compareAt="08:18:53.527324 - 27 Jun 2024"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SFP ]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
-PARENT PNR-&amp;
RP/]]></TEXT><UNMATCH validate="manual"><EXPECTED><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[            {*}/{*}  {*}Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[4GXBQT]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[DALWN0980/DALWN0980            AA/SU  27JUN24/0618Z   4GXBQT&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[  1.]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SMITH]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[JANE]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
  2  ]]></TEXT><UNMATCH validate="manual"><EXPECTED><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_1.pnr_format(&apos;&apos;)}]]></EXPRESSION><VALUE><![CDATA[6X 402 Y 16AUG 5 FRALHR ]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[{*}  1000 1100  {*}  E  6X/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[4GXBQT]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[  3 AP NCE&amp;
  4 TK ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[OK27JUN]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><UNMATCH validate="manual"><EXPECTED><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[DALWN0980&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(local).*?SP}]]></EXPRESSION><VALUE><![CDATA[5 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE&amp;
  6 /SSR ERBD WN HK1/S2&amp;
  7 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E6&amp;
  8 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E6&amp;
  9 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S2&amp;
 10 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[27JUN]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/YGSU/]]></TEXT><UNMATCH validate="manual"><EXPECTED><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-{%recloc2%=.{6}}&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[DALWN0980-4GWA7Q&amp;
]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&gt;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;]]></TEXT></RECEIVED></UNMATCH></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="27" endLine="142" beginLine="141" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:53.529545 - 27 Jun 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="08:18:53.703177 - 27 Jun 2024" filename="">NEED RECEIVED FROM&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="28" endLine="149" beginLine="148" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:58.714685 - 27 Jun 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="08:18:58.824834 - 27 Jun 2024" filename="">--- RLR SFP ---&amp;
-PARENT PNR-&amp;
RP/DALWN0980/DALWN0980            AA/SU  27JUN24/0618Z   4GXBQT&amp;
  1.SMITH/JANE&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP NCE&amp;
  4 TK OK27JUN/DALWN0980&amp;
  5 SSR DOCS WN HK1 A////01MAR80/F//SMITH/JANE&amp;
  6 /SSR ERBD WN HK1/S2&amp;
  7 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E6&amp;
  8 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E6&amp;
  9 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S2&amp;
 10 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP 27JUN/YGSU/DALWN0980-4GWA7Q&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="29" endLine="150" beginLine="149" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:18:58.825058 - 27 Jun 2024"><TEXT><![CDATA[SP2]]></TEXT></QUERY><REPLY receiveAt="08:18:58.908283 - 27 Jun 2024" filename="">RESTRICTED - ADDITIONAL SPLIT NOT ALLOWED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="30" endLine="153" beginLine="152" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:19:00.914200 - 27 Jun 2024"><TEXT><![CDATA[XE5]]></TEXT></QUERY><REPLY receiveAt="08:19:01.096982 - 27 Jun 2024" filename="">--- RLR SFP ---&amp;
-PARENT PNR-&amp;
RP/DALWN0980/DALWN0980            AA/SU  27JUN24/0618Z   4GXBQT&amp;
  1.SMITH/JANE&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP NCE&amp;
  4 TK OK27JUN/DALWN0980&amp;
  5 /SSR ERBD WN HK1/S2&amp;
  6 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E5&amp;
  7 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E5&amp;
  8 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S2&amp;
  9 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP 27JUN/YGSU/DALWN0980-4GWA7Q&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="31" endLine="154" beginLine="153" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:19:01.097166 - 27 Jun 2024"><TEXT><![CDATA[RFTEST]]></TEXT></QUERY><REPLY receiveAt="08:19:01.244929 - 27 Jun 2024" filename="">--- RLR SFP ---&amp;
-PARENT PNR-&amp;
RP/DALWN0980/DALWN0980            AA/SU  27JUN24/0618Z   4GXBQT&amp;
RF TEST&amp;
  1.SMITH/JANE&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP NCE&amp;
  4 TK OK27JUN/DALWN0980&amp;
  5 /SSR ERBD WN HK1/S2&amp;
  6 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E5&amp;
  7 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E5&amp;
  8 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S2&amp;
  9 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP 27JUN/YGSU/DALWN0980-4GWA7Q&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="32" endLine="155" beginLine="154" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:19:01.245361 - 27 Jun 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="08:19:01.750370 - 27 Jun 2024" filename="">--- AXR RLR SFP ---&amp;
RP/DALWN0980/DALWN0980            YG/SU  27JUN24/0619Z   4GXBQT&amp;
  1.SMITH/JANE&amp;
  2  WN2367 Y 10JUL 3 DALATL HK1       1  0600 0905   *1A/E*&amp;
  3 AP NCE&amp;
  4 TK OK27JUN/DALWN0980&amp;
  5 /SSR ERBD WN HK1/S2&amp;
  6 OPW-08JUL:0700/1C14/WN REQUIRES DOCUMENT ON OR BEFORE&amp;
        09JUL:0700/E5&amp;
  7 OPC-09JUL:0700/1C16/WN CANCELLATION DUE TO NO DOCUMENT/E5&amp;
  8 OPC-28JUN:2359/1C8/WN CANCELLATION DUE TO NO TICKET DAL TIME&amp;
        ZONE/TKT/S2&amp;
  9 RM NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN:&amp;
       FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS -&amp;
       GGAMAUSHAZ/S2&amp;
  * SP 27JUN/YGSU/DALWN0980-4GWA7Q&amp;
  * ES/G 27JUN/YGSU/DALWN0980&amp;
    NCE1A0955-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="33" responseEndLine="172" responseBeginLine="170" endLine="168" beginLine="164" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:19:01.751025 - 27 Jun 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[SU&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[4GXBQT]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="08:19:01.930330 - 27 Jun 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:4GXBQT::270624:0619&apos;&amp;
RSI+RP:YGSU:DALWN0980:45995132+DALWN0980+EHD+DALWN0980:0447YG:270624:45995132:0618&apos;&amp;
LFT+3:P12+--- AXR RLR SFP ---&apos;&amp;
STX+AXR*RLR*SFP&apos;&amp;
UID+45995132:DALWN0980+A&apos;&amp;
SYS++WN:DAL&apos;&amp;
PRE+US&apos;&amp;
UID+45995132:DALWN0980+A&apos;&amp;
SYS++WN:DAL&apos;&amp;
PRE+US&apos;&amp;
UID+45995132:DALWN0980+A&apos;&amp;
SYS++WN:DAL&apos;&amp;
PRE+US&apos;&amp;
SEQ++3]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2024:7:14&apos;&amp;
EMS++PT:2+NM+1&apos;&amp;
TIF+SMITH::1+JANE&apos;&amp;
ETI+:1+UN:Y:Y::SMITH:JANE&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+100724:0600:100724:0905+DAL+ATL+WN+2367:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+WN:4GXBQT&apos;&amp;
RPI+1+HK&apos;&amp;
STX+TSA&apos;&amp;
APD+7M8:0:0205::3+:1+:N+721:M&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
FSD&apos;&amp;
TVL+100724:0600:100724:0905+DAL+ATL&apos;&amp;
IFT+ACO+AIRCRAFT OWNER SOUTHWEST AIRLINES TEXAS&apos;&amp;
DUM&apos;&amp;
SGR+BND+:1&apos;&amp;
DUM&apos;&amp;
EMS++OT:13+AP+3&apos;&amp;
LFT+3:5+NCE&apos;&amp;
EMS++OT:12+TK+4&apos;&amp;
TKE++OK:270624::DALWN0980&apos;&amp;
EMS++OT:16+SSR+5&apos;&amp;
SSR+ERBD:HK:1:WN&apos;&amp;
PTS+++++I+0G6&apos;&amp;
STX+CGB&apos;&amp;
REF+ST:1*PT:2&apos;&amp;
EMS++OT:19+OPW+6&apos;&amp;
OPE+DALWN0980:080724:1:14:WN REQUIRES DOCUMENT ON OR BEFORE 09JUL\:0700::0700&apos;&amp;
REF+OT:16&apos;&amp;
EMS++OT:18+OPC+7&apos;&amp;
OPE+DALWN0980:090724:1:16:WN CANCELLATION DUE TO NO DOCUMENT::0700&apos;&amp;
REF+OT:16&apos;&amp;
EMS++OT:24+OPC+8&apos;&amp;
OPE+DALWN0980:280624:1:8:WN CANCELLATION DUE TO NO TICKET DAL TIME ZONE::2359&apos;&amp;
REF+ST:1*PT:2&apos;&amp;
EMS++OT:11+RM+9&apos;&amp;
MIR+RM::NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN\: FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS - GGAMAUSHAZ&apos;&amp;
ERM+RM::NOTIFY PASSENGER PRIOR TO TICKET PURCHASE \&amp; CHECK-IN\: FEDERAL LAWS FORBID THE CARRIAGE OF HAZARDOUS MATERIALS - GGAMAUSHAZ&apos;&amp;
REF+ST:1&apos;&amp;
EMS++OT:0+ES&apos;&amp;
ISI+NCE1A0955:B+270624:YGSU:DALWN0980+G&apos;&amp;
EMS+++SP&apos;&amp;
RCI+1A:4GWA7Q:S:270624&apos;&amp;
RSI+SP:YGSU:DALWN0980]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="34" responseEndLine="186" responseBeginLine="184" endLine="182" beginLine="178" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="KO"><COMMENT> Catch the correct envelope number of parent PNR</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:19:01.931967 - 27 Jun 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[SU&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: The global pattern match failed (3 patterns, RE result: -1)." compareAt="08:19:02.005219 - 27 Jun 2024"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[{(multi).*}&apos;&amp;
PNH++{%env_num2%=.{1}}&apos;&amp;
{(multi).*}&apos;&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[MSG+:M&apos;&amp;
ERC+1:EC:1A&apos;&amp;
IFT+C:50:::EN+CHECK FORMAT&apos;]]></TEXT></RECEIVED></UNMATCH></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="34"><QUERY filename="" loop="0" sentAt="08:19:02.006569 - 27 Jun 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="35" responseEndLine="217" responseBeginLine="204" endLine="202" beginLine="196" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="looping"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:19:02.061203 - 27 Jun 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[++++FR:EUR:FR+A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[27JUN24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;P&apos;, received &apos;C&apos;." compareAt="08:19:02.169502 - 27 Jun 2024"><TEXT><![CDATA[UNH++]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[PURCRR]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[CONTRL]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[14]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[2]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:1:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[1A]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UN]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[27JUN24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCI+01MAKHI32B0001+1ASI+NONE+7&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCM+1+PURCRQ:14:1:1A+4+18&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[SPR+++2005:8:8+2100:12:12]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+{%backend%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{%message_id%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{%sdi_date2%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="35" responseEndLine="217" responseBeginLine="204" endLine="202" beginLine="196" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="1" sentAt="08:19:05.174015 - 27 Jun 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[++++FR:EUR:FR+A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[27JUN24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;P&apos;, received &apos;C&apos;." compareAt="08:19:05.214374 - 27 Jun 2024"><TEXT><![CDATA[UNH++]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[PURCRR]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[CONTRL]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[14]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[2]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:1:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[1A]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UN]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[27JUN24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCI+00649HNIU30001+1ASI+NONE+7&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCM+1+PURCRQ:14:1:1A+4+18&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[SPR+++2005:8:8+2100:12:12]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><VARIABLE name="recloc2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+{%backend%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{%message_id%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{%sdi_date2%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="36" responseEndLine="237" responseBeginLine="231" endLine="230" beginLine="226" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/Remove_SSR_split_child_Feed.cry" loop="0" sentAt="08:19:08.225184 - 27 Jun 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;P&apos;, received &apos;C&apos;." compareAt="08:19:08.277982 - 27 Jun 2024"><TEXT><![CDATA[UNH++]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[PUPIRR]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[CONTRL]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[14]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[2]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:1:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[1A]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UN]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{*}&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCI+01MJXVSCGA0001+1ASI+NONE+7&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[IRV+OBE+SONPK4]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCM+1+PUPIRQ:14:1:1A+4+18]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[BLB+{*}+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C{%raw_binary%=(multi).*}UNT\x1D2\x1D1\x1C&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION></TRANSACTION><ERROR filename="" line="248" severity="Fatal Error">The variable &apos;global_regression.openpnr_payload&apos; is not defined</ERROR><STATISTIC><STATISTIC_ELEMENT name="Message in">38</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">18808</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">38</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">1374</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">6</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">38</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">37</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.973684</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">22373.6</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">2.481</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">7206.4</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">32</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">9</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">5</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">5</STATISTIC_ELEMENT></STATISTIC></xml>