<xml scenarioFilename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry"><SCRIPT type="Initialize">import json
import re
import generic_lib

from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.

def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;id&apos;, &apos;reference&apos;, &apos;creation&apos;, &apos;travelers&apos;, &apos;products&apos;, &apos;contacts&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=&quot;NCE6X0100&quot;, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;contacts&apos;]), expected=4, item_name=&apos;number of contacts&apos;)
        contacts_1 = openpnr[&apos;contacts&apos;][0]
        contacts_2 = openpnr[&apos;contacts&apos;][1]
        contacts_3 = openpnr[&apos;contacts&apos;][2]
        contacts_4 = openpnr[&apos;contacts&apos;][3]

        #Check service data for AP element + SSR CTCX element
        assert_equal(actual=contacts_1[&apos;type&apos;], expected=&apos;contact&apos;, item_name=&apos;contact type&apos;)
        assert_equal(actual=contacts_1[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AP-2&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_1[&apos;purpose&apos;], expected= [u&apos;STANDARD&apos;], item_name=&apos;contact purpose&apos;)
        assert_equal(actual=contacts_1[&apos;freeFlowFormat&apos;], expected=&apos;+33600000666&apos;, item_name=&apos;contact freeFlowFormat&apos;)

        assert_equal(actual=contacts_2[&apos;type&apos;], expected=&apos;contact&apos;, item_name=&apos;contact type&apos;)
        assert_equal(actual=contacts_2[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-SSR-10&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_2[&apos;phone&apos;][&apos;number&apos;], expected=&quot;0612345678&quot;, item_name=&apos;contact email/address&apos;)
        assert_equal(actual=contacts_2[&apos;purpose&apos;], expected= [u&apos;NOTIFICATION&apos;], item_name=&apos;contact purpose&apos;)
        assert_equal(actual=contacts_2[&apos;security&apos;][&apos;allowedParties&apos;][0][&apos;party&apos;][&apos;company&apos;][&apos;code&apos;], expected=&apos;6X&apos;, item_name=&apos;contact security/code&apos;)
        assert_equal(actual=contacts_2[&apos;security&apos;][&apos;consentPermissions&apos;][0][&apos;validity&apos;][&apos;validityStatus&apos;], expected=&apos;GRANTED&apos;, item_name=&apos;contact security/validityStatus&apos;)

		#assert_equal(actual=contacts_3[&apos;type&apos;], expected=&apos;contact&apos;, item_name=&apos;contact type&apos;)
        assert_equal(actual=contacts_3[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-SSR-11&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_3[&apos;email&apos;][&apos;address&apos;], expected=&quot;BART.SIMPSON//MAIL.COM&quot;, item_name=&apos;contact email/address&apos;)
        assert_equal(actual=contacts_3[&apos;purpose&apos;], expected= [u&apos;NOTIFICATION&apos;], item_name=&apos;contact purpose&apos;)
        assert_equal(actual=contacts_3[&apos;security&apos;][&apos;allowedParties&apos;][0][&apos;party&apos;][&apos;company&apos;][&apos;code&apos;], expected=&apos;6X&apos;, item_name=&apos;contact security/code&apos;)
        assert_equal(actual=contacts_3[&apos;security&apos;][&apos;consentPermissions&apos;][0][&apos;validity&apos;][&apos;validityStatus&apos;], expected=&apos;GRANTED&apos;, item_name=&apos;contact security/validityStatus&apos;)

        assert_equal(actual=contacts_4[&apos;type&apos;], expected=&apos;contact&apos;, item_name=&apos;contact type&apos;)
        assert_equal(actual=contacts_4[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-SSR-12&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_4[&apos;purpose&apos;], expected= [u&apos;NOTIFICATION&apos;], item_name=&apos;contact purpose&apos;)
        assert_equal(actual=contacts_4[&apos;isDeclined&apos;], expected= True, item_name=&apos;contact security/code&apos;)
        assert_equal(actual=contacts_4[&apos;security&apos;][&apos;allowedParties&apos;][0][&apos;party&apos;][&apos;company&apos;][&apos;code&apos;], expected=&apos;6X&apos;, item_name=&apos;contact security/code&apos;)

    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="106" beginLine="105" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:54.119751 - 02 Sep 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="14:24:54.179347 - 02 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" endLine="107" beginLine="106" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:54.181697 - 02 Sep 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="14:24:54.248771 - 02 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="3" endLine="108" beginLine="107" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:54.248964 - 02 Sep 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="14:24:54.330067 - 02 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="115" beginLine="114" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:54.330634 - 02 Sep 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:24:54.397971 - 02 Sep 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="117" beginLine="116" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:56.413172 - 02 Sep 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0955]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:24:56.477132 - 02 Sep 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="121" responseBeginLine="121" endLine="119" beginLine="118" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:56.477453 - 02 Sep 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[***************]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="14:24:56.689237 - 02 Sep 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/02SEP/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" endLine="128" beginLine="127" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><COMMENT> 2. Create simple PNR with mandatory elements</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:56.689586 - 02 Sep 2024"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Pax1.book()}]]></EXPRESSION><VALUE><![CDATA[NM1ARQE/EIMB]]></VALUE></REGULAR_EXPRESSION></QUERY><REPLY receiveAt="14:24:56.795523 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
  1.ARQE/EIMB&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="8" endLine="129" beginLine="128" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:56.795726 - 02 Sep 2024"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_6X_daily.book(1)}]]></EXPRESSION><VALUE><![CDATA[SS6X562Y25OCTNCELHR1]]></VALUE></REGULAR_EXPRESSION></QUERY><REPLY receiveAt="14:24:57.177931 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
  1.ARQE/EIMB&amp;
  2  6X 562 Y 25OCT 5 NCELHR DK1  0600 0710  25OCT  E  0 ERJ CM&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="9" endLine="130" beginLine="129" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:57.178135 - 02 Sep 2024"><TEXT><![CDATA[AP+33600000666]]></TEXT></QUERY><REPLY receiveAt="14:24:57.302751 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
  1.ARQE/EIMB&amp;
  2  6X 562 Y 25OCT 5 NCELHR DK1  0600 0710  25OCT  E  0 ERJ CM&amp;
  3 AP +33600000666&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="10" endLine="131" beginLine="130" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:57.302920 - 02 Sep 2024"><TEXT><![CDATA[TKOK;RFTEST]]></TEXT></QUERY><REPLY receiveAt="14:24:57.462230 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
RF TEST&amp;
  1.ARQE/EIMB&amp;
  2  6X 562 Y 25OCT 5 NCELHR DK1  0600 0710  25OCT  E  0 ERJ CM&amp;
  3 AP +33600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="11" endLine="132" beginLine="131" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:57.462412 - 02 Sep 2024"><TEXT><![CDATA[ES/G]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-B]]></TEXT></QUERY><REPLY receiveAt="14:24:57.686193 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
RF TEST&amp;
  1.ARQE/EIMB&amp;
  2  6X 562 Y 25OCT 5 NCELHR DK1  0600 0710  25OCT  E  0 ERJ CM&amp;
  3 AP +33600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
  * ES/G B NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="12" responseEndLine="138" responseBeginLine="136" endLine="133" beginLine="132" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:57.686342 - 02 Sep 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><COMPARISON compareAt="14:24:58.192393 - 02 Sep 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[           YG]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  2SEP24/1224]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[7OLAZR]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  1.ARQE/EIMB&amp;
  2  6X 562 Y 25OCT 5 NCELHR HK1  0600 0710  25OCT  E  6X/7OLAZR&amp;
  3 AP +33600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
  * ES/G 02SEP/YGSU/NCE6X0100&amp;
    NCE6X0100-B&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="13" responseEndLine="273" responseBeginLine="272" endLine="270" beginLine="147" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:24:59.207367 - 02 Sep 2024"><TEXT><![CDATA[PATCH /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[/elements HTTP/1.1&amp;
Content-Type: text/plain&amp;
Debug-Format: json&amp;
If-Match: 1&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline"><VALUE><![CDATA[eyJub25jZSI6Ik56STRNekkwT0RJMU56VXhPREV3TXc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjQ6NTAuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJWSFZjbkJzNkZTK3lraWZCaUcyWWpKYVE1UWs9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
[&amp;
\t\{&amp;
\t\t&quot;action&quot;: &quot;add&quot;,&amp;
        &quot;model&quot;: &quot;Contact&quot;,&amp;
        &quot;element&quot;: \{&amp;
\t\t\t&quot;type&quot;: &quot;contact&quot;,&amp;
\t\t\t&quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-SSR-8&quot;,&amp;
\t\t\t&quot;phone&quot;: \{&amp;
\t\t\t\t&quot;number&quot;: &quot;0612345678&quot;&amp;
\t\t\t\},&amp;
\t\t\t&quot;purpose&quot;: [&amp;
\t\t\t\t&quot;NOTIFICATION&quot;&amp;
\t\t\t],&amp;
\t\t\t&quot;travelerRefs&quot;: [&amp;
\t\t\t\t\{&amp;
\t\t\t\t\t&quot;type&quot;: &quot;stakeholder&quot;,&amp;
\t\t\t\t\t&quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-1&quot;,&amp;
\t\t\t\t\t&quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
\t\t\t\t\}&amp;
\t\t\t],&amp;
\t\t\t&quot;security&quot;: \{&amp;
\t\t\t\t&quot;allowedParties&quot;: [&amp;
\t\t\t\t\t\{&amp;
\t\t\t\t\t\t&quot;party&quot;: \{&amp;
\t\t\t\t\t\t\t&quot;company&quot;: \{&amp;
\t\t\t\t\t\t\t\t&quot;code&quot;: &quot;6X&quot;&amp;
\t\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\}&amp;
\t\t\t\t],&amp;
\t\t\t\t&quot;consentPermissions&quot;: [&amp;
\t\t\t\t\t\{&amp;
\t\t\t\t\t\t&quot;validity&quot;: \{&amp;
\t\t\t\t\t\t\t&quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\}&amp;
\t\t\t\t]&amp;
\t\t\t\}&amp;
\t\t\}&amp;
    \},&amp;
    \{&amp;
\t\t&quot;action&quot;: &quot;add&quot;,&amp;
        &quot;model&quot;: &quot;Contact&quot;,&amp;
        &quot;element&quot;: \{&amp;
\t\t\t&quot;type&quot;: &quot;contact&quot;,&amp;
\t\t\t&quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-SSR-9&quot;,&amp;
\t\t\t&quot;email&quot;: \{&amp;
\t\t\t\t&quot;address&quot;: &quot;BART.SIMPSON//MAIL.COM&quot;&amp;
\t\t\t\},&amp;
\t\t\t&quot;purpose&quot;: [&amp;
\t\t\t\t&quot;NOTIFICATION&quot;&amp;
\t\t\t],&amp;
\t\t\t&quot;travelerRefs&quot;: [&amp;
\t\t\t\t\{&amp;
\t\t\t\t\t&quot;type&quot;: &quot;stakeholder&quot;,&amp;
\t\t\t\t\t&quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-1&quot;,&amp;
\t\t\t\t\t&quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
\t\t\t\t\}&amp;
\t\t\t],&amp;
\t\t\t&quot;security&quot;: \{&amp;
\t\t\t\t&quot;allowedParties&quot;: [&amp;
\t\t\t\t\t\{&amp;
\t\t\t\t\t\t&quot;party&quot;: \{&amp;
\t\t\t\t\t\t\t&quot;company&quot;: \{&amp;
\t\t\t\t\t\t\t\t&quot;code&quot;: &quot;6X&quot;&amp;
\t\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\}&amp;
\t\t\t\t],&amp;
\t\t\t\t&quot;consentPermissions&quot;: [&amp;
\t\t\t\t\t\{&amp;
\t\t\t\t\t\t&quot;validity&quot;: \{&amp;
\t\t\t\t\t\t\t&quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\}&amp;
\t\t\t\t]&amp;
\t\t\t\}&amp;
\t\t\}&amp;
    \},&amp;
    \{&amp;
\t\t&quot;action&quot;: &quot;add&quot;,&amp;
        &quot;model&quot;: &quot;Contact&quot;,&amp;
        &quot;element&quot;: \{&amp;
\t\t\t&quot;type&quot;: &quot;contact&quot;,&amp;
\t\t\t&quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-SSR-10&quot;,&amp;
\t\t\t&quot;purpose&quot;: [&amp;
\t\t\t\t&quot;NOTIFICATION&quot;&amp;
\t\t\t],&amp;
\t\t\t&quot;travelerRefs&quot;: [&amp;
\t\t\t\t\{&amp;
\t\t\t\t\t&quot;type&quot;: &quot;stakeholder&quot;,&amp;
\t\t\t\t\t&quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-1&quot;,&amp;
\t\t\t\t\t&quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
\t\t\t\t\}&amp;
\t\t\t],&amp;
\t\t\t&quot;isDeclined&quot;: true,&amp;
\t\t\t&quot;security&quot;: \{&amp;
\t\t\t\t&quot;allowedParties&quot;: [&amp;
\t\t\t\t\t\{&amp;
\t\t\t\t\t\t&quot;party&quot;: \{&amp;
\t\t\t\t\t\t\t&quot;company&quot;: \{&amp;
\t\t\t\t\t\t\t\t&quot;code&quot;: &quot;6X&quot;&amp;
\t\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\}&amp;
\t\t\t\t],&amp;
\t\t\t\t&quot;consentPermissions&quot;: [&amp;
\t\t\t\t\t\{&amp;
\t\t\t\t\t\t&quot;validity&quot;: \{&amp;
\t\t\t\t\t\t\t&quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
\t\t\t\t\t\t\}&amp;
\t\t\t\t\t\}&amp;
\t\t\t\t]&amp;
\t\t\t\}&amp;
\t\t\}&amp;
    \}&amp;
]]]></TEXT></QUERY><COMPARISON compareAt="14:25:00.035166 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[ama-request-id:0001NVHDTJ6QHN&amp;
content-length:3368&amp;
etag:2&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;7OLAZR&quot;, &amp;
    &quot;version&quot;: &quot;2&quot;, &amp;
    &quot;openPnr&quot;: \{&amp;
        &quot;id&quot;: &quot;7OLAZR-2024-09-02&quot;, &amp;
        &quot;type&quot;: &quot;pnr&quot;, &amp;
        &quot;reference&quot;: &quot;7OLAZR&quot;, &amp;
        &quot;version&quot;: &quot;2&quot;, &amp;
        &quot;creation&quot;: \{&amp;
            &quot;dateTime&quot;: &quot;2024-09-02T12:24:00Z&quot;, &amp;
            &quot;pointOfSale&quot;: \{&amp;
                &quot;office&quot;: \{&amp;
                    &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                    &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                    &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                    &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
                \}, &amp;
                &quot;login&quot;: \{&amp;
                    &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                    &quot;initials&quot;: &quot;YG&quot;, &amp;
                    &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                    &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                    &quot;cityCode&quot;: &quot;NCE&quot;&amp;
                \}&amp;
            \}&amp;
        \}, &amp;
        &quot;lastModification&quot;: \{&amp;
            &quot;dateTime&quot;: &quot;2024-09-02T12:24:59Z&quot;&amp;
        \}, &amp;
        &quot;travelers&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                &quot;names&quot;: [&amp;
                    \{&amp;
                        &quot;firstName&quot;: &quot;EIMB&quot;, &amp;
                        &quot;lastName&quot;: &quot;ARQE&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;contacts&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;contact&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AP-2&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                    \}, &amp;
                    \{&amp;
                        &quot;type&quot;: &quot;contact&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-10&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                    \}, &amp;
                    \{&amp;
                        &quot;type&quot;: &quot;contact&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-11&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                    \}, &amp;
                    \{&amp;
                        &quot;type&quot;: &quot;contact&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-12&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;passenger&quot;: \{&amp;
                    &quot;uniqueIdentifier&quot;: &quot;6104F3D400004A47&quot;&amp;
                \}&amp;
            \}&amp;
        ], &amp;
        &quot;products&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;product&quot;, &amp;
                &quot;subType&quot;: &quot;AIR&quot;, &amp;
                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AIR-1&quot;, &amp;
                &quot;airSegment&quot;: \{&amp;
                    &quot;departure&quot;: \{&amp;
                        &quot;iataCode&quot;: &quot;NCE&quot;, &amp;
                        &quot;localDateTime&quot;: &quot;2024-10-25T06:00:00&quot;&amp;
                    \}, &amp;
                    &quot;arrival&quot;: \{&amp;
                        &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                        &quot;localDateTime&quot;: &quot;2024-10-25T07:10:00&quot;&amp;
                    \}, &amp;
                    &quot;marketing&quot;: \{&amp;
                        &quot;flightDesignator&quot;: \{&amp;
                            &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                            &quot;flightNumber&quot;: &quot;562&quot;&amp;
                        \}, &amp;
                        &quot;bookingClass&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;, &amp;
                            &quot;cabin&quot;: \{&amp;
                                &quot;code&quot;: &quot;Y&quot;&amp;
                            \}, &amp;
                            &quot;subClass&quot;: \{&amp;
                                &quot;code&quot;: 0, &amp;
                                &quot;pointOfSale&quot;: \{&amp;
                                    &quot;office&quot;: \{&amp;
                                        &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                    \}, &amp;
                                    &quot;login&quot;: \{&amp;
                                        &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                    \}&amp;
                                \}, &amp;
                                &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                            \}, &amp;
                            &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                        \}, &amp;
                        &quot;id&quot;: &quot;6X-562-2024-10-25-NCE-LHR&quot;&amp;
                    \}, &amp;
                    &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                    &quot;deliveries&quot;: [&amp;
                        \{&amp;
                            &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-BKG-1&quot;, &amp;
                            &quot;distributionId&quot;: &quot;600553D500018E8E&quot;, &amp;
                            &quot;traveler&quot;: \{&amp;
                                &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                            \}&amp;
                        \}&amp;
                    ], &amp;
                    &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                    &quot;notAcknowledged&quot;: false&amp;
                \}&amp;
            \}&amp;
        ], &amp;
        &quot;contacts&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;contact&quot;, &amp;
                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AP-2&quot;, &amp;
                &quot;purpose&quot;: [&amp;
                    &quot;STANDARD&quot;&amp;
                ], &amp;
                &quot;freeFlowFormat&quot;: &quot;+33600000666&quot;, &amp;
                &quot;travelerRefs&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ]&amp;
            \}, &amp;
            \{&amp;
                &quot;type&quot;: &quot;contact&quot;, &amp;
                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-10&quot;, &amp;
                &quot;phone&quot;: \{&amp;
                    &quot;number&quot;: &quot;0612345678&quot;&amp;
                \}, &amp;
                &quot;purpose&quot;: [&amp;
                    &quot;NOTIFICATION&quot;&amp;
                ], &amp;
                &quot;travelerRefs&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;security&quot;: \{&amp;
                    &quot;allowedParties&quot;: [&amp;
                        \{&amp;
                            &quot;party&quot;: \{&amp;
                                &quot;company&quot;: \{&amp;
                                    &quot;code&quot;: &quot;6X&quot;&amp;
                                \}&amp;
                            \}&amp;
                        \}&amp;
                    ], &amp;
                    &quot;consentPermissions&quot;: [&amp;
                        \{&amp;
                            &quot;validity&quot;: \{&amp;
                                &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                            \}&amp;
                        \}&amp;
                    ]&amp;
                \}&amp;
            \}, &amp;
            \{&amp;
                &quot;type&quot;: &quot;contact&quot;, &amp;
                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-11&quot;, &amp;
                &quot;email&quot;: \{&amp;
                    &quot;address&quot;: &quot;BART.SIMPSON//MAIL.COM&quot;&amp;
                \}, &amp;
                &quot;purpose&quot;: [&amp;
                    &quot;NOTIFICATION&quot;&amp;
                ], &amp;
                &quot;travelerRefs&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;security&quot;: \{&amp;
                    &quot;allowedParties&quot;: [&amp;
                        \{&amp;
                            &quot;party&quot;: \{&amp;
                                &quot;company&quot;: \{&amp;
                                    &quot;code&quot;: &quot;6X&quot;&amp;
                                \}&amp;
                            \}&amp;
                        \}&amp;
                    ], &amp;
                    &quot;consentPermissions&quot;: [&amp;
                        \{&amp;
                            &quot;validity&quot;: \{&amp;
                                &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                            \}&amp;
                        \}&amp;
                    ]&amp;
                \}&amp;
            \}, &amp;
            \{&amp;
                &quot;type&quot;: &quot;contact&quot;, &amp;
                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-12&quot;, &amp;
                &quot;purpose&quot;: [&amp;
                    &quot;NOTIFICATION&quot;&amp;
                ], &amp;
                &quot;travelerRefs&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;isDeclined&quot;: true, &amp;
                &quot;security&quot;: \{&amp;
                    &quot;allowedParties&quot;: [&amp;
                        \{&amp;
                            &quot;party&quot;: \{&amp;
                                &quot;company&quot;: \{&amp;
                                    &quot;code&quot;: &quot;6X&quot;&amp;
                                \}&amp;
                            \}&amp;
                        \}&amp;
                    ]&amp;
                \}&amp;
            \}&amp;
        ], &amp;
        &quot;automatedProcesses&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;automated-process&quot;, &amp;
                &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-TK-3&quot;, &amp;
                &quot;code&quot;: &quot;OK&quot;, &amp;
                &quot;dateTime&quot;: &quot;2024-09-02T00:00:00&quot;, &amp;
                &quot;office&quot;: \{&amp;
                    &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
                \}, &amp;
                &quot;travelers&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;products&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;product&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AIR-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        ]&amp;
    \}&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14" responseEndLine="300" responseBeginLine="289" endLine="288" beginLine="282" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:00.037770 - 02 Sep 2024"><TEXT><![CDATA[GET /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[ HTTP/1.1&amp;
Content-Type: text/plain&amp;
Debug-format: json&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_2"><VALUE><![CDATA[eyJub25jZSI6Ik1UUTJNelkxTVRVMk5qUXpOREUxTWc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjQ6NTAuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJxbTEya2s3SE1xR2xEYm5LTUJlTWQ4Y2pFMDg9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT></QUERY><COMPARISON compareAt="14:25:00.304612 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001NVHDZJ6QHO]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2161]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[ChE3T0xBWlItMjAyNC0wOS0wMhIDcG5yGgY3T0xBWlIiATI6VRoUMjAyNC0wOS0wMlQxMjoyNDowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0wOS0wMlQxMjoyNDo1OVp6ygIKC3N0YWtlaG9sZGVyEho3T0xBWlItMjAyNC0wOS0wMi1QTlItTk0tMSIMEgRFSU1CGgRBUlFFcjwKB2NvbnRhY3QSGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1BUC0yGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPgoHY29udGFjdBIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMBoVcHJvY2Vzc2VkUG5yLmNvbnRhY3Rzcj4KB2NvbnRhY3QSHDdPTEFaUi0yMDI0LTA5LTAyLVBOUi1TU1ItMTEaFXByb2Nlc3NlZFBuci5jb250YWN0c3I+Cgdjb250YWN0Ehw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTEyGhVwcm9jZXNzZWRQbnIuY29udGFjdHOiARISEDYxMDRGM0Q0MDAwMDRBNDeCAcQCCgdwcm9kdWN0EAEaGzdPTEFaUi0yMDI0LTA5LTAyLVBOUi1BSVItMSKZAgoaCgNOQ0UaEzIwMjQtMTAtMjVUMDY6MDA6MDASGgoDTEhSGhMyMDI0LTEwLTI1VDA3OjEwOjAwIk0KCQoCNlgSAzU2MhIlCgFZEgMKAVkaEgoAEgwKBBoCNlgSBCoCRlIgASIHRUNPTk9NWTIZNlgtNTYyLTIwMjQtMTAtMjUtTkNFLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzdPTEFaUi0yMDI0LTA5LTAyLVBOUi1CS0ctMRoQNjAwNTUzRDUwMDAxOEU4RVpBCgtzdGFrZWhvbGRlchIaN09MQVpSLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAsgF7Cgdjb250YWN0Eho3T0xBWlItMjAyNC0wOS0wMi1QTlItQVAtMkIBAVoOCgwrMzM2MDAwMDA2NjZiQQoLc3Rha2Vob2xkZXISGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzsgGOAQoHY29udGFjdBIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMCIMGgowNjEyMzQ1Njc4QgECYkEKC3N0YWtlaG9sZGVyEho3T0xBWlItMjAyNC0wOS0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBEBIICgYKBBICNlgaBAoCCAGyAZoBCgdjb250YWN0Ehw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTExMhgKFkJBUlQuU0lNUFNPTi8vTUFJTC5DT01CAQJiQQoLc3Rha2Vob2xkZXISGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugEQEggKBgoEEgI2WBoECgIIAbIBfwoHY29udGFjdBIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMkIBAmJBCgtzdGFrZWhvbGRlchIaN09MQVpSLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOiAQIIAboBChIICgYKBBICNli6AdUBChFhdXRvbWF0ZWQtcHJvY2VzcxIaN09MQVpSLTIwMjQtMDktMDItUE5SLVRLLTMYBSITMjAyNC0wOS0wMlQwMDowMDowMCoLCglOQ0U2WDAxMDBaQQoLc3Rha2Vob2xkZXISGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSGzdPTEFaUi0yMDI0LTA5LTAyLVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="15" responseEndLine="325" responseBeginLine="318" endLine="316" beginLine="310" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:00.306060 - 02 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Debug-Format: debug&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_3"><VALUE><![CDATA[eyJub25jZSI6Ik1qRTFPVGN3TVRrMk5UazNORFF5TlE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjQ6NTAuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJNUmZHTzAvUk5hNHhOc3VQdVZVZm03UUsralU9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ChE3T0xBWlItMjAyNC0wOS0wMhIDcG5yGgY3T0xBWlIiATI6VRoUMjAyNC0wOS0wMlQxMjoyNDowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0wOS0wMlQxMjoyNDo1OVp6ygIKC3N0YWtlaG9sZGVyEho3T0xBWlItMjAyNC0wOS0wMi1QTlItTk0tMSIMEgRFSU1CGgRBUlFFcjwKB2NvbnRhY3QSGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1BUC0yGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPgoHY29udGFjdBIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMBoVcHJvY2Vzc2VkUG5yLmNvbnRhY3Rzcj4KB2NvbnRhY3QSHDdPTEFaUi0yMDI0LTA5LTAyLVBOUi1TU1ItMTEaFXByb2Nlc3NlZFBuci5jb250YWN0c3I+Cgdjb250YWN0Ehw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTEyGhVwcm9jZXNzZWRQbnIuY29udGFjdHOiARISEDYxMDRGM0Q0MDAwMDRBNDeCAcQCCgdwcm9kdWN0EAEaGzdPTEFaUi0yMDI0LTA5LTAyLVBOUi1BSVItMSKZAgoaCgNOQ0UaEzIwMjQtMTAtMjVUMDY6MDA6MDASGgoDTEhSGhMyMDI0LTEwLTI1VDA3OjEwOjAwIk0KCQoCNlgSAzU2MhIlCgFZEgMKAVkaEgoAEgwKBBoCNlgSBCoCRlIgASIHRUNPTk9NWTIZNlgtNTYyLTIwMjQtMTAtMjUtTkNFLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzdPTEFaUi0yMDI0LTA5LTAyLVBOUi1CS0ctMRoQNjAwNTUzRDUwMDAxOEU4RVpBCgtzdGFrZWhvbGRlchIaN09MQVpSLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAsgF7Cgdjb250YWN0Eho3T0xBWlItMjAyNC0wOS0wMi1QTlItQVAtMkIBAVoOCgwrMzM2MDAwMDA2NjZiQQoLc3Rha2Vob2xkZXISGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzsgGOAQoHY29udGFjdBIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMCIMGgowNjEyMzQ1Njc4QgECYkEKC3N0YWtlaG9sZGVyEho3T0xBWlItMjAyNC0wOS0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBEBIICgYKBBICNlgaBAoCCAGyAZoBCgdjb250YWN0Ehw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTExMhgKFkJBUlQuU0lNUFNPTi8vTUFJTC5DT01CAQJiQQoLc3Rha2Vob2xkZXISGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugEQEggKBgoEEgI2WBoECgIIAbIBfwoHY29udGFjdBIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMkIBAmJBCgtzdGFrZWhvbGRlchIaN09MQVpSLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOiAQIIAboBChIICgYKBBICNli6AdUBChFhdXRvbWF0ZWQtcHJvY2VzcxIaN09MQVpSLTIwMjQtMDktMDItUE5SLVRLLTMYBSITMjAyNC0wOS0wMlQwMDowMDowMCoLCglOQ0U2WDAxMDBaQQoLc3Rha2Vob2xkZXISGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSGzdPTEFaUi0yMDI0LTA5LTAyLVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="14:25:00.467065 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001NVHE5J6QHO]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[3321]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;7OLAZR-2024-09-02&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;7OLAZR&quot;, &amp;
    &quot;version&quot;: &quot;2&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:24:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:24:59Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;EIMB&quot;, &amp;
                    &quot;lastName&quot;: &quot;ARQE&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-10&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-11&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-12&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;6104F3D400004A47&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-25T06:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-25T07:10:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;562&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-562-2024-10-25-NCE-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600553D500018E8E&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;+33600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-10&quot;, &amp;
            &quot;phone&quot;: \{&amp;
                &quot;number&quot;: &quot;0612345678&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;consentPermissions&quot;: [&amp;
                    \{&amp;
                        &quot;validity&quot;: \{&amp;
                            &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-11&quot;, &amp;
            &quot;email&quot;: \{&amp;
                &quot;address&quot;: &quot;BART.SIMPSON//MAIL.COM&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;consentPermissions&quot;: [&amp;
                    \{&amp;
                        &quot;validity&quot;: \{&amp;
                            &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-12&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;isDeclined&quot;: true, &amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-TK-3&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-09-02T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="16" responseEndLine="341" responseBeginLine="336" endLine="334" beginLine="333" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:00.468823 - 02 Sep 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="14:25:00.860930 - 02 Sep 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[           AB]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  2SEP24/1224]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(local).*?SSR}]]></EXPRESSION><VALUE><![CDATA[  1.ARQE/EIMB&amp;
  2  6X 562 Y 25OCT 5 NCELHR HK1  0600 0710  25OCT  E  6X/7OLAZR&amp;
  3 AP +33600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
  5 SSR]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ CTCM 6X HK1 0612345678&amp;
  6 SSR CTCE 6X HK1 BART.SIMPSON//MAIL.COM&amp;
  7 SSR CTCR 6X HK1&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  8 OPC-24OCT:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * ES/G 02SEP/YGSU/NCE6X0100&amp;
    NCE6X0100-B&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="17" responseEndLine="361" responseBeginLine="359" endLine="357" beginLine="353" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:00.862485 - 02 Sep 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:25:01.072577 - 02 Sep 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:7OLAZR::020924:1224&apos;&amp;
RSI+RP:ABSU:NCE6X0100:00631002+NCE6X0100+NCE+NCE6X0100:1127YG:020924:00631002:1224&apos;&amp;
LFT+3:P12+--- RLR ---&apos;&amp;
STX+RLR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00360124:SYD6X0102+A&apos;&amp;
SYS++6X:SYD&apos;&amp;
PRE+AU&apos;&amp;
SEQ++3]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2024:10:29&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+ARQE::1+EIMB&apos;&amp;
ETI+:1+UN:Y:Y::ARQE:EIMB&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+251024:0600:251024:0710+NCE+LHR+6X+562:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+6X:7OLAZR&apos;&amp;
RPI+1+HK&apos;&amp;
APD+ERJ:0:0210::5+++648:M++M:CM&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
FSD&apos;&amp;
TVL+251024:0600:251024:0710+NCE+LHR&apos;&amp;
IFT+ACO+AIRCRAFT OWNER AMADEUS SIX&apos;&amp;
DUM&apos;&amp;
DUM&apos;&amp;
EMS++OT:2+AP+3&apos;&amp;
LFT+3:5+\+33600000666&apos;&amp;
EMS++OT:3+TK+4&apos;&amp;
TKE++OK:020924::NCE6X0100&apos;&amp;
EMS++OT:10+SSR+5&apos;&amp;
SSR+CTCM:HK:1:6X:::::0612345678&apos;&amp;
REF+PT:1&apos;&amp;
EMS++OT:11+SSR+6&apos;&amp;
SSR+CTCE:HK:1:6X:::::BART.SIMPSON//MAIL.COM&apos;&amp;
REF+PT:1&apos;&amp;
EMS++OT:12+SSR+7&apos;&amp;
SSR+CTCR:HK:1:6X&apos;&amp;
REF+PT:1&apos;&amp;
EMS++OT:8+OPC+8&apos;&amp;
OPE+NCE6X0100:241024:1:8:6X CANCELLATION DUE TO NO TICKET NCE TIME ZONE::2300&apos;&amp;
REF+ST:1*PT:1&apos;&amp;
EMS++OT:0+ES&apos;&amp;
ISI+NCE6X0100:B+020924:YGSU:NCE6X0100+G]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="18" endLine="371" beginLine="370" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><SCRIPT type="Exec">env_num = int (env_num)
env_num = env_num - 0
</SCRIPT><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:01.075062 - 02 Sep 2024"><TEXT><![CDATA[UNH++::&apos;&amp;
print(env_num)]]></TEXT></QUERY><REPLY receiveAt="14:25:01.120942 - 02 Sep 2024" filename="">UNB+IATB:1+1AAPITES3+TESAPI3+240902:1225+00PH8J3VE40002+00LH2ART6J0002++E&apos;&amp;
UNH+1+CONTRL:2:1:UN+********&apos;&amp;
UCI+00LH2ART6J0002+TESAPI3+1AAPITES3+7&apos;&amp;
UCM+1+UNKMSG:XX:X:XX+4+17&apos;&amp;
UNT+4+1&apos;&amp;
UNZ+1+00PH8J3VE40002&apos;</REPLY></TRANSACTION><TRANSACTION transactionCounter="18"><QUERY filename="" loop="0" sentAt="14:25:01.121628 - 02 Sep 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="19" responseEndLine="403" responseBeginLine="390" endLine="387" beginLine="381" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:01.169567 - 02 Sep 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE1A0900++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[02SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:25:01.241485 - 02 Sep 2024" match="OK"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[02SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[20240902\:12\:24\:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%backend%=*}]]></EXPRESSION><VALUE><![CDATA[SONPK4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:09:02:12:25:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%message_id%=*}]]></EXPRESSION><VALUE><![CDATA[4681452553]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%sdi_date2%=*}]]></EXPRESSION><VALUE><![CDATA[2024:09:02:12:25:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="20" responseEndLine="423" responseBeginLine="417" endLine="416" beginLine="412" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:01.244597 - 02 Sep 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[4681452553]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[SONPK4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[2024:09:02:12:25:00]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:25:01.296970 - 02 Sep 2024" match="OK"><TEXT><![CDATA[UNH++PUPIRR:14:1:1A+&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[4681452553]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+SONPK4&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:09:02:12:25:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
BLB+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1962]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%raw_binary%=(multi).*}]]></EXPRESSION><VALUE><![CDATA[\x0A\x8A\x0F\x12\xAD\x0E\x0A\x117OLAZR-2024-09-02\x12\x03pnr\x1A\x067OLAZR&quot;\x012:U\x1A\x142024-09-02T12:24:00Z&quot;=\x0A&quot;\x0A\x09NCE6X0100\x12\x0800631002\x1A\x026X&quot;\x07AIRLINE\x12\x17\x0A\x041127\x12\x02YG\x1A\x02SU*\x02FR2\x03NCEJ\x92\x02\x1A\x142024-09-02T12:24:59Z&quot;\x0D\x0A\x0B\x0A\x09SYD6X0102*\x11NDCX ORDER CREATE2\x03\x12\x011:E\x12\x10historyChangeLog\x18\x01&quot;\x1C7OLAZR-2024-09-02-PNR-SSR-10*\x07contact2\x08contacts:E\x12\x10historyChangeLog\x18\x01&quot;\x1C7OLAZR-2024-09-02-PNR-SSR-11*\x07contact2\x08contacts:E\x12\x10historyChangeLog\x18\x01&quot;\x1C7OLAZR-2024-09-02-PNR-SSR-12*\x07contact2\x08contactsz\xCA\x02\x0A\x0Bstakeholder\x12\x1A7OLAZR-2024-09-02-PNR-NM-1&quot;\x0C\x12\x04EIMB\x1A\x04ARQEr&lt;\x0A\x07contact\x12\x1A7OLAZR-2024-09-02-PNR-AP-2\x1A\x15processedPnr.contactsr&gt;\x0A\x07contact\x12\x1C7OLAZR-2024-09-02-PNR-SSR-10\x1A\x15processedPnr.contactsr&gt;\x0A\x07contact\x12\x1C7OLAZR-2024-09-02-PNR-SSR-11\x1A\x15processedPnr.contactsr&gt;\x0A\x07contact\x12\x1C7OLAZR-2024-09-02-PNR-SSR-12\x1A\x15processedPnr.contacts\xA2\x01\x12\x12\x106104F3D400004A47\x82\x01\xC8\x02\x0A\x07product\x10\x01\x1A\x1B7OLAZR-2024-09-02-PNR-AIR-1&quot;\x9D\x02\x0A\x1A\x0A\x03NCE\x1A\x132024-10-25T06:00:00\x12\x1A\x0A\x03LHR\x1A\x132024-10-25T07:10:00&quot;O\x0A\x09\x0A\x026X\x12\x03562\x12&apos;&amp;
\x0A\x01Y\x12\x03\x0A\x01Y\x1A\x14\x0A\x02\x08\x00\x12\x0C\x0A\x04\x1A\x026X\x12\x04*\x02FR \x01&quot;\x07ECONOMY2\x196X-562-2024-10-25-NCE-LHRJ\x02HKb\x84\x01\x0A\x10segment-delivery\x12\x1B7OLAZR-2024-09-02-PNR-BKG-1\x1A\x10600553D500018E8EZA\x0A\x0Bstakeholder\x12\x1A7OLAZR-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\x8A\x01\x01E\x92\x01\x02\x08\x00\xB2\x01z\x0A\x07contact\x12\x1A7OLAZR-2024-09-02-PNR-AP-2@\x01Z\x0E\x0A\x0C+33600000666bA\x0A\x0Bstakeholder\x12\x1A7OLAZR-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\xB2\x01\x8D\x01\x0A\x07contact\x12\x1C7OLAZR-2024-09-02-PNR-SSR-10&quot;\x0C\x1A\x0A0612345678@\x02bA\x0A\x0Bstakeholder\x12\x1A7OLAZR-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\xBA\x01\x10\x12\x08\x0A\x06\x0A\x04\x12\x026X\x1A\x04\x0A\x02\x08\x01\xB2\x01\x99\x01\x0A\x07contact\x12\x1C7OLAZR-2024-09-02-PNR-SSR-112\x18\x0A\x16BART.SIMPSON//MAIL.COM@\x02bA\x0A\x0Bstakeholder\x12\x1A7OLAZR-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\xBA\x01\x10\x12\x08\x0A\x06\x0A\x04\x12\x026X\x1A\x04\x0A\x02\x08\x01\xB2\x01~\x0A\x07contact\x12\x1C7OLAZR-2024-09-02-PNR-SSR-12@\x02bA\x0A\x0Bstakeholder\x12\x1A7OLAZR-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\xA2\x01\x02\x08\x01\xBA\x01\x0A\x12\x08\x0A\x06\x0A\x04\x12\x026X\xBA\x01\xD5\x01\x0A\x11automated-process\x12\x1A7OLAZR-2024-09-02-PNR-TK-3\x18\x05&quot;\x132024-09-02T00:00:00*\x0B\x0A\x09NCE6X0100ZA\x0A\x0Bstakeholder\x12\x1A7OLAZR-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelersb=\x0A\x07product\x12\x1B7OLAZR-2024-09-02-PNR-AIR-1\x1A\x15processedPnr.products\x1AX\x0A\x1Fapplication/vnd.google.protobuf\x12\x067OLAZR\x1A\x012&quot;\x03Pnr*\%com.amadeus.models.reservation.pnr.v2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[UNT\x1D2\x1D1\x1C&apos;&amp;
&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="21" responseEndLine="451" responseBeginLine="444" endLine="442" beginLine="437" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:01.299342 - 02 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_4"><VALUE><![CDATA[eyJub25jZSI6Ik1qWXdPREkxTURrM05ESXlNRFk0T1E9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjQ6NTAuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiI5TjRLS2lKL0V4dk1xaGo5WEZSdEg1RXZTQzQ9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="global_regression.openpnr_payload"><VALUE><![CDATA[ChE3T0xBWlItMjAyNC0wOS0wMhIDcG5yGgY3T0xBWlIiATI6VRoUMjAyNC0wOS0wMlQxMjoyNDowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKkgIaFDIwMjQtMDktMDJUMTI6MjQ6NTlaIg0KCwoJU1lENlgwMTAyKhFORENYIE9SREVSIENSRUFURTIDEgExOkUSEGhpc3RvcnlDaGFuZ2VMb2cYASIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMCoHY29udGFjdDIIY29udGFjdHM6RRIQaGlzdG9yeUNoYW5nZUxvZxgBIhw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTExKgdjb250YWN0Mghjb250YWN0czpFEhBoaXN0b3J5Q2hhbmdlTG9nGAEiHDdPTEFaUi0yMDI0LTA5LTAyLVBOUi1TU1ItMTIqB2NvbnRhY3QyCGNvbnRhY3RzesoCCgtzdGFrZWhvbGRlchIaN09MQVpSLTIwMjQtMDktMDItUE5SLU5NLTEiDBIERUlNQhoEQVJRRXI8Cgdjb250YWN0Eho3T0xBWlItMjAyNC0wOS0wMi1QTlItQVAtMhoVcHJvY2Vzc2VkUG5yLmNvbnRhY3Rzcj4KB2NvbnRhY3QSHDdPTEFaUi0yMDI0LTA5LTAyLVBOUi1TU1ItMTAaFXByb2Nlc3NlZFBuci5jb250YWN0c3I+Cgdjb250YWN0Ehw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTExGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPgoHY29udGFjdBIcN09MQVpSLTIwMjQtMDktMDItUE5SLVNTUi0xMhoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTA0RjNENDAwMDA0QTQ3ggHIAgoHcHJvZHVjdBABGhs3T0xBWlItMjAyNC0wOS0wMi1QTlItQUlSLTEinQIKGgoDTkNFGhMyMDI0LTEwLTI1VDA2OjAwOjAwEhoKA0xIUhoTMjAyNC0xMC0yNVQwNzoxMDowMCJPCgkKAjZYEgM1NjISJwoBWRIDCgFZGhQKAggAEgwKBBoCNlgSBCoCRlIgASIHRUNPTk9NWTIZNlgtNTYyLTIwMjQtMTAtMjUtTkNFLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzdPTEFaUi0yMDI0LTA5LTAyLVBOUi1CS0ctMRoQNjAwNTUzRDUwMDAxOEU4RVpBCgtzdGFrZWhvbGRlchIaN09MQVpSLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgECCACyAXoKB2NvbnRhY3QSGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1BUC0yQAFaDgoMKzMzNjAwMDAwNjY2YkEKC3N0YWtlaG9sZGVyEho3T0xBWlItMjAyNC0wOS0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7IBjQEKB2NvbnRhY3QSHDdPTEFaUi0yMDI0LTA5LTAyLVBOUi1TU1ItMTAiDBoKMDYxMjM0NTY3OEACYkEKC3N0YWtlaG9sZGVyEho3T0xBWlItMjAyNC0wOS0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBEBIICgYKBBICNlgaBAoCCAGyAZkBCgdjb250YWN0Ehw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTExMhgKFkJBUlQuU0lNUFNPTi8vTUFJTC5DT01AAmJBCgtzdGFrZWhvbGRlchIaN09MQVpSLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6ARASCAoGCgQSAjZYGgQKAggBsgF+Cgdjb250YWN0Ehw3T0xBWlItMjAyNC0wOS0wMi1QTlItU1NSLTEyQAJiQQoLc3Rha2Vob2xkZXISGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzogECCAG6AQoSCAoGCgQSAjZYugHVAQoRYXV0b21hdGVkLXByb2Nlc3MSGjdPTEFaUi0yMDI0LTA5LTAyLVBOUi1USy0zGAUiEzIwMjQtMDktMDJUMDA6MDA6MDAqCwoJTkNFNlgwMTAwWkEKC3N0YWtlaG9sZGVyEho3T0xBWlItMjAyNC0wOS0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2I9Cgdwcm9kdWN0Ehs3T0xBWlItMjAyNC0wOS0wMi1QTlItQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0cw==]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="14:25:01.461301 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001NVHEBJ6QHP]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[3856]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;7OLAZR-2024-09-02&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;7OLAZR&quot;, &amp;
    &quot;version&quot;: &quot;2&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:24:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:24:59Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;SYD6X0102&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;NDCX ORDER CREATE&quot;, &amp;
        &quot;correlationReference&quot;: \{&amp;
            &quot;correlationId&quot;: &quot;1&quot;&amp;
        \}, &amp;
        &quot;changeLog&quot;: [&amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-10&quot;, &amp;
                &quot;elementType&quot;: &quot;contact&quot;, &amp;
                &quot;path&quot;: &quot;contacts&quot;&amp;
            \}, &amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-11&quot;, &amp;
                &quot;elementType&quot;: &quot;contact&quot;, &amp;
                &quot;path&quot;: &quot;contacts&quot;&amp;
            \}, &amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-12&quot;, &amp;
                &quot;elementType&quot;: &quot;contact&quot;, &amp;
                &quot;path&quot;: &quot;contacts&quot;&amp;
            \}&amp;
        ]&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;EIMB&quot;, &amp;
                    &quot;lastName&quot;: &quot;ARQE&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-10&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-11&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-12&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;6104F3D400004A47&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-25T06:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-25T07:10:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;562&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-562-2024-10-25-NCE-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600553D500018E8E&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;+33600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-10&quot;, &amp;
            &quot;phone&quot;: \{&amp;
                &quot;number&quot;: &quot;0612345678&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;consentPermissions&quot;: [&amp;
                    \{&amp;
                        &quot;validity&quot;: \{&amp;
                            &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-11&quot;, &amp;
            &quot;email&quot;: \{&amp;
                &quot;address&quot;: &quot;BART.SIMPSON//MAIL.COM&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;consentPermissions&quot;: [&amp;
                    \{&amp;
                        &quot;validity&quot;: \{&amp;
                            &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-SSR-12&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;isDeclined&quot;: true, &amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-TK-3&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-09-02T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;7OLAZR-2024-09-02-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="22" endLine="462" beginLine="461" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:01.463006 - 02 Sep 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OLAZR]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:25:01.817943 - 02 Sep 2024" filename="">--- RLR ---&amp;
RP/NCE6X0100/NCE6X0100            AB/SU   2SEP24/1224Z   7OLAZR&amp;
  1.ARQE/EIMB&amp;
  2  6X 562 Y 25OCT 5 NCELHR HK1  0600 0710  25OCT  E  6X/7OLAZR&amp;
  3 AP +33600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
  5 SSR CTCM 6X HK1 0612345678&amp;
  6 SSR CTCE 6X HK1 BART.SIMPSON//MAIL.COM&amp;
  7 SSR CTCR 6X HK1&amp;
  8 OPC-24OCT:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * ES/G 02SEP/YGSU/NCE6X0100&amp;
    NCE6X0100-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="23" endLine="463" beginLine="462" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:01.818162 - 02 Sep 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="14:25:02.078824 - 02 Sep 2024" filename="">--- RLR ---&amp;
RP/NCE6X0100/NCE6X0100            AB/SU   2SEP24/1224Z   7OLAZR&amp;
  1.ARQE/EIMB&amp;
  2 AP +33600000666&amp;
  3 TK OK02SEP/NCE6X0100&amp;
  * ES/G 02SEP/YGSU/NCE6X0100&amp;
    NCE6X0100-B&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="24" endLine="464" beginLine="463" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:02.079298 - 02 Sep 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="14:25:02.467987 - 02 Sep 2024" filename="">END OF TRANSACTION COMPLETE - 7OLAZR&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="25" endLine="465" beginLine="464" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:02.468546 - 02 Sep 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="14:25:02.547996 - 02 Sep 2024" filename="">IGNORED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="26" endLine="470" beginLine="469" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:02.548533 - 02 Sep 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="14:25:02.680001 - 02 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="27" endLine="471" beginLine="470" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_CTCx/SSR_CTCx_Update_Feed.cry" loop="0" sentAt="14:25:02.680420 - 02 Sep 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="14:25:02.756305 - 02 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><STATISTIC><STATISTIC_ELEMENT name="Message in">28</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">36776</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">28</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">9077</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">28</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">27</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.964286</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">8645.7</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">2.926</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">5515.28</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">63</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="CPS" name="Conversations/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">3</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">0</STATISTIC_ELEMENT></STATISTIC></xml>