<xml scenarioFilename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry"><SCRIPT type="Initialize">import json
from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.
def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;id&apos;, &apos;reference&apos;, &apos;creation&apos;, &apos;loyaltyRequests&apos;, &apos;travelers&apos;, &apos;products&apos;, &apos;contacts&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=&quot;SYD6X0102&quot;, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;contacts&apos;]), expected=4, item_name=&apos;number of loyaltyRequests&apos;)
        contacts_1 = openpnr[&apos;loyaltyRequests&apos;][0]
        contacts_2 = openpnr[&apos;loyaltyRequests&apos;][1]
        contacts_3 = openpnr[&apos;loyaltyRequests&apos;][2]
        contacts_4 = openpnr[&apos;loyaltyRequests&apos;][3]

        #Check service data for SSR CTCX element
        assert_equal(actual=contacts_1[&apos;type&apos;], expected=&apos;service&apos;, item_name=&apos;loyaltyRequests type&apos;)
        assert_equal(actual=contacts_1[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-SSR-3&quot;, item_name=&apos;automatedProcesses id&apos;)
        assert_equal(actual=contacts_1[&apos;code&apos;], expected=&apos;CLID&apos;, item_name=&apos;loyaltyRequests code&apos;)
        assert_equal(actual=contacts_1[&apos;subType&apos;], expected=&apos;SPECIAL_SERVICE_REQUEST&apos;, item_name=&apos;loyaltyRequests subType&apos;)
        assert_equal(actual=contacts_1[&apos;serviceProvider&apos;][&apos;code&apos;], expected=&apos;AY&apos;, item_name=&apos;loyaltyRequests/serviceProvider code&apos;)
        assert_equal(actual=contacts_1[&apos;status&apos;], expected=&apos;HN&apos;, item_name=&apos;loyaltyRequests status&apos;)
        assert_equal(actual=contacts_1[&apos;membership&apos;][&apos;id&apos;], expected=&apos;TEST99BE&apos;, item_name=&apos;loyaltyRequests membership/id&apos;)
        assert_equal(actual=contacts_1[&apos;membership&apos;][&apos;membershipType&apos;], expected=&apos;CORPORATE&apos;, item_name=&apos;loyaltyRequests membershipType&apos;)
        assert_equal(actual=contacts_1[&apos;membership&apos;][&apos;activeTier&apos;][&apos;companyCode&apos;], expected=&apos;AY&apos;, item_name=&apos;loyaltyRequests membership/activeTier/companyCode&apos;)
        assert_equal(actual=contacts_1[&apos;membership&apos;][&apos;verificationStatus&apos;], expected=&apos;VERIFIED&apos;, item_name=&apos;loyaltyRequests membership/verificationStatus&apos;)

    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="88" beginLine="87" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:30.732144 - 30 Jul 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="14:43:30.787803 - 30 Jul 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" responseEndLine="94" responseBeginLine="93" endLine="89" beginLine="88" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:30.788322 - 30 Jul 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><COMPARISON compareAt="14:43:30.846071 - 30 Jul 2024" match="OK"><TEXT><![CDATA[SIGN IN&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="3" endLine="96" beginLine="95" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:30.846327 - 30 Jul 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="14:43:30.916893 - 30 Jul 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="103" beginLine="102" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:30.917064 - 30 Jul 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:43:30.975905 - 30 Jul 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="105" beginLine="104" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:32.981078 - 30 Jul 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0955]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:43:33.044486 - 30 Jul 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="109" responseBeginLine="109" endLine="107" beginLine="106" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:33.044900 - 30 Jul 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[****************]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="14:43:33.217855 - 30 Jul 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/30JUL/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" responseEndLine="134" responseBeginLine="125" endLine="123" beginLine="118" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:33.220360 - 30 Jul 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=json\&amp;output=protobufBase64 HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline"><VALUE><![CDATA[eyJub25jZSI6Ik56YzFPVE01TXpNME9EUXdPVEV6T1E9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDctMzBUMTI6NDM6MjYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiI1UWFhQ3YyaFRGMjhPY0RvOXdvNS9PaTZITzA9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT><VARIABLE name="input_json_SSR_CTCx"><VALUE><![CDATA[\{&amp;
    &quot;last_modification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-06-25T08:35:25Z&quot;&amp;
    \},&amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
            &quot;id&quot;: &quot;46BSDN-2024-06-25-PNR-NM-1&quot;,&amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;first_name&quot;: &quot;MORTY&quot;,&amp;
                    &quot;last_name&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;sub_type&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;46BSDN-2024-06-25-PNR-AIR-3&quot;,&amp;
            &quot;air_segment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iata_code&quot;: &quot;HEL&quot;,&amp;
                    &quot;local_date_time&quot;: &quot;2024-09-01T16:35:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iata_code&quot;: &quot;OUL&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flight_designator&quot;: \{&amp;
                        &quot;carrier_code&quot;: &quot;AY&quot;,&amp;
                        &quot;flight_number&quot;: &quot;435&quot;&amp;
                    \},&amp;
                    &quot;booking_class&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;,&amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;,&amp;
                            &quot;bidPrice&quot;: \{&amp;
                                &quot;amount&quot;: &quot;0&quot;,&amp;
                                &quot;elementaryPriceType&quot;: &quot;BID_PRICE&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                \},&amp;
                &quot;booking_status_code&quot;: &quot;NN&quot;&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;46BSDN-2024-06-25-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;,&amp;
            &quot;id&quot;: &quot;AP-1&quot;,&amp;
            &quot;phone&quot;: \{&amp;
                &quot;number&quot;: &quot;+33600000666&quot;&amp;
            \},&amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ]&amp;
        \},&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;,&amp;
            &quot;id&quot;: &quot;CTCE&quot;,&amp;
            &quot;email&quot;: \{&amp;
                &quot;address&quot;: &quot;BART.SIMPSON//MAIL.COM/FR&quot;&amp;
            \},&amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ],&amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;46BSDN-2024-06-25-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ],&amp;
                &quot;consentPermissions&quot;: [&amp;
                    \{&amp;
                        &quot;validity&quot;: \{&amp;
                            &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \},&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;,&amp;
            &quot;id&quot;: &quot;CTCM&quot;,&amp;
            &quot;phone&quot;: \{&amp;
                &quot;number&quot;: &quot;0123456789&quot;&amp;
            \},&amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ],&amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;46BSDN-2024-06-25-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ],&amp;
                &quot;consentPermissions&quot;: [&amp;
                    \{&amp;
                        &quot;validity&quot;: \{&amp;
                            &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \},&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;,&amp;
            &quot;id&quot;: &quot;CTCR&quot;,&amp;
            &quot;isDeclined&quot;: &quot;True&quot;,&amp;
            &quot;purpose&quot;: [&amp;
                &quot;NOTIFICATION&quot;&amp;
            ],&amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;46BSDN-2024-06-25-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;security&quot;: \{&amp;
                &quot;allowedParties&quot;: [&amp;
                    \{&amp;
                        &quot;party&quot;: \{&amp;
                            &quot;company&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}&amp;
                        \}&amp;
                    \}&amp;
                ],&amp;
                &quot;consentPermissions&quot;: [&amp;
                    \{&amp;
                        &quot;validity&quot;: \{&amp;
                            &quot;validityStatus&quot;: &quot;GRANTED&quot;&amp;
                        \}&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        \}&amp;
    ],&amp;
    &quot;automated_processes&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;,&amp;
            &quot;code&quot;: &quot;OK&quot;&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="14:43:33.394147 - 30 Jul 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001ZFSP6HFSOL]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[954]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[ShYaFDIwMjQtMDYtMjVUMDg6MzU6MjVaejkKC3N0YWtlaG9sZGVyEho0NkJTRE4tMjAyNC0wNi0yNS1QTlItTk0tMSIOEgVNT1JUWRoFU01JVEiCAbsBCgdwcm9kdWN0EAEaGzQ2QlNETi0yMDI0LTA2LTI1LVBOUi1BSVItMyJOChoKA0hFTBoTMjAyNC0wOS0wMVQxNjozNTowMBIFCgNPVUwiJQoJCgJBWRIDNDM1EhgKAVkSEwoBWRIOCgEwIglCSURfUFJJQ0VKAk5OQkEKC3N0YWtlaG9sZGVyEho0NkJTRE4tMjAyNC0wNi0yNS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7IBIgoHY29udGFjdBIEQVAtMSIOGgwrMzM2MDAwMDA2NjZCAQGyAYUBCgdjb250YWN0EgRDVENFMhsKGUJBUlQuU0lNUFNPTi8vTUFJTC5DT00vRlJCAQJiQQoLc3Rha2Vob2xkZXISGjQ2QlNETi0yMDI0LTA2LTI1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugEQEggKBgoEEgI2WBoECgIIAbIBdgoHY29udGFjdBIEQ1RDTSIMGgowMTIzNDU2Nzg5QgECYkEKC3N0YWtlaG9sZGVyEho0NkJTRE4tMjAyNC0wNi0yNS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBEBIICgYKBBICNlgaBAoCCAGyAW0KB2NvbnRhY3QSBENUQ1JCAQJiQQoLc3Rha2Vob2xkZXISGjQ2QlNETi0yMDI0LTA2LTI1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzogECCAG6ARASCAoGCgQSAjZYGgQKAggBugEVChFhdXRvbWF0ZWQtcHJvY2VzcxgF]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="8" responseEndLine="163" responseBeginLine="152" endLine="150" beginLine="143" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:33.395133 - 30 Jul 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/ HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_2"><VALUE><![CDATA[eyJub25jZSI6Ik16Y3dOelExTVRBek16VTJNakExTlE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDctMzBUMTI6NDM6MjYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJSUHk3SDY3TERLMFFoREl0MDRXK3NIK1lMeTg9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ShYaFDIwMjQtMDYtMjVUMDg6MzU6MjVaejkKC3N0YWtlaG9sZGVyEho0NkJTRE4tMjAyNC0wNi0yNS1QTlItTk0tMSIOEgVNT1JUWRoFU01JVEiCAbsBCgdwcm9kdWN0EAEaGzQ2QlNETi0yMDI0LTA2LTI1LVBOUi1BSVItMyJOChoKA0hFTBoTMjAyNC0wOS0wMVQxNjozNTowMBIFCgNPVUwiJQoJCgJBWRIDNDM1EhgKAVkSEwoBWRIOCgEwIglCSURfUFJJQ0VKAk5OQkEKC3N0YWtlaG9sZGVyEho0NkJTRE4tMjAyNC0wNi0yNS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7IBIgoHY29udGFjdBIEQVAtMSIOGgwrMzM2MDAwMDA2NjZCAQGyAYUBCgdjb250YWN0EgRDVENFMhsKGUJBUlQuU0lNUFNPTi8vTUFJTC5DT00vRlJCAQJiQQoLc3Rha2Vob2xkZXISGjQ2QlNETi0yMDI0LTA2LTI1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugEQEggKBgoEEgI2WBoECgIIAbIBdgoHY29udGFjdBIEQ1RDTSIMGgowMTIzNDU2Nzg5QgECYkEKC3N0YWtlaG9sZGVyEho0NkJTRE4tMjAyNC0wNi0yNS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBEBIICgYKBBICNlgaBAoCCAGyAW0KB2NvbnRhY3QSBENUQ1JCAQJiQQoLc3Rha2Vob2xkZXISGjQ2QlNETi0yMDI0LTA2LTI1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzogECCAG6ARASCAoGCgQSAjZYGgQKAggBugEVChFhdXRvbWF0ZWQtcHJvY2VzcxgF]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></QUERY><COMPARISON compareAt="14:43:34.323101 - 30 Jul 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 201 Created&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001ZFSPCHFSOL]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1441]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[87Z9UW]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf2%=.*}]]></EXPRESSION><VALUE><![CDATA[ChE4N1o5VVctMjAyNC0wNy0zMBIDcG5yGgY4N1o5VVciATA6VRoUMjAyNC0wNy0zMFQxMjo0MzowMFoiPQoiCglTWUQ2WDAxMDISCDAwMzYwMTI0GgI2WCIHQUlSTElORRIXCgQwMDAxEgJBQhoCU1UqAkFVMgNTWURKFhoUMjAyNC0wNy0zMFQxMjo0MzozM1p6jAEKC3N0YWtlaG9sZGVyEho4N1o5VVctMjAyNC0wNy0zMC1QTlItTk0tMSIOEgVNT1JUWRoFU01JVEhyPAoHY29udGFjdBIaODdaOVVXLTIwMjQtMDctMzAtUE5SLUFQLTIaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwRDAzQjIwMDAxM0IwQ4IBlgMKB3Byb2R1Y3QQARobODdaOVVXLTIwMjQtMDctMzAtUE5SLUFJUi0xIusCChoKA0hFTBoTMjAyNC0wOS0wMVQwNzowMDowMBIaCgNPVUwaEzIwMjQtMDktMDFUMDg6MjA6MDAingEKCQoCQVkSAzQzNRJ2CgFZEhMKAVkSDgoBNCIJQklEX1BSSUNFGlMKABIMCgQaAjZYEgQqAkFVGhUKAzI3MSIOQURKVVNURURfWUlFTEQaFgoDMjY3Ig9FRkZFQ1RJVkVfWUlFTEQaEAoDMjcxIglPTkRfWUlFTEQgASIHRUNPTk9NWTIZQVktNDM1LTIwMjQtMDktMDEtSEVMLU9VTEoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzg3WjlVVy0yMDI0LTA3LTMwLVBOUi1CS0ctMRoQNjAwRDYzQjIwMDAzQjQ4MFpBCgtzdGFrZWhvbGRlchIaODdaOVVXLTIwMjQtMDctMzAtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAsgF7Cgdjb250YWN0Eho4N1o5VVctMjAyNC0wNy0zMC1QTlItQVAtMkIBAVoOCgwrMzM2MDAwMDA2NjZiQQoLc3Rha2Vob2xkZXISGjg3WjlVVy0yMDI0LTA3LTMwLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugHVAQoRYXV0b21hdGVkLXByb2Nlc3MSGjg3WjlVVy0yMDI0LTA3LTMwLVBOUi1USy02GAUiEzIwMjQtMDctMzBUMDA6MDA6MDAqCwoJU1lENlgwMTAyWkEKC3N0YWtlaG9sZGVyEho4N1o5VVctMjAyNC0wNy0zMC1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2I9Cgdwcm9kdWN0Ehs4N1o5VVctMjAyNC0wNy0zMC1QTlItQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0cw==]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="9" responseEndLine="188" responseBeginLine="181" endLine="179" beginLine="173" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:34.324721 - 30 Jul 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Debug-Format: debug&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_3"><VALUE><![CDATA[eyJub25jZSI6Ik1UQTRPREl6TXpNMk5UY3dNek0wTlE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDctMzBUMTI6NDM6MjYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJscTJ2OVJ4NGI1ZXhhTXFPekZQTC9zemtvUzg9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf2"><VALUE><![CDATA[ChE4N1o5VVctMjAyNC0wNy0zMBIDcG5yGgY4N1o5VVciATA6VRoUMjAyNC0wNy0zMFQxMjo0MzowMFoiPQoiCglTWUQ2WDAxMDISCDAwMzYwMTI0GgI2WCIHQUlSTElORRIXCgQwMDAxEgJBQhoCU1UqAkFVMgNTWURKFhoUMjAyNC0wNy0zMFQxMjo0MzozM1p6jAEKC3N0YWtlaG9sZGVyEho4N1o5VVctMjAyNC0wNy0zMC1QTlItTk0tMSIOEgVNT1JUWRoFU01JVEhyPAoHY29udGFjdBIaODdaOVVXLTIwMjQtMDctMzAtUE5SLUFQLTIaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwRDAzQjIwMDAxM0IwQ4IBlgMKB3Byb2R1Y3QQARobODdaOVVXLTIwMjQtMDctMzAtUE5SLUFJUi0xIusCChoKA0hFTBoTMjAyNC0wOS0wMVQwNzowMDowMBIaCgNPVUwaEzIwMjQtMDktMDFUMDg6MjA6MDAingEKCQoCQVkSAzQzNRJ2CgFZEhMKAVkSDgoBNCIJQklEX1BSSUNFGlMKABIMCgQaAjZYEgQqAkFVGhUKAzI3MSIOQURKVVNURURfWUlFTEQaFgoDMjY3Ig9FRkZFQ1RJVkVfWUlFTEQaEAoDMjcxIglPTkRfWUlFTEQgASIHRUNPTk9NWTIZQVktNDM1LTIwMjQtMDktMDEtSEVMLU9VTEoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzg3WjlVVy0yMDI0LTA3LTMwLVBOUi1CS0ctMRoQNjAwRDYzQjIwMDAzQjQ4MFpBCgtzdGFrZWhvbGRlchIaODdaOVVXLTIwMjQtMDctMzAtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAsgF7Cgdjb250YWN0Eho4N1o5VVctMjAyNC0wNy0zMC1QTlItQVAtMkIBAVoOCgwrMzM2MDAwMDA2NjZiQQoLc3Rha2Vob2xkZXISGjg3WjlVVy0yMDI0LTA3LTMwLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugHVAQoRYXV0b21hdGVkLXByb2Nlc3MSGjg3WjlVVy0yMDI0LTA3LTMwLVBOUi1USy02GAUiEzIwMjQtMDctMzBUMDA6MDA6MDAqCwoJU1lENlgwMTAyWkEKC3N0YWtlaG9sZGVyEho4N1o5VVctMjAyNC0wNy0zMC1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2I9Cgdwcm9kdWN0Ehs4N1o5VVctMjAyNC0wNy0zMC1QTlItQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0cw==]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON KO="KO" validate="manual" matchMessage="Match failed with error code 1: Callback rejected:Match function exits on unspecified Error." compareAt="14:43:34.477429 - 30 Jul 2024"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001ZFSPLHFSOM]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2313]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;87Z9UW-2024-07-30&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;87Z9UW&quot;, &amp;
    &quot;version&quot;: &quot;0&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-07-30T12:43:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;SYD6X0102&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00360124&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;0001&quot;, &amp;
                &quot;initials&quot;: &quot;AB&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;AU&quot;, &amp;
                &quot;cityCode&quot;: &quot;SYD&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-07-30T12:43:33Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;MORTY&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610D03B200013B0C&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;HEL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-09-01T07:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;OUL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-09-01T08:20:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;AY&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;435&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;, &amp;
                            &quot;bidPrice&quot;: \{&amp;
                                &quot;amount&quot;: &quot;4&quot;, &amp;
                                &quot;elementaryPriceType&quot;: &quot;BID_PRICE&quot;&amp;
                            \}&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;AU&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;yields&quot;: [&amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;271&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;ADJUSTED_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;267&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;EFFECTIVE_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;271&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;OND_YIELD&quot;&amp;
                                \}&amp;
                            ], &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;AY-435-2024-09-01-HEL-OUL&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600D63B20003B480&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;+33600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-TK-6&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-07-30T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;SYD6X0102&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="10" responseEndLine="202" responseBeginLine="199" endLine="197" beginLine="196" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:34.478250 - 30 Jul 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[87Z9UW]]></VALUE></VARIABLE></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 76: The pattern match failed." compareAt="14:43:34.678360 - 30 Jul 2024"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/SYD6X0102/SYD6X0102 ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[           AB]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[ 30JUL24/1243]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[87Z9UW]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[{(local).*?SSR CLID} AY HN/ AYTEST99BE&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[  1.SMITH/MORTY&amp;
]]></TEXT></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  2  AY 435 Y 01SEP 7 HELOUL HK1  0700 0820  01SEP  E  AY/87Z9UW&amp;
  3 AP +33600000666&amp;
  4 TK OK30JUL/SYD6X0102&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="11" responseEndLine="222" responseBeginLine="220" endLine="218" beginLine="214" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:34.737429 - 30 Jul 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[87Z9UW]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:43:34.986330 - 30 Jul 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:87Z9UW::300724:1243&apos;&amp;
RSI+RP:ABSU:SYD6X0102:00360124+SYD6X0102+NCE+SYD6X0102:0001AB:300724:00360124:1243&apos;&amp;
LFT+3:P12+--- RLR ---&apos;&amp;
STX+RLR&apos;&amp;
UID+00360124:SYD6X0102+A&apos;&amp;
SYS++6X:SYD&apos;&amp;
PRE+AU&apos;&amp;
UID+00360124:SYD6X0102+A&apos;&amp;
SYS++6X:SYD&apos;&amp;
PRE+AU&apos;&amp;
UID+00360124:SYD6X0102+A&apos;&amp;
SYS++6X:SYD&apos;&amp;
PRE+AU&apos;&amp;
SEQ++1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[0]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2024:9:5&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+SMITH::1+MORTY&apos;&amp;
ETI+:1+UN:Y:Y::SMITH:MORTY&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+010924:0700:010924:0820+HEL+OUL+AY+435:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+AY:87Z9UW&apos;&amp;
RPI+1+HK&apos;&amp;
APD+AT7:0:0120::7+++320:M+::0615+M:N&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
IFT+3+     OPERATED BY NORDIC REGIONAL AIRLINES OY&apos;&amp;
FSD&apos;&amp;
TVL+010924:0700:010924:0820+HEL+OUL&apos;&amp;
IFT+ACO+AIRCRAFT OWNER NORDIC REGIONAL AIRLINES&apos;&amp;
IFT+OPC+OPERATED BY /NORDIC REG FOR FINNAIR&apos;&amp;
DUM&apos;&amp;
REF+PT:1&apos;&amp;
DUM&apos;&amp;
EMS++OT:2+AP+3&apos;&amp;
LFT+3:5+\+33600000666&apos;&amp;
EMS++OT:6+TK+4&apos;&amp;
TKE++OK:300724::SYD6X0102]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="11"><QUERY filename="" loop="0" sentAt="14:43:34.987152 - 30 Jul 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="12" responseEndLine="255" responseBeginLine="242" endLine="240" beginLine="234" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:35.104209 - 30 Jul 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE6X0100++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[87Z9UW]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[30JUL24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[0]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:43:36.608518 - 30 Jul 2024" match="OK"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[87Z9UW]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[30JUL24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[0]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[87Z9UW]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[20240730\:12\:43\:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%backend%=*}]]></EXPRESSION><VALUE><![CDATA[SONPK4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[0]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:07:30:12:43:34]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%message_id%=*}]]></EXPRESSION><VALUE><![CDATA[4573082089]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%sdi_date2%=*}]]></EXPRESSION><VALUE><![CDATA[2024:07:30:12:43:34]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="13" responseEndLine="275" responseBeginLine="269" endLine="268" beginLine="264" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:36.659459 - 30 Jul 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[4573082089]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[SONPK4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[2024:07:30:12:43:34]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:43:37.024658 - 30 Jul 2024" match="OK"><TEXT><![CDATA[UNH++PUPIRR:14:1:1A+&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[4573082089]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+SONPK4&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:07:30:12:43:34]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
BLB+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1608]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%raw_binary%=(multi).*}]]></EXPRESSION><VALUE><![CDATA[\x0A\xA8\x0C\x12\xCB\x0B\x0A\x1187Z9UW-2024-07-30\x12\x03pnr\x1A\x0687Z9UW&quot;\x010:U\x1A\x142024-07-30T12:43:00Z&quot;=\x0A&quot;\x0A\x09SYD6X0102\x12\x0800360124\x1A\x026X&quot;\x07AIRLINE\x12\x17\x0A\x040001\x12\x02AB\x1A\x02SU*\x02AU2\x03SYDJ\xCB\x03\x1A\x142024-07-30T12:43:33Z&quot;\x0D\x0A\x0B\x0A\x09SYD6X0102*\x11NDCX ORDER CREATE:H\x12\x10historyChangeLog\x18\x01&quot;\x1A87Z9UW-2024-07-30-PNR-NM-1*\x0Bstakeholder2\x09travelers:D\x12\x10historyChangeLog\x18\x01&quot;\x1B87Z9UW-2024-07-30-PNR-AIR-1*\x07product2\x08products:c\x12\x10historyChangeLog\x18\x01&quot;\x1B87Z9UW-2024-07-30-PNR-BKG-1*\x10segment-delivery2\x1Eproducts/airSegment/deliveries:C\x12\x10historyChangeLog\x18\x01&quot;\x1A87Z9UW-2024-07-30-PNR-AP-2*\x07contact2\x08contacts:W\x12\x10historyChangeLog\x18\x01&quot;\x1A87Z9UW-2024-07-30-PNR-TK-6*\x11automated-process2\x12automatedProcessesz\x8C\x01\x0A\x0Bstakeholder\x12\x1A87Z9UW-2024-07-30-PNR-NM-1&quot;\x0E\x12\x05MORTY\x1A\x05SMITHr&lt;\x0A\x07contact\x12\x1A87Z9UW-2024-07-30-PNR-AP-2\x1A\x15processedPnr.contacts\xA2\x01\x12\x12\x10610D03B200013B0C\x82\x01\x9A\x03\x0A\x07product\x10\x01\x1A\x1B87Z9UW-2024-07-30-PNR-AIR-1&quot;\xEF\x02\x0A\x1A\x0A\x03HEL\x1A\x132024-09-01T07:00:00\x12\x1A\x0A\x03OUL\x1A\x132024-09-01T08:20:00&quot;\xA0\x01\x0A\x09\x0A\x02AY\x12\x03435\x12x\x0A\x01Y\x12\x13\x0A\x01Y\x12\x0E\x0A\x014&quot;\x09BID_PRICE\x1AU\x0A\x02\x08\x00\x12\x0C\x0A\x04\x1A\x026X\x12\x04*\x02AU\x1A\x15\x0A\x03271&quot;\x0EADJUSTED_YIELD\x1A\x16\x0A\x03267&quot;\x0FEFFECTIVE_YIELD\x1A\x10\x0A\x03271&quot;\x09OND_YIELD \x01&quot;\x07ECONOMY2\x19AY-435-2024-09-01-HEL-OULJ\x02HKb\x84\x01\x0A\x10segment-delivery\x12\x1B87Z9UW-2024-07-30-PNR-BKG-1\x1A\x10600D63B20003B480ZA\x0A\x0Bstakeholder\x12\x1A87Z9UW-2024-07-30-PNR-NM-1\x1A\x16processedPnr.travelers\x8A\x01\x01E\x92\x01\x02\x08\x00\xB2\x01z\x0A\x07contact\x12\x1A87Z9UW-2024-07-30-PNR-AP-2@\x01Z\x0E\x0A\x0C+33600000666bA\x0A\x0Bstakeholder\x12\x1A87Z9UW-2024-07-30-PNR-NM-1\x1A\x16processedPnr.travelers\xBA\x01\xD5\x01\x0A\x11automated-process\x12\x1A87Z9UW-2024-07-30-PNR-TK-6\x18\x05&quot;\x132024-07-30T00:00:00*\x0B\x0A\x09SYD6X0102ZA\x0A\x0Bstakeholder\x12\x1A87Z9UW-2024-07-30-PNR-NM-1\x1A\x16processedPnr.travelersb=\x0A\x07product\x12\x1B87Z9UW-2024-07-30-PNR-AIR-1\x1A\x15processedPnr.products\x1AX\x0A\x1Fapplication/vnd.google.protobuf\x12\x0687Z9UW\x1A\x010&quot;\x03Pnr*\%com.amadeus.models.reservation.pnr.v2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[UNT\x1D2\x1D1\x1C&apos;&amp;
&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14" responseEndLine="303" responseBeginLine="296" endLine="294" beginLine="289" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:37.027417 - 30 Jul 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_4"><VALUE><![CDATA[eyJub25jZSI6Ik9EZzFOelU1T0Rnek5UWTFOekE0TWc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDctMzBUMTI6NDM6MjYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJ3U1krcGxJelFTZXpnK1ZsUmIzQ0lJSXNIbms9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="global_regression.openpnr_payload"><VALUE><![CDATA[ChE4N1o5VVctMjAyNC0wNy0zMBIDcG5yGgY4N1o5VVciATA6VRoUMjAyNC0wNy0zMFQxMjo0MzowMFoiPQoiCglTWUQ2WDAxMDISCDAwMzYwMTI0GgI2WCIHQUlSTElORRIXCgQwMDAxEgJBQhoCU1UqAkFVMgNTWURKywMaFDIwMjQtMDctMzBUMTI6NDM6MzNaIg0KCwoJU1lENlgwMTAyKhFORENYIE9SREVSIENSRUFURTpIEhBoaXN0b3J5Q2hhbmdlTG9nGAEiGjg3WjlVVy0yMDI0LTA3LTMwLVBOUi1OTS0xKgtzdGFrZWhvbGRlcjIJdHJhdmVsZXJzOkQSEGhpc3RvcnlDaGFuZ2VMb2cYASIbODdaOVVXLTIwMjQtMDctMzAtUE5SLUFJUi0xKgdwcm9kdWN0Mghwcm9kdWN0czpjEhBoaXN0b3J5Q2hhbmdlTG9nGAEiGzg3WjlVVy0yMDI0LTA3LTMwLVBOUi1CS0ctMSoQc2VnbWVudC1kZWxpdmVyeTIecHJvZHVjdHMvYWlyU2VnbWVudC9kZWxpdmVyaWVzOkMSEGhpc3RvcnlDaGFuZ2VMb2cYASIaODdaOVVXLTIwMjQtMDctMzAtUE5SLUFQLTIqB2NvbnRhY3QyCGNvbnRhY3RzOlcSEGhpc3RvcnlDaGFuZ2VMb2cYASIaODdaOVVXLTIwMjQtMDctMzAtUE5SLVRLLTYqEWF1dG9tYXRlZC1wcm9jZXNzMhJhdXRvbWF0ZWRQcm9jZXNzZXN6jAEKC3N0YWtlaG9sZGVyEho4N1o5VVctMjAyNC0wNy0zMC1QTlItTk0tMSIOEgVNT1JUWRoFU01JVEhyPAoHY29udGFjdBIaODdaOVVXLTIwMjQtMDctMzAtUE5SLUFQLTIaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwRDAzQjIwMDAxM0IwQ4IBmgMKB3Byb2R1Y3QQARobODdaOVVXLTIwMjQtMDctMzAtUE5SLUFJUi0xIu8CChoKA0hFTBoTMjAyNC0wOS0wMVQwNzowMDowMBIaCgNPVUwaEzIwMjQtMDktMDFUMDg6MjA6MDAioAEKCQoCQVkSAzQzNRJ4CgFZEhMKAVkSDgoBNCIJQklEX1BSSUNFGlUKAggAEgwKBBoCNlgSBCoCQVUaFQoDMjcxIg5BREpVU1RFRF9ZSUVMRBoWCgMyNjciD0VGRkVDVElWRV9ZSUVMRBoQCgMyNzEiCU9ORF9ZSUVMRCABIgdFQ09OT01ZMhlBWS00MzUtMjAyNC0wOS0wMS1IRUwtT1VMSgJIS2KEAQoQc2VnbWVudC1kZWxpdmVyeRIbODdaOVVXLTIwMjQtMDctMzAtUE5SLUJLRy0xGhA2MDBENjNCMjAwMDNCNDgwWkEKC3N0YWtlaG9sZGVyEho4N1o5VVctMjAyNC0wNy0zMC1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQIIALIBegoHY29udGFjdBIaODdaOVVXLTIwMjQtMDctMzAtUE5SLUFQLTJAAVoOCgwrMzM2MDAwMDA2NjZiQQoLc3Rha2Vob2xkZXISGjg3WjlVVy0yMDI0LTA3LTMwLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugHVAQoRYXV0b21hdGVkLXByb2Nlc3MSGjg3WjlVVy0yMDI0LTA3LTMwLVBOUi1USy02GAUiEzIwMjQtMDctMzBUMDA6MDA6MDAqCwoJU1lENlgwMTAyWkEKC3N0YWtlaG9sZGVyEho4N1o5VVctMjAyNC0wNy0zMC1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2I9Cgdwcm9kdWN0Ehs4N1o5VVctMjAyNC0wNy0zMC1QTlItQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0cw==]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON KO="KO" validate="manual" matchMessage="Match failed with error code 1: Callback rejected:Match function exits on unspecified Error." compareAt="14:43:37.184115 - 30 Jul 2024"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001ZFSPYHFSOP]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[3119]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;87Z9UW-2024-07-30&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;87Z9UW&quot;, &amp;
    &quot;version&quot;: &quot;0&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-07-30T12:43:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;SYD6X0102&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00360124&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;0001&quot;, &amp;
                &quot;initials&quot;: &quot;AB&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;AU&quot;, &amp;
                &quot;cityCode&quot;: &quot;SYD&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-07-30T12:43:33Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;SYD6X0102&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;NDCX ORDER CREATE&quot;, &amp;
        &quot;changeLog&quot;: [&amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
                &quot;elementType&quot;: &quot;stakeholder&quot;, &amp;
                &quot;path&quot;: &quot;travelers&quot;&amp;
            \}, &amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;87Z9UW-2024-07-30-PNR-AIR-1&quot;, &amp;
                &quot;elementType&quot;: &quot;product&quot;, &amp;
                &quot;path&quot;: &quot;products&quot;&amp;
            \}, &amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;87Z9UW-2024-07-30-PNR-BKG-1&quot;, &amp;
                &quot;elementType&quot;: &quot;segment-delivery&quot;, &amp;
                &quot;path&quot;: &quot;products/airSegment/deliveries&quot;&amp;
            \}, &amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;87Z9UW-2024-07-30-PNR-AP-2&quot;, &amp;
                &quot;elementType&quot;: &quot;contact&quot;, &amp;
                &quot;path&quot;: &quot;contacts&quot;&amp;
            \}, &amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;87Z9UW-2024-07-30-PNR-TK-6&quot;, &amp;
                &quot;elementType&quot;: &quot;automated-process&quot;, &amp;
                &quot;path&quot;: &quot;automatedProcesses&quot;&amp;
            \}&amp;
        ]&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;MORTY&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610D03B200013B0C&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;HEL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-09-01T07:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;OUL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-09-01T08:20:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;AY&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;435&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;, &amp;
                            &quot;bidPrice&quot;: \{&amp;
                                &quot;amount&quot;: &quot;4&quot;, &amp;
                                &quot;elementaryPriceType&quot;: &quot;BID_PRICE&quot;&amp;
                            \}&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;AU&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;yields&quot;: [&amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;271&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;ADJUSTED_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;267&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;EFFECTIVE_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;271&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;OND_YIELD&quot;&amp;
                                \}&amp;
                            ], &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;AY-435-2024-09-01-HEL-OUL&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600D63B20003B480&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;+33600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-TK-6&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-07-30T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;SYD6X0102&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;87Z9UW-2024-07-30-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="15" endLine="314" beginLine="313" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:37.185881 - 30 Jul 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[87Z9UW]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:43:37.593465 - 30 Jul 2024" filename="">--- RLR ---&amp;
RP/SYD6X0102/SYD6X0102            AA/SU  30JUL24/1243Z   87Z9UW&amp;
  1.SMITH/MORTY&amp;
  2  AY 435 Y 01SEP 7 HELOUL HK1  0700 0820  01SEP  E  AY/87Z9UW&amp;
  3 AP +33600000666&amp;
  4 TK OK30JUL/SYD6X0102&amp;
  5 OPW-29AUG:1300/1C7/AY REQUIRES TICKET ON OR BEFORE&amp;
        01SEP:1300 SYD TIME ZONE/TKT/S2&amp;
  6 OPC-01SEP:1300/1C8/AY CANCELLATION DUE TO NO TICKET SYD TIME&amp;
        ZONE/TKT/S2&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="16" endLine="315" beginLine="314" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:37.594001 - 30 Jul 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="14:43:37.854266 - 30 Jul 2024" filename="">--- RLR ---&amp;
RP/SYD6X0102/SYD6X0102            AA/SU  30JUL24/1243Z   87Z9UW&amp;
  1.SMITH/MORTY&amp;
  2 AP +33600000666&amp;
  3 TK OK30JUL/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="17" endLine="316" beginLine="315" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:37.854529 - 30 Jul 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="14:43:38.205879 - 30 Jul 2024" filename="">END OF TRANSACTION COMPLETE - 87Z9UW&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="18" endLine="317" beginLine="316" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.206051 - 30 Jul 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="14:43:38.279188 - 30 Jul 2024" filename="">IGNORED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="19" endLine="322" beginLine="321" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.279357 - 30 Jul 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="14:43:38.410958 - 30 Jul 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="20" endLine="323" beginLine="322" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.411104 - 30 Jul 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="14:43:38.499518 - 30 Jul 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="21" endLine="331" beginLine="330" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><COMMENT> 6. Cancel the PNR and sign out</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.499724 - 30 Jul 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="14:43:38.555517 - 30 Jul 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="22" endLine="332" beginLine="331" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.555622 - 30 Jul 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="14:43:38.609651 - 30 Jul 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="23" endLine="333" beginLine="332" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.609753 - 30 Jul 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="14:43:38.664065 - 30 Jul 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="24" endLine="338" beginLine="337" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.664175 - 30 Jul 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="14:43:38.721832 - 30 Jul 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="25" endLine="339" beginLine="338" filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/ORDER_10052_Support_SB_Out/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/SSR_CTCx/SSR_CTCR_Create_Feed.cry" loop="0" sentAt="14:43:38.722001 - 30 Jul 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="14:43:38.798644 - 30 Jul 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><STATISTIC><STATISTIC_ELEMENT name="Message in">26</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">21766</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">26</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">11743</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">26</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">25</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.961538</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">8075.3</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">1.476</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">5826.89</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">72</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="CPS" name="Conversations/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">3</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">3</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">3</STATISTIC_ELEMENT></STATISTIC></xml>