<xml scenarioFilename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry"><SCRIPT type="Initialize">import json
import re
import generic_lib

from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json
from generic_lib import flatten

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.

def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;id&apos;, &apos;reference&apos;, &apos;creation&apos;, &apos;travelers&apos;, &apos;products&apos;, &apos;contacts&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=&quot;NCE6X0100&quot;, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;contacts&apos;]), expected=2, item_name=&apos;number of contacts&apos;)
        contacts_1 = openpnr[&apos;contacts&apos;][0]
        contacts_2 = openpnr[&apos;contacts&apos;][1]

        #Check service data for SSR DOCA element
        assert_equal(actual=contacts_1[&apos;type&apos;], expected=&apos;contact&apos;, item_name=&apos;contact type&apos;)
        assert_equal(actual=contacts_1[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AP-2&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_1[&apos;purpose&apos;], expected= [u&apos;STANDARD&apos;], item_name=&apos;contact purpose&apos;)
        assert_equal(actual=contacts_1[&apos;freeFlowFormat&apos;], expected=&apos;0600000666&apos;, item_name=&apos;contact freeFlowFormat&apos;)

        assert_equal(actual=contacts_2[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-SSR-10&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;category&apos;], expected=&quot;DESTINATION&quot;, item_name=&apos;contact address/category&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;lines&apos;][0], expected= &quot;301 PARK AVENUE&quot;, item_name=&apos;contact address/lines&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;postalCode&apos;], expected= &quot;10022&quot;, item_name=&apos;contact address/postalCode&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;countryCode&apos;], expected= &quot;USA&quot;, item_name=&apos;contact address/countryCode&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;cityName&apos;], expected= &quot;NEW YORK&quot;, item_name=&apos;contact address/cityName&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;stateCode&apos;], expected= &quot;NY&quot;, item_name=&apos;contact address/stateCode&apos;)
        assert_equal(actual=contacts_2[&apos;purpose&apos;], expected= [u&apos;REGULATORY&apos;], item_name=&apos;contact purpose&apos;)

    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="94" beginLine="93" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:19.725766 - 02 Sep 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="14:25:19.776611 - 02 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" endLine="95" beginLine="94" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:19.777177 - 02 Sep 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="14:25:19.839841 - 02 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="3" endLine="96" beginLine="95" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:19.840654 - 02 Sep 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="14:25:19.912410 - 02 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="103" beginLine="102" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:19.912793 - 02 Sep 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:25:19.972835 - 02 Sep 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="105" beginLine="104" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:21.982512 - 02 Sep 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0955]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:25:22.040535 - 02 Sep 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="109" responseBeginLine="109" endLine="107" beginLine="106" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:22.042116 - 02 Sep 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[***************]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="14:25:22.210494 - 02 Sep 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/02SEP/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" endLine="116" beginLine="115" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><COMMENT> 2. Create simple PNR with mandatory elements</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:22.211106 - 02 Sep 2024"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Pax1.book()}]]></EXPRESSION><VALUE><![CDATA[NM1ANZT/TWGS]]></VALUE></REGULAR_EXPRESSION></QUERY><REPLY receiveAt="14:25:22.317531 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
  1.ANZT/TWGS&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="8" endLine="117" beginLine="116" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:22.318674 - 02 Sep 2024"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_AY_daily.book(1)}]]></EXPRESSION><VALUE><![CDATA[SSAY435Y03OCTHELOUL1]]></VALUE></REGULAR_EXPRESSION></QUERY><REPLY receiveAt="14:25:22.745124 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
  1.ANZT/TWGS&amp;
  2  AY 435 Y 03OCT 4 HELOUL DK1  0700 0820  03OCT  E  0 AT7 N&amp;
     OPERATED BY NORDIC REG FOR FINNAIR&amp;
     OPERATED BY NORDIC REGIONAL AIRLINES OY&amp;
     SEE RTSVC&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="9" endLine="118" beginLine="117" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:22.745522 - 02 Sep 2024"><TEXT><![CDATA[AP0600000666]]></TEXT></QUERY><REPLY receiveAt="14:25:22.867172 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
  1.ANZT/TWGS&amp;
  2  AY 435 Y 03OCT 4 HELOUL DK1  0700 0820  03OCT  E  0 AT7 N&amp;
     OPERATED BY NORDIC REG FOR FINNAIR&amp;
     OPERATED BY NORDIC REGIONAL AIRLINES OY&amp;
     SEE RTSVC&amp;
  3 AP 0600000666&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="10" endLine="119" beginLine="118" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:22.867669 - 02 Sep 2024"><TEXT><![CDATA[TKOK;RFTEST]]></TEXT></QUERY><REPLY receiveAt="14:25:23.025862 - 02 Sep 2024" filename="">RP/NCE6X0100/&amp;
RF TEST&amp;
  1.ANZT/TWGS&amp;
  2  AY 435 Y 03OCT 4 HELOUL DK1  0700 0820  03OCT  E  0 AT7 N&amp;
     OPERATED BY NORDIC REG FOR FINNAIR&amp;
     OPERATED BY NORDIC REGIONAL AIRLINES OY&amp;
     SEE RTSVC&amp;
  3 AP 0600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="11" responseEndLine="125" responseBeginLine="123" endLine="120" beginLine="119" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:23.026494 - 02 Sep 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><COMPARISON compareAt="14:25:23.507030 - 02 Sep 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[           YG]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  2SEP24/1225]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[7OMGYP]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  1.ANZT/TWGS&amp;
  2  AY 435 Y 03OCT 4 HELOUL HK1  0700 0820  03OCT  E  AY/7OMGYP&amp;
  3 AP 0600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="12" responseEndLine="182" responseBeginLine="172" endLine="170" beginLine="135" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:24.522504 - 02 Sep 2024"><TEXT><![CDATA[PATCH /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[/elements HTTP/1.1&amp;
Content-Type: text/plain&amp;
Debug-Format: json&amp;
If-Match: 1&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline"><VALUE><![CDATA[eyJub25jZSI6Ik56WXpNVGs1TlRZMk5EQTJOVEF6TkE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjU6MTYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJacGZ6NmRTVzZ6RlVqN25hd1BtTUxPUzM2eTA9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
[&amp;
    \{&amp;
\t\t&quot;action&quot;: &quot;add&quot;,&amp;
\t\t&quot;model&quot;: &quot;Contact&quot;,&amp;
\t\t&quot;element&quot;: \{&amp;
\t\t\t&quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-SSR-11&quot;,&amp;
            &quot;address&quot;: \{&amp;
                &quot;category&quot;: &quot;DESTINATION&quot;,&amp;
                &quot;lines&quot;: [&amp;
                    &quot;301 PARK AVENUE&quot;&amp;
                ],&amp;
                &quot;postalCode&quot;: &quot;10022&quot;,&amp;
                &quot;countryCode&quot;: &quot;USA&quot;,&amp;
                &quot;cityName&quot;: &quot;NEW YORK&quot;,&amp;
                &quot;stateCode&quot;: &quot;NY&quot;&amp;
            \},&amp;
            &quot;purpose&quot;: [&amp;
                &quot;REGULATORY&quot;&amp;
            ],&amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-09-02]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
\t\t\}&amp;
\t\}&amp;
]]]></TEXT></QUERY><COMPARISON compareAt="14:25:25.325421 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001NVHI6J6QIC]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2755]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[&quot;openPnr&quot;: \{&amp;
        &quot;id&quot;: &quot;7OMGYP-2024-09-02&quot;, &amp;
        &quot;type&quot;: &quot;pnr&quot;, &amp;
        &quot;reference&quot;: &quot;7OMGYP&quot;, &amp;
        &quot;version&quot;: &quot;2&quot;, &amp;
        &quot;creation&quot;: \{&amp;
            &quot;dateTime&quot;: &quot;2024-09-02T12:25:00Z&quot;, &amp;
            &quot;pointOfSale&quot;: \{&amp;
                &quot;office&quot;: \{&amp;
                    &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                    &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                    &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                    &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
                \}, &amp;
                &quot;login&quot;: \{&amp;
                    &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                    &quot;initials&quot;: &quot;YG&quot;, &amp;
                    &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                    &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                    &quot;cityCode&quot;: &quot;NCE&quot;&amp;
                \}&amp;
            \}&amp;
        \}, &amp;
        &quot;lastModification&quot;: \{&amp;
            &quot;dateTime&quot;: &quot;2024-09-02T12:25:24Z&quot;&amp;
        \}, &amp;
        &quot;travelers&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                &quot;names&quot;: [&amp;
                    \{&amp;
                        &quot;firstName&quot;: &quot;TWGS&quot;, &amp;
                        &quot;lastName&quot;: &quot;ANZT&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;contacts&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;contact&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AP-2&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                    \}, &amp;
                    \{&amp;
                        &quot;type&quot;: &quot;contact&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-SSR-10&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;passenger&quot;: \{&amp;
                    &quot;uniqueIdentifier&quot;: &quot;610463D30000BD00&quot;&amp;
                \}&amp;
            \}&amp;
        ], &amp;
        &quot;products&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;product&quot;, &amp;
                &quot;subType&quot;: &quot;AIR&quot;, &amp;
                &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AIR-1&quot;, &amp;
                &quot;airSegment&quot;: \{&amp;
                    &quot;departure&quot;: \{&amp;
                        &quot;iataCode&quot;: &quot;HEL&quot;, &amp;
                        &quot;localDateTime&quot;: &quot;2024-10-03T07:00:00&quot;&amp;
                    \}, &amp;
                    &quot;arrival&quot;: \{&amp;
                        &quot;iataCode&quot;: &quot;OUL&quot;, &amp;
                        &quot;localDateTime&quot;: &quot;2024-10-03T08:20:00&quot;&amp;
                    \}, &amp;
                    &quot;marketing&quot;: \{&amp;
                        &quot;flightDesignator&quot;: \{&amp;
                            &quot;carrierCode&quot;: &quot;AY&quot;, &amp;
                            &quot;flightNumber&quot;: &quot;435&quot;&amp;
                        \}, &amp;
                        &quot;bookingClass&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;, &amp;
                            &quot;cabin&quot;: \{&amp;
                                &quot;code&quot;: &quot;Y&quot;, &amp;
                                &quot;bidPrice&quot;: \{&amp;
                                    &quot;amount&quot;: &quot;38&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;BID_PRICE&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;subClass&quot;: \{&amp;
                                &quot;code&quot;: 0, &amp;
                                &quot;pointOfSale&quot;: \{&amp;
                                    &quot;office&quot;: \{&amp;
                                        &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                    \}, &amp;
                                    &quot;login&quot;: \{&amp;
                                        &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                    \}&amp;
                                \}, &amp;
                                &quot;yields&quot;: [&amp;
                                    \{&amp;
                                        &quot;amount&quot;: &quot;270&quot;, &amp;
                                        &quot;elementaryPriceType&quot;: &quot;ADJUSTED_YIELD&quot;&amp;
                                    \}, &amp;
                                    \{&amp;
                                        &quot;amount&quot;: &quot;232&quot;, &amp;
                                        &quot;elementaryPriceType&quot;: &quot;EFFECTIVE_YIELD&quot;&amp;
                                    \}, &amp;
                                    \{&amp;
                                        &quot;amount&quot;: &quot;270&quot;, &amp;
                                        &quot;elementaryPriceType&quot;: &quot;OND_YIELD&quot;&amp;
                                    \}&amp;
                                ], &amp;
                                &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                            \}, &amp;
                            &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                        \}, &amp;
                        &quot;id&quot;: &quot;AY-435-2024-10-03-HEL-OUL&quot;&amp;
                    \}, &amp;
                    &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                    &quot;deliveries&quot;: [&amp;
                        \{&amp;
                            &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-BKG-1&quot;, &amp;
                            &quot;distributionId&quot;: &quot;600553D500018E8F&quot;, &amp;
                            &quot;traveler&quot;: \{&amp;
                                &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                                &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                            \}&amp;
                        \}&amp;
                    ], &amp;
                    &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                    &quot;notAcknowledged&quot;: false&amp;
                \}&amp;
            \}&amp;
        ], &amp;
        &quot;contacts&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;contact&quot;, &amp;
                &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AP-2&quot;, &amp;
                &quot;purpose&quot;: [&amp;
                    &quot;STANDARD&quot;&amp;
                ], &amp;
                &quot;freeFlowFormat&quot;: &quot;0600000666&quot;, &amp;
                &quot;travelerRefs&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ]&amp;
            \}, &amp;
            \{&amp;
                &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-SSR-10&quot;, &amp;
                &quot;address&quot;: \{&amp;
                    &quot;category&quot;: &quot;DESTINATION&quot;, &amp;
                    &quot;lines&quot;: [&amp;
                        &quot;301 PARK AVENUE&quot;&amp;
                    ], &amp;
                    &quot;postalCode&quot;: &quot;10022&quot;, &amp;
                    &quot;countryCode&quot;: &quot;USA&quot;, &amp;
                    &quot;cityName&quot;: &quot;NEW YORK&quot;, &amp;
                    &quot;stateCode&quot;: &quot;NY&quot;&amp;
                \}, &amp;
                &quot;purpose&quot;: [&amp;
                    &quot;REGULATORY&quot;&amp;
                ], &amp;
                &quot;travelerRefs&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        ], &amp;
        &quot;automatedProcesses&quot;: [&amp;
            \{&amp;
                &quot;type&quot;: &quot;automated-process&quot;, &amp;
                &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-TK-3&quot;, &amp;
                &quot;code&quot;: &quot;OK&quot;, &amp;
                &quot;dateTime&quot;: &quot;2024-09-02T00:00:00&quot;, &amp;
                &quot;office&quot;: \{&amp;
                    &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
                \}, &amp;
                &quot;travelers&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                    \}&amp;
                ], &amp;
                &quot;products&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;product&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AIR-1&quot;, &amp;
                        &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                    \}&amp;
                ]&amp;
            \}&amp;
        ]&amp;
    \}&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="13" responseEndLine="210" responseBeginLine="199" endLine="198" beginLine="192" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:25.327340 - 02 Sep 2024"><TEXT><![CDATA[GET /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[ HTTP/1.1&amp;
Content-Type: text/plain&amp;
Debug-format: json&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_2"><VALUE><![CDATA[eyJub25jZSI6Ik1EQTBORGd3TXpJd05EVXpNamt5TWc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjU6MTYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJTbE9NMnkvSHlyL3VYejBjUllYdGtaaUZwWk09In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT></QUERY><COMPARISON compareAt="14:25:25.617593 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001NVHI9J6QID]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1721]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[ChE3T01HWVAtMjAyNC0wOS0wMhIDcG5yGgY3T01HWVAiATI6VRoUMjAyNC0wOS0wMlQxMjoyNTowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0wOS0wMlQxMjoyNToyNFp6ygEKC3N0YWtlaG9sZGVyEho3T01HWVAtMjAyNC0wOS0wMi1QTlItTk0tMSIMEgRUV0dTGgRBTlpUcjwKB2NvbnRhY3QSGjdPTUdZUC0yMDI0LTA5LTAyLVBOUi1BUC0yGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPgoHY29udGFjdBIcN09NR1lQLTIwMjQtMDktMDItUE5SLVNTUi0xMBoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTA0NjNEMzAwMDBCRDAwggGXAwoHcHJvZHVjdBABGhs3T01HWVAtMjAyNC0wOS0wMi1QTlItQUlSLTEi7AIKGgoDSEVMGhMyMDI0LTEwLTAzVDA3OjAwOjAwEhoKA09VTBoTMjAyNC0xMC0wM1QwODoyMDowMCKfAQoJCgJBWRIDNDM1EncKAVkSFAoBWRIPCgIzOCIJQklEX1BSSUNFGlMKABIMCgQaAjZYEgQqAkZSGhUKAzI3MCIOQURKVVNURURfWUlFTEQaFgoDMjMyIg9FRkZFQ1RJVkVfWUlFTEQaEAoDMjcwIglPTkRfWUlFTEQgASIHRUNPTk9NWTIZQVktNDM1LTIwMjQtMTAtMDMtSEVMLU9VTEoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzdPTUdZUC0yMDI0LTA5LTAyLVBOUi1CS0ctMRoQNjAwNTUzRDUwMDAxOEU4RlpBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAsgF5Cgdjb250YWN0Eho3T01HWVAtMjAyNC0wOS0wMi1QTlItQVAtMkIBAVoMCgowNjAwMDAwNjY2YkEKC3N0YWtlaG9sZGVyEho3T01HWVAtMjAyNC0wOS0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7IBkwESHDdPTUdZUC0yMDI0LTA5LTAyLVBOUi1TU1ItMTAqLQgBEg8zMDEgUEFSSyBBVkVOVUUaBTEwMDIyIgNVU0EqCE5FVyBZT1JLMgJOWUIBBGJBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AdUBChFhdXRvbWF0ZWQtcHJvY2VzcxIaN09NR1lQLTIwMjQtMDktMDItUE5SLVRLLTMYBSITMjAyNC0wOS0wMlQwMDowMDowMCoLCglOQ0U2WDAxMDBaQQoLc3Rha2Vob2xkZXISGjdPTUdZUC0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSGzdPTUdZUC0yMDI0LTA5LTAyLVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14" responseEndLine="235" responseBeginLine="228" endLine="226" beginLine="220" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:25.619542 - 02 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Debug-Format: debug&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_3"><VALUE><![CDATA[eyJub25jZSI6Ik5EZzROemd6T0RZek5qZzBOekl5T0E9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjU6MTYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJHdXZUVURlaXNlY252NWErd25IMUdMbmFEMTQ9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ChE3T01HWVAtMjAyNC0wOS0wMhIDcG5yGgY3T01HWVAiATI6VRoUMjAyNC0wOS0wMlQxMjoyNTowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0wOS0wMlQxMjoyNToyNFp6ygEKC3N0YWtlaG9sZGVyEho3T01HWVAtMjAyNC0wOS0wMi1QTlItTk0tMSIMEgRUV0dTGgRBTlpUcjwKB2NvbnRhY3QSGjdPTUdZUC0yMDI0LTA5LTAyLVBOUi1BUC0yGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPgoHY29udGFjdBIcN09NR1lQLTIwMjQtMDktMDItUE5SLVNTUi0xMBoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTA0NjNEMzAwMDBCRDAwggGXAwoHcHJvZHVjdBABGhs3T01HWVAtMjAyNC0wOS0wMi1QTlItQUlSLTEi7AIKGgoDSEVMGhMyMDI0LTEwLTAzVDA3OjAwOjAwEhoKA09VTBoTMjAyNC0xMC0wM1QwODoyMDowMCKfAQoJCgJBWRIDNDM1EncKAVkSFAoBWRIPCgIzOCIJQklEX1BSSUNFGlMKABIMCgQaAjZYEgQqAkZSGhUKAzI3MCIOQURKVVNURURfWUlFTEQaFgoDMjMyIg9FRkZFQ1RJVkVfWUlFTEQaEAoDMjcwIglPTkRfWUlFTEQgASIHRUNPTk9NWTIZQVktNDM1LTIwMjQtMTAtMDMtSEVMLU9VTEoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzdPTUdZUC0yMDI0LTA5LTAyLVBOUi1CS0ctMRoQNjAwNTUzRDUwMDAxOEU4RlpBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAsgF5Cgdjb250YWN0Eho3T01HWVAtMjAyNC0wOS0wMi1QTlItQVAtMkIBAVoMCgowNjAwMDAwNjY2YkEKC3N0YWtlaG9sZGVyEho3T01HWVAtMjAyNC0wOS0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7IBkwESHDdPTUdZUC0yMDI0LTA5LTAyLVBOUi1TU1ItMTAqLQgBEg8zMDEgUEFSSyBBVkVOVUUaBTEwMDIyIgNVU0EqCE5FVyBZT1JLMgJOWUIBBGJBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AdUBChFhdXRvbWF0ZWQtcHJvY2VzcxIaN09NR1lQLTIwMjQtMDktMDItUE5SLVRLLTMYBSITMjAyNC0wOS0wMlQwMDowMDowMCoLCglOQ0U2WDAxMDBaQQoLc3Rha2Vob2xkZXISGjdPTUdZUC0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSGzdPTUdZUC0yMDI0LTA5LTAyLVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="14:25:25.772699 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001NVHIBJ6QID]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2708]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;7OMGYP-2024-09-02&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;7OMGYP&quot;, &amp;
    &quot;version&quot;: &quot;2&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:25:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:25:24Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;TWGS&quot;, &amp;
                    &quot;lastName&quot;: &quot;ANZT&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-SSR-10&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610463D30000BD00&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;HEL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-03T07:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;OUL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-03T08:20:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;AY&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;435&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;, &amp;
                            &quot;bidPrice&quot;: \{&amp;
                                &quot;amount&quot;: &quot;38&quot;, &amp;
                                &quot;elementaryPriceType&quot;: &quot;BID_PRICE&quot;&amp;
                            \}&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;yields&quot;: [&amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;270&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;ADJUSTED_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;232&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;EFFECTIVE_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;270&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;OND_YIELD&quot;&amp;
                                \}&amp;
                            ], &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;AY-435-2024-10-03-HEL-OUL&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600553D500018E8F&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;0600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-SSR-10&quot;, &amp;
            &quot;address&quot;: \{&amp;
                &quot;category&quot;: &quot;DESTINATION&quot;, &amp;
                &quot;lines&quot;: [&amp;
                    &quot;301 PARK AVENUE&quot;&amp;
                ], &amp;
                &quot;postalCode&quot;: &quot;10022&quot;, &amp;
                &quot;countryCode&quot;: &quot;USA&quot;, &amp;
                &quot;cityName&quot;: &quot;NEW YORK&quot;, &amp;
                &quot;stateCode&quot;: &quot;NY&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;REGULATORY&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-TK-3&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-09-02T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="15" responseEndLine="250" responseBeginLine="247" endLine="244" beginLine="243" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:25.774145 - 02 Sep 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="14:25:26.205082 - 02 Sep 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[           AB]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  2SEP24/1225]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(local).*?SSR DOCA}]]></EXPRESSION><VALUE><![CDATA[  1.ANZT/TWGS&amp;
  2  AY 435 Y 03OCT 4 HELOUL HK1  0700 0820  03OCT  E  AY/7OMGYP&amp;
  3 AP 0600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
  5 SSR DOCA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ AY HK1 D/USA/301 PARK AVENUE/NEW YORK/NY/10022&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  6 OPW-29SEP:0400/1C7/AY REQUIRES TICKET ON OR BEFORE&amp;
        02OCT:0400 NCE TIME ZONE/TKT/S2&amp;
  7 OPC-02OCT:0400/1C8/AY CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="16" responseEndLine="270" responseBeginLine="268" endLine="266" beginLine="262" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:27.213638 - 02 Sep 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:25:27.426851 - 02 Sep 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:7OMGYP::020924:1225&apos;&amp;
RSI+RP:ABSU:NCE6X0100:00631002+NCE6X0100+NCE+NCE6X0100:1127YG:020924:00631002:1225&apos;&amp;
LFT+3:P12+--- RLR ---&apos;&amp;
STX+RLR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00360124:SYD6X0102+A&apos;&amp;
SYS++6X:SYD&apos;&amp;
PRE+AU&apos;&amp;
SEQ++3]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2024:10:7&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+ANZT::1+TWGS&apos;&amp;
ETI+:1+UN:Y:Y::ANZT:TWGS&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+031024:0700:031024:0820+HEL+OUL+AY+435:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+AY:7OMGYP&apos;&amp;
RPI+1+HK&apos;&amp;
APD+AT7:0:0120::4+++320:M+::0615+M:N&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
IFT+3+     OPERATED BY NORDIC REGIONAL AIRLINES OY&apos;&amp;
FSD&apos;&amp;
TVL+031024:0700:031024:0820+HEL+OUL&apos;&amp;
IFT+ACO+AIRCRAFT OWNER NORDIC REGIONAL AIRLINES&apos;&amp;
IFT+OPC+OPERATED BY /NORDIC REG FOR FINNAIR&apos;&amp;
DUM&apos;&amp;
DUM&apos;&amp;
EMS++OT:2+AP+3&apos;&amp;
LFT+3:5+0600000666&apos;&amp;
EMS++OT:3+TK+4&apos;&amp;
TKE++OK:020924::NCE6X0100&apos;&amp;
EMS++OT:10+SSR+5&apos;&amp;
SSR+DOCA:HK:1:AY:::::D/USA/301 PARK AVENUE/NEW YORK/NY/10022&apos;&amp;
REF+PT:1&apos;&amp;
EMS++OT:8+OPW+6&apos;&amp;
OPE+NCE6X0100:290924:1:7:AY REQUIRES TICKET ON OR BEFORE 02OCT\:0400 NCE TIME ZONE::0400&apos;&amp;
REF+ST:1&apos;&amp;
EMS++OT:7+OPC+7&apos;&amp;
OPE+NCE6X0100:021024:1:8:AY CANCELLATION DUE TO NO TICKET NCE TIME ZONE::0400&apos;&amp;
REF+ST:1*PT:1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="16"><QUERY filename="" loop="0" sentAt="14:25:27.428181 - 02 Sep 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="17" responseEndLine="303" responseBeginLine="290" endLine="287" beginLine="281" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:27.473428 - 02 Sep 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE1A0900++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[02SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:25:27.542700 - 02 Sep 2024" match="OK"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[02SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[20240902\:12\:25\:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%backend%=*}]]></EXPRESSION><VALUE><![CDATA[SONPK4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:09:02:12:25:25]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%message_id%=*}]]></EXPRESSION><VALUE><![CDATA[4681453513]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%sdi_date2%=*}]]></EXPRESSION><VALUE><![CDATA[2024:09:02:12:25:25]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="18" responseEndLine="323" responseBeginLine="317" endLine="316" beginLine="312" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:27.545671 - 02 Sep 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[4681453513]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[SONPK4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[2024:09:02:12:25:25]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="14:25:27.600476 - 02 Sep 2024" match="OK"><TEXT><![CDATA[UNH++PUPIRR:14:1:1A+&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[4681453513]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+SONPK4&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:09:02:12:25:25]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
BLB+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1484]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%raw_binary%=(multi).*}]]></EXPRESSION><VALUE><![CDATA[\x0A\xAC\x0B\x12\xCF\x0A\x0A\x117OMGYP-2024-09-02\x12\x03pnr\x1A\x067OMGYP&quot;\x012:U\x1A\x142024-09-02T12:25:00Z&quot;=\x0A&quot;\x0A\x09NCE6X0100\x12\x0800631002\x1A\x026X&quot;\x07AIRLINE\x12\x17\x0A\x041127\x12\x02YG\x1A\x02SU*\x02FR2\x03NCEJ\}\x1A\x142024-09-02T12:25:24Z&quot;\x0D\x0A\x0B\x0A\x09SYD6X0102*\x11NDCX ORDER CREATE2\x03\x12\x011:&gt;\x12\x10historyChangeLog\x18\x01&quot;\x1C7OMGYP-2024-09-02-PNR-SSR-10*\x002\x08contactsz\xCA\x01\x0A\x0Bstakeholder\x12\x1A7OMGYP-2024-09-02-PNR-NM-1&quot;\x0C\x12\x04TWGS\x1A\x04ANZTr&lt;\x0A\x07contact\x12\x1A7OMGYP-2024-09-02-PNR-AP-2\x1A\x15processedPnr.contactsr&gt;\x0A\x07contact\x12\x1C7OMGYP-2024-09-02-PNR-SSR-10\x1A\x15processedPnr.contacts\xA2\x01\x12\x12\x10610463D30000BD00\x82\x01\x9B\x03\x0A\x07product\x10\x01\x1A\x1B7OMGYP-2024-09-02-PNR-AIR-1&quot;\xF0\x02\x0A\x1A\x0A\x03HEL\x1A\x132024-10-03T07:00:00\x12\x1A\x0A\x03OUL\x1A\x132024-10-03T08:20:00&quot;\xA1\x01\x0A\x09\x0A\x02AY\x12\x03435\x12y\x0A\x01Y\x12\x14\x0A\x01Y\x12\x0F\x0A\x0238&quot;\x09BID_PRICE\x1AU\x0A\x02\x08\x00\x12\x0C\x0A\x04\x1A\x026X\x12\x04*\x02FR\x1A\x15\x0A\x03270&quot;\x0EADJUSTED_YIELD\x1A\x16\x0A\x03232&quot;\x0FEFFECTIVE_YIELD\x1A\x10\x0A\x03270&quot;\x09OND_YIELD \x01&quot;\x07ECONOMY2\x19AY-435-2024-10-03-HEL-OULJ\x02HKb\x84\x01\x0A\x10segment-delivery\x12\x1B7OMGYP-2024-09-02-PNR-BKG-1\x1A\x10600553D500018E8FZA\x0A\x0Bstakeholder\x12\x1A7OMGYP-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\x8A\x01\x01E\x92\x01\x02\x08\x00\xB2\x01x\x0A\x07contact\x12\x1A7OMGYP-2024-09-02-PNR-AP-2@\x01Z\x0C\x0A\x0A0600000666bA\x0A\x0Bstakeholder\x12\x1A7OMGYP-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\xB2\x01\x92\x01\x12\x1C7OMGYP-2024-09-02-PNR-SSR-10*-\x08\x01\x12\x0F301 PARK AVENUE\x1A\x0510022&quot;\x03USA*\x08NEW YORK2\x02NY@\x04bA\x0A\x0Bstakeholder\x12\x1A7OMGYP-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelers\xBA\x01\xD5\x01\x0A\x11automated-process\x12\x1A7OMGYP-2024-09-02-PNR-TK-3\x18\x05&quot;\x132024-09-02T00:00:00*\x0B\x0A\x09NCE6X0100ZA\x0A\x0Bstakeholder\x12\x1A7OMGYP-2024-09-02-PNR-NM-1\x1A\x16processedPnr.travelersb=\x0A\x07product\x12\x1B7OMGYP-2024-09-02-PNR-AIR-1\x1A\x15processedPnr.products\x1AX\x0A\x1Fapplication/vnd.google.protobuf\x12\x067OMGYP\x1A\x012&quot;\x03Pnr*\%com.amadeus.models.reservation.pnr.v2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[UNT\x1D2\x1D1\x1C&apos;&amp;
&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="19" responseEndLine="351" responseBeginLine="344" endLine="342" beginLine="337" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:27.602093 - 02 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline_4"><VALUE><![CDATA[eyJub25jZSI6Ik5EQXhNalExTURNME1ESTNNVE0wT0E9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMDJUMTI6MjU6MTYuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJ3Tm9DWDBoM29BR1N4aW1lSlN5T3lvbmRBUDA9In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="global_regression.openpnr_payload"><VALUE><![CDATA[ChE3T01HWVAtMjAyNC0wOS0wMhIDcG5yGgY3T01HWVAiATI6VRoUMjAyNC0wOS0wMlQxMjoyNTowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKfRoUMjAyNC0wOS0wMlQxMjoyNToyNFoiDQoLCglTWUQ2WDAxMDIqEU5EQ1ggT1JERVIgQ1JFQVRFMgMSATE6PhIQaGlzdG9yeUNoYW5nZUxvZxgBIhw3T01HWVAtMjAyNC0wOS0wMi1QTlItU1NSLTEwKgAyCGNvbnRhY3RzesoBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEiDBIEVFdHUxoEQU5aVHI8Cgdjb250YWN0Eho3T01HWVAtMjAyNC0wOS0wMi1QTlItQVAtMhoVcHJvY2Vzc2VkUG5yLmNvbnRhY3Rzcj4KB2NvbnRhY3QSHDdPTUdZUC0yMDI0LTA5LTAyLVBOUi1TU1ItMTAaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwNDYzRDMwMDAwQkQwMIIBmwMKB3Byb2R1Y3QQARobN09NR1lQLTIwMjQtMDktMDItUE5SLUFJUi0xIvACChoKA0hFTBoTMjAyNC0xMC0wM1QwNzowMDowMBIaCgNPVUwaEzIwMjQtMTAtMDNUMDg6MjA6MDAioQEKCQoCQVkSAzQzNRJ5CgFZEhQKAVkSDwoCMzgiCUJJRF9QUklDRRpVCgIIABIMCgQaAjZYEgQqAkZSGhUKAzI3MCIOQURKVVNURURfWUlFTEQaFgoDMjMyIg9FRkZFQ1RJVkVfWUlFTEQaEAoDMjcwIglPTkRfWUlFTEQgASIHRUNPTk9NWTIZQVktNDM1LTIwMjQtMTAtMDMtSEVMLU9VTEoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSGzdPTUdZUC0yMDI0LTA5LTAyLVBOUi1CS0ctMRoQNjAwNTUzRDUwMDAxOEU4RlpBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgECCACyAXgKB2NvbnRhY3QSGjdPTUdZUC0yMDI0LTA5LTAyLVBOUi1BUC0yQAFaDAoKMDYwMDAwMDY2NmJBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOyAZIBEhw3T01HWVAtMjAyNC0wOS0wMi1QTlItU1NSLTEwKi0IARIPMzAxIFBBUksgQVZFTlVFGgUxMDAyMiIDVVNBKghORVcgWU9SSzICTllABGJBCgtzdGFrZWhvbGRlchIaN09NR1lQLTIwMjQtMDktMDItUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AdUBChFhdXRvbWF0ZWQtcHJvY2VzcxIaN09NR1lQLTIwMjQtMDktMDItUE5SLVRLLTMYBSITMjAyNC0wOS0wMlQwMDowMDowMCoLCglOQ0U2WDAxMDBaQQoLc3Rha2Vob2xkZXISGjdPTUdZUC0yMDI0LTA5LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSGzdPTUdZUC0yMDI0LTA5LTAyLVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="14:25:27.761132 - 02 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001NVHIFJ6QIF]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2951]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;7OMGYP-2024-09-02&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;7OMGYP&quot;, &amp;
    &quot;version&quot;: &quot;2&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:25:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-02T12:25:24Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;SYD6X0102&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;NDCX ORDER CREATE&quot;, &amp;
        &quot;correlationReference&quot;: \{&amp;
            &quot;correlationId&quot;: &quot;1&quot;&amp;
        \}, &amp;
        &quot;changeLog&quot;: [&amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;ADD&quot;, &amp;
                &quot;elementId&quot;: &quot;7OMGYP-2024-09-02-PNR-SSR-10&quot;, &amp;
                &quot;path&quot;: &quot;contacts&quot;&amp;
            \}&amp;
        ]&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;TWGS&quot;, &amp;
                    &quot;lastName&quot;: &quot;ANZT&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-SSR-10&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610463D30000BD00&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;HEL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-03T07:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;OUL&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-10-03T08:20:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;AY&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;435&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;, &amp;
                            &quot;bidPrice&quot;: \{&amp;
                                &quot;amount&quot;: &quot;38&quot;, &amp;
                                &quot;elementaryPriceType&quot;: &quot;BID_PRICE&quot;&amp;
                            \}&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;yields&quot;: [&amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;270&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;ADJUSTED_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;232&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;EFFECTIVE_YIELD&quot;&amp;
                                \}, &amp;
                                \{&amp;
                                    &quot;amount&quot;: &quot;270&quot;, &amp;
                                    &quot;elementaryPriceType&quot;: &quot;OND_YIELD&quot;&amp;
                                \}&amp;
                            ], &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;AY-435-2024-10-03-HEL-OUL&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600553D500018E8F&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;0600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-SSR-10&quot;, &amp;
            &quot;address&quot;: \{&amp;
                &quot;category&quot;: &quot;DESTINATION&quot;, &amp;
                &quot;lines&quot;: [&amp;
                    &quot;301 PARK AVENUE&quot;&amp;
                ], &amp;
                &quot;postalCode&quot;: &quot;10022&quot;, &amp;
                &quot;countryCode&quot;: &quot;USA&quot;, &amp;
                &quot;cityName&quot;: &quot;NEW YORK&quot;, &amp;
                &quot;stateCode&quot;: &quot;NY&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;REGULATORY&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-TK-3&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-09-02T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;7OMGYP-2024-09-02-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="20" endLine="363" beginLine="362" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:27.762812 - 02 Sep 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7OMGYP]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="14:25:27.998735 - 02 Sep 2024" filename="">--- RLR ---&amp;
RP/NCE6X0100/NCE6X0100            AB/SU   2SEP24/1225Z   7OMGYP&amp;
  1.ANZT/TWGS&amp;
  2  AY 435 Y 03OCT 4 HELOUL HK1  0700 0820  03OCT  E  AY/7OMGYP&amp;
  3 AP 0600000666&amp;
  4 TK OK02SEP/NCE6X0100&amp;
  5 SSR DOCA AY HK1 D/USA/301 PARK AVENUE/NEW YORK/NY/10022&amp;
  6 OPW-29SEP:0400/1C7/AY REQUIRES TICKET ON OR BEFORE&amp;
        02OCT:0400 NCE TIME ZONE/TKT/S2&amp;
  7 OPC-02OCT:0400/1C8/AY CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="21" endLine="364" beginLine="363" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:27.999393 - 02 Sep 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="14:25:28.253825 - 02 Sep 2024" filename="">--- RLR ---&amp;
RP/NCE6X0100/NCE6X0100            AB/SU   2SEP24/1225Z   7OMGYP&amp;
  1.ANZT/TWGS&amp;
  2 AP 0600000666&amp;
  3 TK OK02SEP/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="22" endLine="365" beginLine="364" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:28.253987 - 02 Sep 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="14:25:28.630862 - 02 Sep 2024" filename="">END OF TRANSACTION COMPLETE - 7OMGYP&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="23" endLine="366" beginLine="365" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:28.631262 - 02 Sep 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="14:25:28.702393 - 02 Sep 2024" filename="">IGNORED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="24" endLine="371" beginLine="370" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:28.703017 - 02 Sep 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="14:25:28.826155 - 02 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="25" endLine="372" beginLine="371" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Update_Feed.cry" loop="0" sentAt="14:25:28.826445 - 02 Sep 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="14:25:28.892079 - 02 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><STATISTIC><STATISTIC_ELEMENT name="Message in">26</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">30031</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">26</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">6687</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">26</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">25</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.961538</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">9167.5</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">2.325</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">5040.21</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">54</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="CPS" name="Conversations/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">2</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">0</STATISTIC_ELEMENT></STATISTIC></xml>