<xml scenarioFilename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry"><SCRIPT type="Initialize">import json
from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.
def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;id&apos;, &apos;reference&apos;, &apos;creation&apos;, &apos;travelers&apos;, &apos;products&apos;, &apos;contacts&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=&quot;SYD6X0102&quot;, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;contacts&apos;]), expected=2, item_name=&apos;number of contacts&apos;)
        contacts_1 = openpnr[&apos;contacts&apos;][0]
        contacts_2 = openpnr[&apos;contacts&apos;][1]

        #Check service data for SSR DOCA element
        assert_equal(actual=contacts_1[&apos;type&apos;], expected=&apos;contact&apos;, item_name=&apos;contact type&apos;)
        assert_equal(actual=contacts_1[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AP-2&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_1[&apos;purpose&apos;], expected= [u&apos;STANDARD&apos;], item_name=&apos;contact purpose&apos;)
        assert_equal(actual=contacts_1[&apos;freeFlowFormat&apos;], expected=&apos;+33600000666&apos;, item_name=&apos;contact freeFlowFormat&apos;)

        assert_equal(actual=contacts_2[&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-SSR-3&quot;, item_name=&apos;contact id&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;category&apos;], expected=&quot;DESTINATION&quot;, item_name=&apos;contact address/category&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;lines&apos;][0], expected= &quot;301 PARK AVENUE&quot;, item_name=&apos;contact address/lines&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;postalCode&apos;], expected= &quot;10022&quot;, item_name=&apos;contact address/postalCode&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;countryCode&apos;], expected= &quot;USA&quot;, item_name=&apos;contact address/countryCode&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;cityName&apos;], expected= &quot;NEW YORK&quot;, item_name=&apos;contact address/cityName&apos;)
        assert_equal(actual=contacts_2[&apos;address&apos;][&apos;stateCode&apos;], expected= &quot;NY&quot;, item_name=&apos;contact address/stateCode&apos;)
        assert_equal(actual=contacts_2[&apos;purpose&apos;], expected= [u&apos;REGULATORY&apos;], item_name=&apos;contact purpose&apos;)

    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="89" beginLine="88" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:14.040758 - 11 Sep 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="15:48:14.089662 - 11 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" responseEndLine="95" responseBeginLine="94" endLine="90" beginLine="89" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:14.090603 - 11 Sep 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><COMPARISON compareAt="15:48:14.150207 - 11 Sep 2024" match="OK"><TEXT><![CDATA[SIGN IN&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="3" endLine="97" beginLine="96" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:14.151081 - 11 Sep 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="15:48:14.223248 - 11 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="104" beginLine="103" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:14.223999 - 11 Sep 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="15:48:14.275686 - 11 Sep 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="106" beginLine="105" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:16.278655 - 11 Sep 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0955]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[********]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="15:48:16.334039 - 11 Sep 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="110" responseBeginLine="110" endLine="108" beginLine="107" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:16.334601 - 11 Sep 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[***************]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="15:48:16.498679 - 11 Sep 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/11SEP/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" responseEndLine="135" responseBeginLine="126" endLine="124" beginLine="119" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:16.502384 - 11 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=json\&amp;output=protobufBase64 HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header"><VALUE><![CDATA[eyJub25jZSI6Ik1UazBOVEU0TnpZNE9UQXlNamsyTVE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMTFUMTM6NDg6MTAuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiTGt6MlJKeDFiRTJwRE12V1pPYmlqZUd3Wng4PSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT><VARIABLE name="input_json_SSR_DOCA"><VALUE><![CDATA[&amp;
    \{&amp;
    &quot;last_modification&quot;: \{&amp;
        &quot;comment&quot;: &quot;ORMS&quot;&amp;
    \},&amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
            &quot;id&quot;: &quot;PAX-1&quot;,&amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;first_name&quot;: &quot;BART&quot;,&amp;
                    &quot;last_name&quot;: &quot;SIMPSON&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;sub_type&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;AIR-1&quot;,&amp;
            &quot;air_segment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iata_code&quot;: &quot;FRA&quot;,&amp;
                    &quot;local_date_time&quot;: &quot;2024-12-13&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iata_code&quot;: &quot;LHR&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flight_designator&quot;: \{&amp;
                        &quot;carrier_code&quot;: &quot;6X&quot;,&amp;
                        &quot;flight_number&quot;: &quot;7040&quot;&amp;
                    \},&amp;
                    &quot;booking_class&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;&amp;
                    \}&amp;
                \},&amp;
                &quot;booking_status_code&quot;: &quot;NN&quot;&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;PAX-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;contacts&quot;: [&amp;
          \{&amp;
              &quot;type&quot;: &quot;contact&quot;,&amp;
              &quot;id&quot;: &quot;AP-1&quot;,&amp;
              &quot;phone&quot;: \{&amp;
                  &quot;number&quot;: &quot;+33600000666&quot;&amp;
           \}, &amp;
              &quot;purpose&quot;: [&amp;
                  &quot;STANDARD&quot;&amp;
              ],&amp;
              &quot;travelerRefs&quot;: [&amp;
                  \{&amp;
                      &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                      &quot;id&quot;: &quot;PAX-1&quot;,&amp;
                      &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                  \}&amp;
              ]&amp;
          \},&amp;
          \{&amp;
              &quot;id&quot;: &quot;3XO5LI-2024-07-12-PNR-SSR-11&quot;,&amp;
              &quot;address&quot;: \{&amp;
                  &quot;category&quot;: &quot;DESTINATION&quot;,&amp;
                  &quot;lines&quot;: [&amp;
                      &quot;301 PARK AVENUE&quot;&amp;
                  ],&amp;
                  &quot;postalCode&quot;: &quot;10022&quot;,&amp;
                  &quot;countryCode&quot;: &quot;USA&quot;,&amp;
                  &quot;cityName&quot;: &quot;NEW YORK&quot;,&amp;
                  &quot;stateCode&quot;: &quot;NY&quot;&amp;
              \},&amp;
              &quot;purpose&quot;: [&amp;
                  &quot;REGULATORY&quot;&amp;
              ],&amp;
              &quot;travelerRefs&quot;: [&amp;
                  \{&amp;
                      &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                      &quot;id&quot;: &quot;PAX-1&quot;,&amp;
                      &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                  \}&amp;
              ]&amp;
          \}&amp;
      ],&amp;
      &quot;automated_processes&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;,&amp;
            &quot;code&quot;: &quot;OK&quot;&amp;
        \}&amp;
    ]&amp;
\}&amp;
]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="15:48:16.653653 - 11 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001DPEA4JNICG]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[550]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[SgYqBE9STVN6JQoLc3Rha2Vob2xkZXISBVBBWC0xIg8SBEJBUlQaB1NJTVBTT06CAXMKB3Byb2R1Y3QQARoFQUlSLTEiMQoRCgNGUkEaCjIwMjQtMTItMTMSBQoDTEhSIhEKCgoCNlgSBDcwNDASAwoBWUoCTk5CLAoLc3Rha2Vob2xkZXISBVBBWC0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzsgFQCgdjb250YWN0EgRBUC0xIg4aDCszMzYwMDAwMDY2NkIBAWIsCgtzdGFrZWhvbGRlchIFUEFYLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOyAX4SHDNYTzVMSS0yMDI0LTA3LTEyLVBOUi1TU1ItMTEqLQgBEg8zMDEgUEFSSyBBVkVOVUUaBTEwMDIyIgNVU0EqCE5FVyBZT1JLMgJOWUIBBGIsCgtzdGFrZWhvbGRlchIFUEFYLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6ARUKEWF1dG9tYXRlZC1wcm9jZXNzGAU=]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="8" responseEndLine="164" responseBeginLine="153" endLine="151" beginLine="144" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:16.655471 - 11 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/ HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header2"><VALUE><![CDATA[eyJub25jZSI6Ik1EQTBPVGsxT1RjeE16STJPREV6TlE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMTFUMTM6NDg6MTAuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoibUU3NFhvVzRwZ1Y5M0d0dklHNTl6TGdDOHVnPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[SgYqBE9STVN6JQoLc3Rha2Vob2xkZXISBVBBWC0xIg8SBEJBUlQaB1NJTVBTT06CAXMKB3Byb2R1Y3QQARoFQUlSLTEiMQoRCgNGUkEaCjIwMjQtMTItMTMSBQoDTEhSIhEKCgoCNlgSBDcwNDASAwoBWUoCTk5CLAoLc3Rha2Vob2xkZXISBVBBWC0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzsgFQCgdjb250YWN0EgRBUC0xIg4aDCszMzYwMDAwMDY2NkIBAWIsCgtzdGFrZWhvbGRlchIFUEFYLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOyAX4SHDNYTzVMSS0yMDI0LTA3LTEyLVBOUi1TU1ItMTEqLQgBEg8zMDEgUEFSSyBBVkVOVUUaBTEwMDIyIgNVU0EqCE5FVyBZT1JLMgJOWUIBBGIsCgtzdGFrZWhvbGRlchIFUEFYLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6ARUKEWF1dG9tYXRlZC1wcm9jZXNzGAU=]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></QUERY><COMPARISON compareAt="15:48:20.607803 - 11 Sep 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 201 Created&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001DPEA8JNICG]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1617]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[C5GZRX]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf2%=.*}]]></EXPRESSION><VALUE><![CDATA[ChFDNUdaUlgtMjAyNC0wOS0xMRIDcG5yGgZDNUdaUlgiATA6VRoUMjAyNC0wOS0xMVQxMzo0ODowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0wOS0xMVQxMzo0ODoxN1p6zAEKC3N0YWtlaG9sZGVyEhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItTk0tMSIPEgRCQVJUGgdTSU1QU09OcjwKB2NvbnRhY3QSGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1BUC0yGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPQoHY29udGFjdBIbQzVHWlJYLTIwMjQtMDktMTEtUE5SLVNTUi0zGhVwcm9jZXNzZWRQbnIuY29udGFjdHOiARISEDYxMEEyM0REMDAwMDgxREaCAcYCCgdwcm9kdWN0EAEaG0M1R1pSWC0yMDI0LTA5LTExLVBOUi1BSVItMSKbAgoaCgNGUkEaEzIwMjQtMTItMTNUMDc6MzU6MDASGgoDTEhSGhMyMDI0LTEyLTEzVDA4OjM1OjAwIk8KCgoCNlgSBDcwNDASJQoBWRIDCgFZGhIKABIMCgQaAjFBEgQqAkZSIAEiB0VDT05PTVkyGjZYLTcwNDAtMjAyNC0xMi0xMy1GUkEtTEhSSgJIS2KEAQoQc2VnbWVudC1kZWxpdmVyeRIbQzVHWlJYLTIwMjQtMDktMTEtUE5SLUJLRy0xGhA2MDBBQzNERTAwMDA1RTBCWkEKC3N0YWtlaG9sZGVyEhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQCyAXsKB2NvbnRhY3QSGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1BUC0yQgEBWg4KDCszMzYwMDAwMDY2NmJBCgtzdGFrZWhvbGRlchIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOyAZIBEhtDNUdaUlgtMjAyNC0wOS0xMS1QTlItU1NSLTMqLQgBEg8zMDEgUEFSSyBBVkVOVUUaBTEwMDIyIgNVU0EqCE5FVyBZT1JLMgJOWUIBBGJBCgtzdGFrZWhvbGRlchIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AdUBChFhdXRvbWF0ZWQtcHJvY2VzcxIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLVRLLTQYBSITMjAyNC0wOS0xMVQwMDowMDowMCoLCglOQ0UxQTA5NTVaQQoLc3Rha2Vob2xkZXISGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSG0M1R1pSWC0yMDI0LTA5LTExLVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="9" responseEndLine="189" responseBeginLine="182" endLine="180" beginLine="174" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:20.610411 - 11 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Debug-Format: debug&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header3"><VALUE><![CDATA[eyJub25jZSI6Ik1UVTROVFkzTmpBMk9EVTRNVEV4TXc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMTFUMTM6NDg6MTAuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiVFhiVjNOK1NiSVNSRVNzd1QvWVlMY2hnS0EwPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf2"><VALUE><![CDATA[ChFDNUdaUlgtMjAyNC0wOS0xMRIDcG5yGgZDNUdaUlgiATA6VRoUMjAyNC0wOS0xMVQxMzo0ODowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0wOS0xMVQxMzo0ODoxN1p6zAEKC3N0YWtlaG9sZGVyEhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItTk0tMSIPEgRCQVJUGgdTSU1QU09OcjwKB2NvbnRhY3QSGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1BUC0yGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPQoHY29udGFjdBIbQzVHWlJYLTIwMjQtMDktMTEtUE5SLVNTUi0zGhVwcm9jZXNzZWRQbnIuY29udGFjdHOiARISEDYxMEEyM0REMDAwMDgxREaCAcYCCgdwcm9kdWN0EAEaG0M1R1pSWC0yMDI0LTA5LTExLVBOUi1BSVItMSKbAgoaCgNGUkEaEzIwMjQtMTItMTNUMDc6MzU6MDASGgoDTEhSGhMyMDI0LTEyLTEzVDA4OjM1OjAwIk8KCgoCNlgSBDcwNDASJQoBWRIDCgFZGhIKABIMCgQaAjFBEgQqAkZSIAEiB0VDT05PTVkyGjZYLTcwNDAtMjAyNC0xMi0xMy1GUkEtTEhSSgJIS2KEAQoQc2VnbWVudC1kZWxpdmVyeRIbQzVHWlJYLTIwMjQtMDktMTEtUE5SLUJLRy0xGhA2MDBBQzNERTAwMDA1RTBCWkEKC3N0YWtlaG9sZGVyEhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQCyAXsKB2NvbnRhY3QSGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1BUC0yQgEBWg4KDCszMzYwMDAwMDY2NmJBCgtzdGFrZWhvbGRlchIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOyAZIBEhtDNUdaUlgtMjAyNC0wOS0xMS1QTlItU1NSLTMqLQgBEg8zMDEgUEFSSyBBVkVOVUUaBTEwMDIyIgNVU0EqCE5FVyBZT1JLMgJOWUIBBGJBCgtzdGFrZWhvbGRlchIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AdUBChFhdXRvbWF0ZWQtcHJvY2VzcxIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLVRLLTQYBSITMjAyNC0wOS0xMVQwMDowMDowMCoLCglOQ0UxQTA5NTVaQQoLc3Rha2Vob2xkZXISGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSG0M1R1pSWC0yMDI0LTA5LTExLVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON KO="KO" validate="manual" matchMessage="Match failed with error code 1: Callback rejected:Match function exits on unspecified Error." compareAt="15:48:20.765824 - 11 Sep 2024"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001DPEEAJNICK]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2477]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;C5GZRX-2024-09-11&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;C5GZRX&quot;, &amp;
    &quot;version&quot;: &quot;0&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-11T13:48:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;, &amp;
                &quot;iataNumber&quot;: &quot;12345675&quot;, &amp;
                &quot;systemCode&quot;: &quot;1A&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-11T13:48:17Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;BART&quot;, &amp;
                    &quot;lastName&quot;: &quot;SIMPSON&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-SSR-3&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610A23DD000081DF&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;FRA&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-13T07:35:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-13T08:35:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7040&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7040-2024-12-13-FRA-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600AC3DE00005E0B&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;+33600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-SSR-3&quot;, &amp;
            &quot;address&quot;: \{&amp;
                &quot;category&quot;: &quot;DESTINATION&quot;, &amp;
                &quot;lines&quot;: [&amp;
                    &quot;301 PARK AVENUE&quot;&amp;
                ], &amp;
                &quot;postalCode&quot;: &quot;10022&quot;, &amp;
                &quot;countryCode&quot;: &quot;USA&quot;, &amp;
                &quot;cityName&quot;: &quot;NEW YORK&quot;, &amp;
                &quot;stateCode&quot;: &quot;NY&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;REGULATORY&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-TK-4&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-09-11T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="10" responseEndLine="203" responseBeginLine="200" endLine="198" beginLine="197" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:20.767569 - 11 Sep 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 15: A character does not match, expected &apos;S&apos;, received &apos;N&apos;." compareAt="15:48:20.985647 - 11 Sep 2024"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SYD6X0102/SYD6X0102 {*}/{*} {*}Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[NCE1A0955/NCE1A0955            YG/SU  11SEP24/1348Z   C5GZRX&amp;
]]></TEXT></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(local).*?SSR DOCA}]]></EXPRESSION><VALUE><![CDATA[  1.SIMPSON/BART&amp;
  2  6X7040 Y 13DEC 5 FRALHR HK1  0735 0835  13DEC  E  6X/C5GZRX&amp;
  3 AP +33600000666&amp;
  4 TK OK11SEP/NCE1A0955&amp;
  5 SSR DOCA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ 6X HK1 D/USA/301 PARK AVENUE/NEW YORK/NY/10022&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="11" responseEndLine="223" responseBeginLine="221" endLine="219" beginLine="215" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:21.037938 - 11 Sep 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="15:48:21.257396 - 11 Sep 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:C5GZRX::110924:1348&apos;&amp;
RSI+RP:AASU:NCE1A0955:12345675+NCE1A0955+NCE+NCE1A0955:1127YG:110924:12345675:1348&apos;&amp;
LFT+3:P12+--- RLR ---&apos;&amp;
STX+RLR&apos;&amp;
UID+12345675:NCE1A0955+A&apos;&amp;
SYS++1A:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+12345675:NCE1A0955+A&apos;&amp;
SYS++1A:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+12345675:NCE1A0955+A&apos;&amp;
SYS++1A:NCE&apos;&amp;
PRE+FR&apos;&amp;
SEQ++2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2024:12:17&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+SIMPSON::1+BART&apos;&amp;
ETI+:1+UN:Y:Y::SIMPSON:BART&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+131224:0735:131224:0835+FRA+LHR+6X+7040:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+6X:C5GZRX&apos;&amp;
RPI+1+HK&apos;&amp;
APD+738:0:0200::5+++407:M++M:M&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
FSD&apos;&amp;
TVL+131224:0735:131224:0835+FRA+LHR&apos;&amp;
IFT+ACO+AIRCRAFT OWNER AMADEUS SIX&apos;&amp;
DUM&apos;&amp;
REF+PT:1&apos;&amp;
DUM&apos;&amp;
EMS++OT:2+AP+3&apos;&amp;
LFT+3:5+\+33600000666&apos;&amp;
REF+PT:1&apos;&amp;
EMS++OT:4+TK+4&apos;&amp;
TKE++OK:110924::NCE1A0955&apos;&amp;
EMS++OT:3+SSR+5&apos;&amp;
SSR+DOCA:HK:1:6X:::::D/USA/301 PARK AVENUE/NEW YORK/NY/10022&apos;&amp;
REF+PT:1&apos;&amp;
EMS++OT:9+OPC+6&apos;&amp;
OPE+NCE1A0955:110924:1:8:6X CANCELLATION DUE TO NO TICKET NCE TIME ZONE::1550&apos;&amp;
REF+ST:1*PT:1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="11"><QUERY filename="" loop="0" sentAt="15:48:21.259301 - 11 Sep 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="12" responseEndLine="256" responseBeginLine="243" endLine="241" beginLine="235" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="looping"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:21.385470 - 11 Sep 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE6X0100++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[11SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 70: Missing character(s)" compareAt="15:48:21.456130 - 11 Sep 2024"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[11SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[::{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+{%backend%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{%message_id%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{%sdi_date2%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="12" responseEndLine="256" responseBeginLine="243" endLine="241" beginLine="235" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="1" sentAt="15:48:24.458164 - 11 Sep 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE6X0100++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[11SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON compareAt="15:48:24.527556 - 11 Sep 2024" match="OK"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[11SEP24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[20240911\:13\:48\:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%backend%=*}]]></EXPRESSION><VALUE><![CDATA[SONPK1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:09:11:13:48:21]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%message_id%=*}]]></EXPRESSION><VALUE><![CDATA[8221920074]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%sdi_date2%=*}]]></EXPRESSION><VALUE><![CDATA[2024:09:11:13:48:21]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="13" responseEndLine="276" responseBeginLine="270" endLine="269" beginLine="265" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:24.574717 - 11 Sep 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[8221920074]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[SONPK1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[2024:09:11:13:48:21]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="15:48:24.633899 - 11 Sep 2024" match="OK"><TEXT><![CDATA[UNH++PUPIRR:14:1:1A+&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[8221920074]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+SONPK]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:09:11:13:48:21]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
BLB+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1357]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%raw_binary%=(multi).*}]]></EXPRESSION><VALUE><![CDATA[\x0A\xAD\x0A\x12\xD0\x09\x0A\x11C5GZRX-2024-09-11\x12\x03pnr\x1A\x06C5GZRX&quot;\x011:q\x1A\x142024-09-11T13:48:00Z&quot;=\x0A&quot;\x0A\x09NCE1A0955\x12\x0812345675\x1A\x021A&quot;\x07AIRLINE\x12\x17\x0A\x041127\x12\x02YG\x1A\x02SU*\x02FR2\x03NCE*\x1A1APUB/ATL-0001AA/NCE1A0955J0\x1A\x142024-09-11T13:48:20Z&quot;\x0D\x0A\x0B\x0A\x09NCE1A0238*\x091APUB/ATLz\xCC\x01\x0A\x0Bstakeholder\x12\x1AC5GZRX-2024-09-11-PNR-NM-1&quot;\x0F\x12\x04BART\x1A\x07SIMPSONr&lt;\x0A\x07contact\x12\x1AC5GZRX-2024-09-11-PNR-AP-2\x1A\x15processedPnr.contactsr=\x0A\x07contact\x12\x1BC5GZRX-2024-09-11-PNR-SSR-3\x1A\x15processedPnr.contacts\xA2\x01\x12\x12\x10610A23DD000081DF\x82\x01\xCA\x02\x0A\x07product\x10\x01\x1A\x1BC5GZRX-2024-09-11-PNR-AIR-1&quot;\x9F\x02\x0A\x1A\x0A\x03FRA\x1A\x132024-12-13T07:35:00\x12\x1A\x0A\x03LHR\x1A\x132024-12-13T08:35:00&quot;Q\x0A\x0A\x0A\x026X\x12\x047040\x12&apos;&amp;
\x0A\x01Y\x12\x03\x0A\x01Y\x1A\x14\x0A\x02\x08\x00\x12\x0C\x0A\x04\x1A\x021A\x12\x04*\x02FR \x01&quot;\x07ECONOMY2\x1A6X-7040-2024-12-13-FRA-LHRJ\x02HKb\x84\x01\x0A\x10segment-delivery\x12\x1BC5GZRX-2024-09-11-PNR-BKG-1\x1A\x10600AC3DE00005E0BZA\x0A\x0Bstakeholder\x12\x1AC5GZRX-2024-09-11-PNR-NM-1\x1A\x16processedPnr.travelers\x8A\x01\x01E\x92\x01\x02\x08\x00\xB2\x01z\x0A\x07contact\x12\x1AC5GZRX-2024-09-11-PNR-AP-2@\x01Z\x0E\x0A\x0C+33600000666bA\x0A\x0Bstakeholder\x12\x1AC5GZRX-2024-09-11-PNR-NM-1\x1A\x16processedPnr.travelers\xB2\x01\x91\x01\x12\x1BC5GZRX-2024-09-11-PNR-SSR-3*-\x08\x01\x12\x0F301 PARK AVENUE\x1A\x0510022&quot;\x03USA*\x08NEW YORK2\x02NY@\x04bA\x0A\x0Bstakeholder\x12\x1AC5GZRX-2024-09-11-PNR-NM-1\x1A\x16processedPnr.travelers\xBA\x01\xD5\x01\x0A\x11automated-process\x12\x1AC5GZRX-2024-09-11-PNR-TK-4\x18\x05&quot;\x132024-09-11T00:00:00*\x0B\x0A\x09NCE1A0955ZA\x0A\x0Bstakeholder\x12\x1AC5GZRX-2024-09-11-PNR-NM-1\x1A\x16processedPnr.travelersb=\x0A\x07product\x12\x1BC5GZRX-2024-09-11-PNR-AIR-1\x1A\x15processedPnr.products\x1AX\x0A\x1Fapplication/vnd.google.protobuf\x12\x06C5GZRX\x1A\x011&quot;\x03Pnr*\%com.amadeus.models.reservation.pnr.v2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[UNT\x1D2\x1D1\x1C&apos;&amp;
&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14" responseEndLine="304" responseBeginLine="297" endLine="295" beginLine="290" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:24.635530 - 11 Sep 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header4"><VALUE><![CDATA[eyJub25jZSI6Ik56VXdNVE16TmprMU1EWTJOamsyTUE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDktMTFUMTM6NDg6MTAuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoicEpMQmc4ZWU0d2R2TzdFbWM0bmxFS0lzdlo0PSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="global_regression.openpnr_payload"><VALUE><![CDATA[ChFDNUdaUlgtMjAyNC0wOS0xMRIDcG5yGgZDNUdaUlgiATE6cRoUMjAyNC0wOS0xMVQxMzo0ODowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0UqGjFBUFVCL0FUTC0wMDAxQUEvTkNFMUEwOTU1SjAaFDIwMjQtMDktMTFUMTM6NDg6MjBaIg0KCwoJTkNFMUEwMjM4KgkxQVBVQi9BVEx6zAEKC3N0YWtlaG9sZGVyEhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItTk0tMSIPEgRCQVJUGgdTSU1QU09OcjwKB2NvbnRhY3QSGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1BUC0yGhVwcm9jZXNzZWRQbnIuY29udGFjdHNyPQoHY29udGFjdBIbQzVHWlJYLTIwMjQtMDktMTEtUE5SLVNTUi0zGhVwcm9jZXNzZWRQbnIuY29udGFjdHOiARISEDYxMEEyM0REMDAwMDgxREaCAcoCCgdwcm9kdWN0EAEaG0M1R1pSWC0yMDI0LTA5LTExLVBOUi1BSVItMSKfAgoaCgNGUkEaEzIwMjQtMTItMTNUMDc6MzU6MDASGgoDTEhSGhMyMDI0LTEyLTEzVDA4OjM1OjAwIlEKCgoCNlgSBDcwNDASJwoBWRIDCgFZGhQKAggAEgwKBBoCMUESBCoCRlIgASIHRUNPTk9NWTIaNlgtNzA0MC0yMDI0LTEyLTEzLUZSQS1MSFJKAkhLYoQBChBzZWdtZW50LWRlbGl2ZXJ5EhtDNUdaUlgtMjAyNC0wOS0xMS1QTlItQktHLTEaEDYwMEFDM0RFMDAwMDVFMEJaQQoLc3Rha2Vob2xkZXISGkM1R1pSWC0yMDI0LTA5LTExLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzigEBRZIBAggAsgF6Cgdjb250YWN0EhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItQVAtMkABWg4KDCszMzYwMDAwMDY2NmJBCgtzdGFrZWhvbGRlchIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOyAZEBEhtDNUdaUlgtMjAyNC0wOS0xMS1QTlItU1NSLTMqLQgBEg8zMDEgUEFSSyBBVkVOVUUaBTEwMDIyIgNVU0EqCE5FVyBZT1JLMgJOWUAEYkEKC3N0YWtlaG9sZGVyEhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oB1QEKEWF1dG9tYXRlZC1wcm9jZXNzEhpDNUdaUlgtMjAyNC0wOS0xMS1QTlItVEstNBgFIhMyMDI0LTA5LTExVDAwOjAwOjAwKgsKCU5DRTFBMDk1NVpBCgtzdGFrZWhvbGRlchIaQzVHWlJYLTIwMjQtMDktMTEtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNiPQoHcHJvZHVjdBIbQzVHWlJYLTIwMjQtMDktMTEtUE5SLUFJUi0xGhVwcm9jZXNzZWRQbnIucHJvZHVjdHM=]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON KO="KO" validate="manual" matchMessage="Match failed with error code 1: Callback rejected:Match function exits on unspecified Error." compareAt="15:48:24.814910 - 11 Sep 2024"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001DPEGGJNICO]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2582]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;C5GZRX-2024-09-11&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;C5GZRX&quot;, &amp;
    &quot;version&quot;: &quot;1&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-11T13:48:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;, &amp;
                &quot;iataNumber&quot;: &quot;12345675&quot;, &amp;
                &quot;systemCode&quot;: &quot;1A&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;1APUB/ATL-0001AA/NCE1A0955&quot;&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-09-11T13:48:20Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0238&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;1APUB/ATL&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;BART&quot;, &amp;
                    &quot;lastName&quot;: &quot;SIMPSON&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AP-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-SSR-3&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610A23DD000081DF&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;FRA&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-13T07:35:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-13T08:35:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7040&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7040-2024-12-13-FRA-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600AC3DE00005E0B&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AP-2&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;+33600000666&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-SSR-3&quot;, &amp;
            &quot;address&quot;: \{&amp;
                &quot;category&quot;: &quot;DESTINATION&quot;, &amp;
                &quot;lines&quot;: [&amp;
                    &quot;301 PARK AVENUE&quot;&amp;
                ], &amp;
                &quot;postalCode&quot;: &quot;10022&quot;, &amp;
                &quot;countryCode&quot;: &quot;USA&quot;, &amp;
                &quot;cityName&quot;: &quot;NEW YORK&quot;, &amp;
                &quot;stateCode&quot;: &quot;NY&quot;&amp;
            \}, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;REGULATORY&quot;&amp;
            ], &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-TK-4&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-09-11T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;C5GZRX-2024-09-11-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="15" endLine="315" beginLine="314" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:24.816406 - 11 Sep 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[C5GZRX]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="15:48:25.237301 - 11 Sep 2024" filename="">--- RLR ---&amp;
RP/NCE1A0955/NCE1A0955            AA/SU  11SEP24/1348Z   C5GZRX&amp;
  1.SIMPSON/BART&amp;
  2  6X7040 Y 13DEC 5 FRALHR HK1  0735 0835  13DEC  E  6X/C5GZRX&amp;
  3 AP +33600000666&amp;
  4 TK OK11SEP/NCE1A0955&amp;
  5 SSR DOCA 6X HK1 D/USA/301 PARK AVENUE/NEW YORK/NY/10022&amp;
  6 OPC-11SEP:1550/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="16" endLine="316" beginLine="315" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:25.237657 - 11 Sep 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="15:48:25.494208 - 11 Sep 2024" filename="">--- RLR ---&amp;
RP/NCE1A0955/NCE1A0955            AA/SU  11SEP24/1348Z   C5GZRX&amp;
  1.SIMPSON/BART&amp;
  2 AP +33600000666&amp;
  3 TK OK11SEP/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="17" endLine="317" beginLine="316" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:25.494561 - 11 Sep 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="15:48:25.896782 - 11 Sep 2024" filename="">END OF TRANSACTION COMPLETE - C5GZRX&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="18" endLine="318" beginLine="317" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:25.896952 - 11 Sep 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="15:48:25.963775 - 11 Sep 2024" filename="">IGNORED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="19" endLine="323" beginLine="322" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:25.963971 - 11 Sep 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="15:48:26.083254 - 11 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="20" endLine="324" beginLine="323" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:26.083405 - 11 Sep 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="15:48:26.147885 - 11 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="21" endLine="332" beginLine="331" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><COMMENT> 6. Cancel the PNR and sign out</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:26.148010 - 11 Sep 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="15:48:26.194903 - 11 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="22" endLine="333" beginLine="332" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:26.195081 - 11 Sep 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="15:48:26.243694 - 11 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="23" endLine="334" beginLine="333" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:26.243870 - 11 Sep 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="15:48:26.291764 - 11 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="24" endLine="339" beginLine="338" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:26.291880 - 11 Sep 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="15:48:26.344158 - 11 Sep 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="25" endLine="340" beginLine="339" filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/LAST_REPO/open_pnr_validation/ORDER_10052_Support_SB_Out_Contacts/ORDER_10052_Support_SB_Out_Contacts/Scripts/SSR_DOCA/SSR_DOCA_Create_Feed.cry" loop="0" sentAt="15:48:26.344256 - 11 Sep 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="15:48:26.406731 - 11 Sep 2024" filename="">&amp;
********         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><STATISTIC><STATISTIC_ELEMENT name="Message in">27</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">20363</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">27</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">9013</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">27</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">25</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.925926</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">12375.4</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">1.869</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">7109.44</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">57</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">2</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">11</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">3</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">3</STATISTIC_ELEMENT></STATISTIC></xml>