<xml scenarioFilename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry"><SCRIPT type="Initialize">import json
from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.
def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;travelers&apos;, &apos;flightItinerary&apos;, &apos;products&apos;, &apos;contacts&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=&quot;NCE6X0100&quot;, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;flightItinerary&apos;]), expected=1, item_name=&apos;number of flightItinerary&apos;)
        flightItinerary_1 = openpnr[&apos;flightItinerary&apos;][0]

        #Check service data for flightItinerary section in output json
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;connectionType&apos;], expected=&quot;CONNECTION&quot;, item_name=&apos;flightItinerary/flights/connectionType&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][0][&apos;type&apos;], expected=&quot;product&quot;, item_name=&apos;flightItinerary/flights/flightSegments/type&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][0][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AIR-2&quot;, item_name=&apos;flightItinerary/flights/flightSegments/id&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][1][&apos;type&apos;], expected=&quot;product&quot;, item_name=&apos;flightItinerary/flights/flightSegments/type&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][1][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AIR-3&quot;, item_name=&apos;flightItinerary/flights/flightSegments/id&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][2][&apos;type&apos;], expected=&quot;product&quot;, item_name=&apos;flightItinerary/flights/flightSegments/type&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][2][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AIR-4&quot;, item_name=&apos;flightItinerary/flights/flightSegments/id&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-CNX-18&quot;, item_name=&apos;flightItinerary/flights/id&apos;)


    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="84" beginLine="83" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:26:58.476725 - 14 Nov 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="16:26:58.583099 - 14 Nov 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" responseEndLine="87" responseBeginLine="86" endLine="85" beginLine="84" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:26:58.586147 - 14 Nov 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><COMPARISON compareAt="16:26:58.661843 - 14 Nov 2024" match="OK"><TEXT><![CDATA[SIGN IN&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="3" endLine="89" beginLine="88" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:26:58.662374 - 14 Nov 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="16:26:58.748053 - 14 Nov 2024" filename="">&amp;
09CC2B44         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="96" beginLine="95" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:26:58.748615 - 14 Nov 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="16:26:58.823595 - 14 Nov 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="98" beginLine="97" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:00.833972 - 14 Nov 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0955]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="16:27:00.911209 - 14 Nov 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="102" responseBeginLine="102" endLine="100" beginLine="99" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:00.913252 - 14 Nov 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[GVxyuXx77768bg+-]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="16:27:01.101777 - 14 Nov 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/14NOV/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" endLine="110" beginLine="109" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><COMMENT> 2. Creation of the PNR</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:01.103005 - 14 Nov 2024"><TEXT><![CDATA[NM2SMITH/JANE/JOHNNY]]></TEXT></QUERY><REPLY receiveAt="16:27:01.261769 - 14 Nov 2024" filename="">RP/NCE6X0100/&amp;
  1.SMITH/JANE   2.SMITH/JOHNNY&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="8" endLine="111" beginLine="110" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:01.262393 - 14 Nov 2024"><TEXT><![CDATA[AN20FEBNCECDG]]></TEXT></QUERY><REPLY receiveAt="16:27:01.572383 - 14 Nov 2024" filename="">AN20FEBNCECDG&amp;
** AMADEUS SIX - AN ** CDG CHARLES DE GAUL.FR                 98 TH 20FEB 0000&amp;
 1   6X 121  J9 D9 I9 Y9          /NCE   CDG    0105    0300  E0/343       1:55&amp;
 2   6X 929  C9 D9 I9 U9 Y9       /NCE   CDG    0630    0800  E0/100       1:30&amp;
 3   6X 930  C9 D9 I9 U9 Y9       /NCE   CDG    0630    0800  E0/100       1:30&amp;
 4   6X 563  J9 D9 I9 U9 Y9       /NCE   CDG    0630    0800  E0/ERJ       1:30&amp;
 5   6X1781  J9 D9 I9 U9 Y9       /NCE   CDG    0800    0920  E0/744       1:20&amp;
 6   6X9481  F9 A9 Z9 J9 D9 I9 U9 /NCE   CDG    0800    0930  E0/744       1:30&amp;
             Y9&amp;
 7   6X8762  F9 A9 Z9 J9 D9 I9 U9 /NCE   CDG    0800    1100  E0/380       3:00&amp;
             Y9 B9 H9 K9 M9 L9 V9 N9 O9 S9 Q9 G9 X9 E9&amp;
 8   6X6030  C9 D9 I9 UL          /NCE   CDG    0900    1000  E0/321       1:00&amp;
 9   6X1782  J9 D9 I9 U9 Y9       /NCE   CDG    0900    1020  E0/744       1:20&amp;
10   6X1783  J9 D9 I9 U9 Y9       /NCE   CDG    0900    1020  E0/744       1:20&amp;
11   6X7725  J9 C9 D9 I9 U9 Y9 B9 /NCE   CDG    0930    1030  E0/ERJ       1:00&amp;
             M9 K9 H9 Q9 G9 E9&amp;
12   6X7824  J9 C9 D9 I9 U9 Y9 B9 /NCE   CDG    1000    1100  E0/319       1:00&amp;
             M9 K9 Q9 G9 E9&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="9" endLine="112" beginLine="111" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:01.572904 - 14 Nov 2024"><TEXT><![CDATA[SS2Y1]]></TEXT></QUERY><REPLY receiveAt="16:27:02.338937 - 14 Nov 2024" filename="">RP/NCE6X0100/&amp;
  1.SMITH/JANE   2.SMITH/JOHNNY&amp;
  3  6X 121 Y 20FEB 4 NCECDG DK2  0105 0300  20FEB  E  0 343&amp;
     SEE RTSVC&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="10" endLine="113" beginLine="112" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:02.339436 - 14 Nov 2024"><TEXT><![CDATA[AP TEST;RFTEST;TKOK]]></TEXT></QUERY><REPLY receiveAt="16:27:02.644208 - 14 Nov 2024" filename="">RP/NCE6X0100/&amp;
RF TEST&amp;
  1.SMITH/JANE   2.SMITH/JOHNNY&amp;
  3  6X 121 Y 20FEB 4 NCECDG DK2  0105 0300  20FEB  E  0 343&amp;
     SEE RTSVC&amp;
  4 AP TEST&amp;
  5 TK OK14NOV/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="11" endLine="114" beginLine="113" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:02.644838 - 14 Nov 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="16:27:03.215039 - 14 Nov 2024" filename="">--- RLR ---&amp;
RP/NCE6X0100/NCE6X0100            YG/SU  14NOV24/1527Z   7BR44F&amp;
  1.SMITH/JANE   2.SMITH/JOHNNY&amp;
  3  6X 121 Y 20FEB 4 NCECDG HK2  0105 0300  20FEB  E  6X/7BR44F&amp;
  4 AP TEST&amp;
  5 TK OK14NOV/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="12" endLine="117" beginLine="116" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:05.221927 - 14 Nov 2024"><TEXT><![CDATA[XE3]]></TEXT></QUERY><REPLY receiveAt="16:27:06.020151 - 14 Nov 2024" filename="">ITINERARY CANCELLED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="13" responseEndLine="126" responseBeginLine="122" endLine="118" beginLine="117" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:06.021031 - 14 Nov 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><COMPARISON compareAt="16:27:06.604808 - 14 Nov 2024" match="OK"><TEXT><![CDATA[RP/NCE6X0100/NCE6X0100            YG/SU  ]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/1527]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[7BR44F]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
  1.SMITH/JANE   2.SMITH/JOHNNY&amp;
  3 AP TEST&amp;
  4 TK OK]]></TEXT><VARIABLE name="today_ddmmm"><VALUE><![CDATA[14NOV]]></VALUE></VARIABLE><TEXT><![CDATA[/NCE6X0100&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14" responseEndLine="140" responseBeginLine="138" endLine="136" beginLine="132" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:09.689588 - 14 Nov 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="16:27:09.945606 - 14 Nov 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:7BR44F::141124:1527&apos;&amp;
RSI+RP:YGSU:NCE6X0100:00631002+NCE6X0100+NCE+NCE6X0100:1127YG:141124:00631002:1527&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
SEQ++4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[3]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2025:2:24&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+SMITH::1+JANE&apos;&amp;
ETI+:1+UN:Y:Y::SMITH:JANE&apos;&amp;
EMS++PT:2+NM+2&apos;&amp;
TIF+SMITH::1+JOHNNY&apos;&amp;
ETI+:1+UN:Y:Y::SMITH:JOHNNY&apos;&amp;
DUM&apos;&amp;
EMS++OT:3+AP+3&apos;&amp;
LFT+3:5+TEST&apos;&amp;
EMS++OT:4+TK+4&apos;&amp;
TKE++OK:141124::NCE6X0100]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14"><QUERY filename="" loop="0" sentAt="16:27:09.947370 - 14 Nov 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="15" responseEndLine="323" responseBeginLine="313" endLine="311" beginLine="150" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:10.016651 - 14 Nov 2024"><TEXT><![CDATA[PATCH /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[/elements HTTP/1.1&amp;
Content-Type: text/plain&amp;
Debug-Format: json&amp;
If-Match: ]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[3]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header"><VALUE><![CDATA[eyJub25jZSI6Ik1qRXlNRFF4T1RJM09UUXdPRFU0TkE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MjY6NTQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoib3NQd1kyQTRWNnZoWmRBN3J3b0tVL1N4aytBPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
[&amp;
    \{&amp;
        &quot;action&quot;: &quot;add&quot;,&amp;
        &quot;model&quot;: &quot;Product&quot;,&amp;
        &quot;element&quot;: \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;AIR-2&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T10:17:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T11:00:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;920&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;&amp;
                    \}&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-11-14]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \},&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-11-14]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-2&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    \},&amp;
    \{&amp;
        &quot;action&quot;: &quot;add&quot;,&amp;
        &quot;model&quot;: &quot;Product&quot;,&amp;
        &quot;element&quot;: \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;AIR-3&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T12:00:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;AMS&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T13:00:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;3902&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;&amp;
                    \}&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-11-14]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \},&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-11-14]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-2&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    \},&amp;
    \{&amp;
        &quot;action&quot;: &quot;add&quot;,&amp;
        &quot;model&quot;: &quot;Product&quot;,&amp;
        &quot;element&quot;: \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;AIR-4&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;AMS&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T14:25:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;TRD&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T16:40:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;KL&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;1153&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;&amp;
                    \}&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-11-14]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \},&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="today"><VALUE><![CDATA[2024-11-14]]></VALUE></VARIABLE><TEXT><![CDATA[-PNR-NM-2&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    \},&amp;
    \{&amp;
        &quot;action&quot;: &quot;add&quot;,&amp;
        &quot;model&quot;: &quot;FlightBound&quot;,&amp;
        &quot;element&quot;: \{&amp;
            &quot;flights&quot;: [&amp;
                \{&amp;
                    &quot;connectedFlights&quot;: \{&amp;
                        &quot;connectionType&quot;: &quot;CONNECTION&quot;,&amp;
                        &quot;flightSegments&quot;: [&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;AIR-2&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \},&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;AIR-3&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \},&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;AIR-4&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}&amp;
                        ]&amp;
                    \}&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    \}&amp;
]]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 9: A character does not match, expected &apos;2&apos;, received &apos;4&apos;." compareAt="16:27:11.138524 - 14 Nov 2024"><TEXT><![CDATA[HTTP/1.1 ]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[200 OK]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[400 Bad Request]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6K2XMY5LA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[202]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[etag:{*}&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[content-type:application/vnd.amadeus+json; charset=utf-8&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[con]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[tent-type:application/vnd.amadeus+json; charset=utf-8]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[nection:close]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[connection:close]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED></EXPECTED><RECEIVED><TEXT><![CDATA[\{]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[\{]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[    &quot;errors&quot;: []]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;reference&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;, &amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[    \{&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;version&quot;: &quot;{*}&quot;, &amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[        &quot;status&quot;: 400, &amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[    ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[        &quot;detail&quot;: &quot;Error at PNR Elements creation time&quot;, &amp;
            &quot;title&quot;: &quot;NOT AVAILABLE AND WAITLIST CLOSED&quot;, &amp;
            &quot;code&quot;: 5511, &amp;
            &quot;source&quot;: \{&amp;
                &quot;parameter&quot;: &quot;AIR-4&quot;, &amp;
                &quot;pointer&quot;: &quot;/openPnr/products/airSegment&quot;&amp;
            \}&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="16" responseEndLine="350" responseBeginLine="339" endLine="338" beginLine="334" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:11.143476 - 14 Nov 2024"><TEXT><![CDATA[GET /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[ HTTP/1.1&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header2"><VALUE><![CDATA[eyJub25jZSI6Ik5EZzNOVEExTWpnME5qQTNNamd4TWc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MjY6NTQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiR3JENTRyTURSblNOcUVCMDFGWjN1TlBaeGpZPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT></QUERY><COMPARISON compareAt="16:27:11.519825 - 14 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6K2ZMY5LB]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1169]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[ChE3QlI0NEYtMjAyNC0xMS0xNBIDcG5yGgY3QlI0NEYiATQ6VRoUMjAyNC0xMS0xNFQxNToyNzowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0xMS0xNFQxNToyNzoxMVp6iwEKC3N0YWtlaG9sZGVyEho3QlI0NEYtMjAyNC0xMS0xNC1QTlItTk0tMSINEgRKQU5FGgVTTUlUSHI8Cgdjb250YWN0Eho3QlI0NEYtMjAyNC0xMS0xNC1QTlItQVAtMxoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBODQxRTAwMDFEOUIweo0BCgtzdGFrZWhvbGRlchIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLU5NLTIiDxIGSk9ITk5ZGgVTTUlUSHI8Cgdjb250YWN0Eho3QlI0NEYtMjAyNC0xMS0xNC1QTlItQVAtMxoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBODQxRTAwMDFEOUIxsgG2AQoHY29udGFjdBIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLUFQLTNCAQFaBgoEVEVTVGJBCgtzdGFrZWhvbGRlchIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNiQQoLc3Rha2Vob2xkZXISGjdCUjQ0Ri0yMDI0LTExLTE0LVBOUi1OTS0yGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugHZAQoRYXV0b21hdGVkLXByb2Nlc3MSGjdCUjQ0Ri0yMDI0LTExLTE0LVBOUi1USy00GAUiEzIwMjQtMTEtMTRUMDA6MDA6MDAqCwoJTkNFNlgwMTAwWkEKC3N0YWtlaG9sZGVyEho3QlI0NEYtMjAyNC0xMS0xNC1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc1pBCgtzdGFrZWhvbGRlchIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLU5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnM=]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="17" responseEndLine="373" responseBeginLine="366" endLine="364" beginLine="360" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:11.522629 - 14 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header3"><VALUE><![CDATA[eyJub25jZSI6Ik5EVTNNRFF6TVRFME56Y3hORFkyTWc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MjY6NTQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiSTVmSUlSMUlxbzVUWk9yb1FJeXVtOHpQTVpNPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ChE3QlI0NEYtMjAyNC0xMS0xNBIDcG5yGgY3QlI0NEYiATQ6VRoUMjAyNC0xMS0xNFQxNToyNzowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0xMS0xNFQxNToyNzoxMVp6iwEKC3N0YWtlaG9sZGVyEho3QlI0NEYtMjAyNC0xMS0xNC1QTlItTk0tMSINEgRKQU5FGgVTTUlUSHI8Cgdjb250YWN0Eho3QlI0NEYtMjAyNC0xMS0xNC1QTlItQVAtMxoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBODQxRTAwMDFEOUIweo0BCgtzdGFrZWhvbGRlchIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLU5NLTIiDxIGSk9ITk5ZGgVTTUlUSHI8Cgdjb250YWN0Eho3QlI0NEYtMjAyNC0xMS0xNC1QTlItQVAtMxoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBODQxRTAwMDFEOUIxsgG2AQoHY29udGFjdBIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLUFQLTNCAQFaBgoEVEVTVGJBCgtzdGFrZWhvbGRlchIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNiQQoLc3Rha2Vob2xkZXISGjdCUjQ0Ri0yMDI0LTExLTE0LVBOUi1OTS0yGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugHZAQoRYXV0b21hdGVkLXByb2Nlc3MSGjdCUjQ0Ri0yMDI0LTExLTE0LVBOUi1USy00GAUiEzIwMjQtMTEtMTRUMDA6MDA6MDAqCwoJTkNFNlgwMTAwWkEKC3N0YWtlaG9sZGVyEho3QlI0NEYtMjAyNC0xMS0xNC1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc1pBCgtzdGFrZWhvbGRlchIaN0JSNDRGLTIwMjQtMTEtMTQtUE5SLU5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnM=]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON KO="KO" validate="manual" matchMessage="Match failed with error code 1: Callback rejected:Match function exits on unspecified Error." compareAt="16:27:11.810831 - 14 Nov 2024"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6K32MY5LB]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1564]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;7BR44F-2024-11-14&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;7BR44F&quot;, &amp;
    &quot;version&quot;: &quot;4&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-14T15:27:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-14T15:27:11Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JANE&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-AP-3&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610A841E0001D9B0&quot;&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-NM-2&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JOHNNY&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-AP-3&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610A841E0001D9B1&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-AP-3&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;TEST&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-NM-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-TK-4&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-11-14T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;7BR44F-2024-11-14-PNR-NM-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="18" responseEndLine="395" responseBeginLine="393" endLine="391" beginLine="387" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:11.812281 - 14 Nov 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="16:27:12.052380 - 14 Nov 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:7BR44F::141124:1527&apos;&amp;
RSI+RP:AASU:NCE6X0100:00631002+NCE6X0100+NCE+NCE6X0100:1127YG:141124:00631002:1527&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+:NCE1A07CE+A&apos;&amp;
SYS++1A:NCE&apos;&amp;
PRE+FR&apos;&amp;
SEQ++5]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2025:2:24&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+SMITH::1+JANE&apos;&amp;
ETI+:1+UN:Y:Y::SMITH:JANE&apos;&amp;
EMS++PT:2+NM+2&apos;&amp;
TIF+SMITH::1+JOHNNY&apos;&amp;
ETI+:1+UN:Y:Y::SMITH:JOHNNY&apos;&amp;
DUM&apos;&amp;
EMS++OT:3+AP+3&apos;&amp;
LFT+3:5+TEST&apos;&amp;
EMS++OT:4+TK+4&apos;&amp;
TKE++OK:141124::NCE6X0100]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="19" endLine="405" beginLine="404" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="N/A"><SCRIPT type="Exec">env_num = int (env_num)
env_num = env_num - 0
</SCRIPT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:12.053453 - 14 Nov 2024"><TEXT><![CDATA[UNH++::&apos;&amp;
print(env_num)]]></TEXT></QUERY><REPLY receiveAt="16:27:12.119314 - 14 Nov 2024" filename="">UNB+IATB:1+1AAPITES3+TESAPI3+241114:1527+01L2NF6QDC0002+00OX9VYSB30002++E&apos;&amp;
UNH+1+CONTRL:2:1:UN+09CC2B44&apos;&amp;
UCI+00OX9VYSB30002+TESAPI3+1AAPITES3+7&apos;&amp;
UCM+1+UNKMSG:XX:X:XX+4+17&apos;&amp;
UNT+4+1&apos;&amp;
UNZ+1+01L2NF6QDC0002&apos;</REPLY></TRANSACTION><TRANSACTION transactionCounter="19"><QUERY filename="" loop="0" sentAt="16:27:12.120064 - 14 Nov 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="20" responseEndLine="437" responseBeginLine="424" endLine="421" beginLine="415" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="looping"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:12.292298 - 14 Nov 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE1A0900++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 70: Missing character(s)" compareAt="16:27:13.305221 - 14 Nov 2024"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[::{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+{%backend%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{%message_id%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{%sdi_date2%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="20" responseEndLine="437" responseBeginLine="424" endLine="421" beginLine="415" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="1" sentAt="16:27:16.321021 - 14 Nov 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE1A0900++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 70: Missing character(s)" compareAt="16:27:16.725911 - 14 Nov 2024"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[7BR44F]]></VALUE></VARIABLE><TEXT><![CDATA[::{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+{%backend%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{%message_id%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{%sdi_date2%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="21" responseEndLine="457" responseBeginLine="451" endLine="450" beginLine="446" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Update/Multi_CNX_Update_Feed.cry" loop="0" sentAt="16:27:19.808176 - 14 Nov 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;P&apos;, received &apos;C&apos;." compareAt="16:27:19.879634 - 14 Nov 2024"><TEXT><![CDATA[UNH++]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[PUPIRR]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[CONTRL]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[14]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[2]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:1:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[1A]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UN]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{*}&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCI+008B6PZXMW0001+1ASI+NONE+7&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+SONPK{*}&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCM+1+PUPIRQ:14:1:1A+4+18&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[BLB+{*}+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C{%raw_binary%=(multi).*}UNT\x1D2\x1D1\x1C&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION></TRANSACTION><ERROR filename="" line="471" severity="Fatal Error">The variable &apos;global_regression.openpnr_payload&apos; is not defined</ERROR><STATISTIC><STATISTIC_ELEMENT name="Message in">24</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">10384</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">24</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">8585</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">9</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">24</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">22</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.916667</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">21415.6</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">3.204</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">8011.88</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">37</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">11</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">4</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">4</STATISTIC_ELEMENT></STATISTIC></xml>