<xml scenarioFilename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry"><SCRIPT type="Initialize">import json
from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.
def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;id&apos;, &apos;reference&apos;, &apos;creation&apos;, &apos;travelers&apos;, &apos;products&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc2 + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=test_user_1A_extended_office, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;associatedPnrs&apos;]), expected=1, item_name=&apos;number of associatedPnrs&apos;)
        associatedPnrs_1 = openpnr[&apos;associatedPnrs&apos;][0]

        assert_equal(actual=associatedPnrs_1[&apos;reference&apos;], expected=recloc, item_name=&apos;RLOC reference&apos;)
        assert_equal(actual=associatedPnrs_1[&apos;associationType&apos;], expected=&quot;SPLIT&quot;, item_name=&apos;associationType&apos;)
        assert_equal(actual=associatedPnrs_1[&apos;direction&apos;], expected=&quot;PARENT&quot;, item_name=&apos;direction&apos;)

    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="67" beginLine="66" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:53.266802 - 02 Jul 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="10:26:53.321744 - 02 Jul 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" endLine="68" beginLine="67" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:53.322288 - 02 Jul 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="10:26:53.376572 - 02 Jul 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="3" endLine="69" beginLine="68" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:53.376975 - 02 Jul 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="10:26:53.443546 - 02 Jul 2024" filename="">&amp;
09CC2B44         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="75" beginLine="74" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:53.443845 - 02 Jul 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="10:26:53.499797 - 02 Jul 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="77" beginLine="76" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:55.512275 - 02 Jul 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="10:26:55.571152 - 02 Jul 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="81" responseBeginLine="81" endLine="79" beginLine="78" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:55.572124 - 02 Jul 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[Yoanntesting123*]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="10:26:55.746817 - 02 Jul 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/02JUL/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" endLine="89" beginLine="88" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><COMMENT> 2.Create a PNR with 2pax 1seg + APM</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:55.748730 - 02 Jul 2024"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Pax1.book()}]]></EXPRESSION><VALUE><![CDATA[NM1AMTB/ASTI]]></VALUE></REGULAR_EXPRESSION></QUERY><REPLY receiveAt="10:26:55.850455 - 02 Jul 2024" filename="">RP/NCE6X0100/&amp;
  1.AMTB/ASTI&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="8" endLine="90" beginLine="89" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:55.851480 - 02 Jul 2024"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Pax2.book()}]]></EXPRESSION><VALUE><![CDATA[NM1ZJZU/QYJZ]]></VALUE></REGULAR_EXPRESSION></QUERY><REPLY receiveAt="10:26:55.951716 - 02 Jul 2024" filename="">RP/NCE6X0100/&amp;
  1.AMTB/ASTI   2.ZJZU/QYJZ&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="9" responseEndLine="95" responseBeginLine="93" endLine="91" beginLine="90" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:55.952534 - 02 Jul 2024"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_1.book(2)}]]></EXPRESSION><VALUE><![CDATA[SS6X402Y21AUGFRALHR2]]></VALUE></REGULAR_EXPRESSION></QUERY><COMPARISON compareAt="10:26:56.350055 - 02 Jul 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[  1.AMTB/ASTI   2.ZJZU/QYJZ&amp;
  3 ]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_1.pnr_format(&apos;&apos;)}]]></EXPRESSION><VALUE><![CDATA[6X 402 Y 21AUG 3 FRALHR ]]></VALUE></REGULAR_EXPRESSION><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[DK2  1000 1100  21AUG  E  0 320]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="10" endLine="98" beginLine="97" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:56.350659 - 02 Jul 2024"><TEXT><![CDATA[TKOK;APNCE;RFYG]]></TEXT></QUERY><REPLY receiveAt="10:26:56.547308 - 02 Jul 2024" filename="">RP/NCE6X0100/&amp;
RF YG&amp;
  1.AMTB/ASTI   2.ZJZU/QYJZ&amp;
  3  6X 402 Y 21AUG 3 FRALHR DK2  1000 1100  21AUG  E  0 320&amp;
  4 AP NCE&amp;
  5 TK OK02JUL/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="11" endLine="101" beginLine="100" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:56.547525 - 02 Jul 2024"><TEXT><![CDATA[sr fqtv 6x-6x1001234500/p1]]></TEXT></QUERY><REPLY receiveAt="10:26:56.720404 - 02 Jul 2024" filename="">RP/NCE6X0100/&amp;
RF YG&amp;
  1.AMTB/ASTI   2.ZJZU/QYJZ&amp;
  3  6X 402 Y 21AUG 3 FRALHR DK2  1000 1100  21AUG  E  0 320&amp;
  4 AP NCE&amp;
  5 TK OK02JUL/NCE6X0100&amp;
  6 SSR FQTV 6X HK/ 6X1001234500/P1&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="12" endLine="102" beginLine="101" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:56.720589 - 02 Jul 2024"><TEXT><![CDATA[sr fqtv 6x-6x1001234501/p2]]></TEXT></QUERY><REPLY receiveAt="10:26:56.904444 - 02 Jul 2024" filename="">RP/NCE6X0100/&amp;
RF YG&amp;
  1.AMTB/ASTI   2.ZJZU/QYJZ&amp;
  3  6X 402 Y 21AUG 3 FRALHR DK2  1000 1100  21AUG  E  0 320&amp;
  4 AP NCE&amp;
  5 TK OK02JUL/NCE6X0100&amp;
  6 SSR FQTV 6X HK/ 6X1001234500/P1&amp;
  7 SSR FQTV 6X HK/ 6X1001234501/P2&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="13" endLine="105" beginLine="104" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><COMMENT> End-transact &amp; check for completion</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:26:56.904807 - 02 Jul 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="10:26:57.485005 - 02 Jul 2024" filename="">--- RLR ---&amp;
RP/NCE6X0100/NCE6X0100            YG/SU   2JUL24/0826Z   9LV67Z&amp;
  1.AMTB/ASTI   2.ZJZU/QYJZ&amp;
  3  6X 402 Y 21AUG 3 FRALHR HK2  1000 1100  21AUG  E  6X/9LV67Z&amp;
  4 AP NCE&amp;
  5 TK OK02JUL/NCE6X0100&amp;
  6 SSR FQTV 6X HK/ 6X1001234500/P1&amp;
  7 SSR FQTV 6X HK/ 6X1001234501/P2&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="14" responseEndLine="112" responseBeginLine="110" endLine="108" beginLine="107" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:02.500310 - 02 Jul 2024"><TEXT><![CDATA[IR]]></TEXT></QUERY><COMPARISON compareAt="10:27:02.702077 - 02 Jul 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[            ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[AA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[ 2JUL24/0827]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[9LV67Z]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[  1.AMTB/ASTI   2.ZJZU/QYJZ&amp;
  3  6X 402 Y 21AUG 3 FRALHR HK2  1000 1100  21AUG  E  6X/9LV67Z&amp;
  4 AP NCE&amp;
  5 TK OK02JUL/NCE6X0100&amp;
  6 SSR FQTV 6X HK/ 6X1001234500/P1&amp;
  7 SSR FQTV 6X HK/ 6X1001234501/P2&amp;
  8 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S3/P1-2&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="15" responseEndLine="125" responseBeginLine="117" endLine="115" beginLine="114" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:02.704412 - 02 Jul 2024"><TEXT><![CDATA[SP1]]></TEXT></QUERY><COMPARISON compareAt="10:27:02.964569 - 02 Jul 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
-ASSOCIATE PNR-&amp;
RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[            ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[AA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[ 2JUL24/0827]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   XXXXXX&amp;
  1.]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[AMTB]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[ASTI]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
  2  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_1.pnr_format(&apos;&apos;)}]]></EXPRESSION><VALUE><![CDATA[6X 402 Y 21AUG 3 FRALHR ]]></VALUE></REGULAR_EXPRESSION><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[HK1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  1000 1100  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[21AUG]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  E  6X/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[9LV67Z]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  3 AP NCE&amp;
  4 TK ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[OK02JUL]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(local).*?SP}]]></EXPRESSION><VALUE><![CDATA[5 SSR FQTV 6X HK/ 6X1001234500&amp;
  6 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * SP]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[02JUL]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/YGSU/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[9LV67Z]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="16" responseEndLine="138" responseBeginLine="130" endLine="128" beginLine="127" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:02.966084 - 02 Jul 2024"><TEXT><![CDATA[EF]]></TEXT></QUERY><COMPARISON compareAt="10:27:03.183904 - 02 Jul 2024" match="OK"><TEXT><![CDATA[--- RLR ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION><TEXT><![CDATA[---&amp;
-PARENT PNR-&amp;
RP/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[            ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[AA]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[SU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[ 2JUL24/0827]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[9LV67Z]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  1.]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[ZJZU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[QYJZ]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
  2  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{=Flight_1.pnr_format(&apos;&apos;)}]]></EXPRESSION><VALUE><![CDATA[6X 402 Y 21AUG 3 FRALHR ]]></VALUE></REGULAR_EXPRESSION><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[HK1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  1000 1100  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[21AUG]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[  E  6X/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[9LV67Z]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  3 AP NCE&amp;
  4 TK ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[OK02JUL]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(local).*?SP}]]></EXPRESSION><VALUE><![CDATA[5 SSR FQTV 6X HK/ 6X1001234501&amp;
  6 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * SP]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[ ]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[02JUL]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[/YGSU/]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc2%=.{6}}]]></EXPRESSION><VALUE><![CDATA[9LV2HM]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="17" endLine="141" beginLine="140" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:03.184634 - 02 Jul 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="10:27:03.818092 - 02 Jul 2024" filename="">--- AXR RLR ---&amp;
RP/NCE6X0100/NCE6X0100            YG/SU   2JUL24/0827Z   9LV67Z&amp;
  1.ZJZU/QYJZ&amp;
  2  6X 402 Y 21AUG 3 FRALHR HK1  1000 1100  21AUG  E  6X/9LV67Z&amp;
  3 AP NCE&amp;
  4 TK OK02JUL/NCE6X0100&amp;
  5 SSR FQTV 6X HK/ 6X1001234501&amp;
  6 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * SP 02JUL/YGSU/NCE6X0100-9LV2HM&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="18" endLine="148" beginLine="147" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:08.832047 - 02 Jul 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[9LV2HM]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="10:27:09.080011 - 02 Jul 2024" filename="">--- AXR RLR ---&amp;
RP/NCE6X0100/NCE6X0100            AA/SU   2JUL24/0827Z   9LV2HM&amp;
  1.AMTB/ASTI&amp;
  2  6X 402 Y 21AUG 3 FRALHR HK1  1000 1100  21AUG  E  6X/9LV2HM&amp;
  3 AP NCE&amp;
  4 TK OK02JUL/NCE6X0100&amp;
  5 SSR FQTV 6X HK/ 6X1001234500&amp;
  6 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * SP 02JUL/YGSU/NCE6X0100-9LV67Z&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="19" endLine="149" beginLine="148" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:09.080423 - 02 Jul 2024"><TEXT><![CDATA[SP2]]></TEXT></QUERY><REPLY receiveAt="10:27:09.175981 - 02 Jul 2024" filename="">UNABLE TO SPLIT PARTY OF 1&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="20" endLine="152" beginLine="151" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:11.179885 - 02 Jul 2024"><TEXT><![CDATA[XE5]]></TEXT></QUERY><REPLY receiveAt="10:27:11.356165 - 02 Jul 2024" filename="">--- AXR RLR ---&amp;
RP/NCE6X0100/NCE6X0100            AA/SU   2JUL24/0827Z   9LV2HM&amp;
  1.AMTB/ASTI&amp;
  2  6X 402 Y 21AUG 3 FRALHR HK1  1000 1100  21AUG  E  6X/9LV2HM&amp;
  3 AP NCE&amp;
  4 TK OK02JUL/NCE6X0100&amp;
  5 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * SP 02JUL/YGSU/NCE6X0100-9LV67Z&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="21" endLine="153" beginLine="152" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:11.356890 - 02 Jul 2024"><TEXT><![CDATA[RFTEST]]></TEXT></QUERY><REPLY receiveAt="10:27:11.488241 - 02 Jul 2024" filename="">--- AXR RLR ---&amp;
RP/NCE6X0100/NCE6X0100            AA/SU   2JUL24/0827Z   9LV2HM&amp;
RF TEST&amp;
  1.AMTB/ASTI&amp;
  2  6X 402 Y 21AUG 3 FRALHR HK1  1000 1100  21AUG  E  6X/9LV2HM&amp;
  3 AP NCE&amp;
  4 TK OK02JUL/NCE6X0100&amp;
  5 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * SP 02JUL/YGSU/NCE6X0100-9LV67Z&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="22" endLine="154" beginLine="153" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:11.489021 - 02 Jul 2024"><TEXT><![CDATA[ER]]></TEXT></QUERY><REPLY receiveAt="10:27:11.960685 - 02 Jul 2024" filename="">--- AXR RLR ---&amp;
RP/NCE6X0100/NCE6X0100            YG/SU   2JUL24/0827Z   9LV2HM&amp;
  1.AMTB/ASTI&amp;
  2  6X 402 Y 21AUG 3 FRALHR HK1  1000 1100  21AUG  E  6X/9LV2HM&amp;
  3 AP NCE&amp;
  4 TK OK02JUL/NCE6X0100&amp;
  5 OPC-20AUG:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2&amp;
  * SP 02JUL/YGSU/NCE6X0100-9LV67Z&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="23" responseEndLine="171" responseBeginLine="169" endLine="167" beginLine="163" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:12.013845 - 02 Jul 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[SU&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[9LV67Z]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="10:27:12.303185 - 02 Jul 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:9LV67Z::020724:0827&apos;&amp;
RSI+RP:YGSU:NCE6X0100:00631002+NCE6X0100+NCE+NCE6X0100:0447YG:020724:00631002:0826&apos;&amp;
LFT+3:P12+--- AXR RLR ---&apos;&amp;
STX+AXR*RLR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
SEQ++4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[3]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2024:8:25&apos;&amp;
EMS++PT:2+NM+1&apos;&amp;
TIF+ZJZU::1+QYJZ&apos;&amp;
ETI+:1+UN:Y:Y::ZJZU:QYJZ&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+210824:1000:210824:1100+FRA+LHR+6X+402:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+6X:9LV67Z&apos;&amp;
RPI+1+HK&apos;&amp;
APD+320:0:0200::3+++407:M&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
FSD&apos;&amp;
TVL+210824:1000:210824:1100+FRA+LHR&apos;&amp;
IFT+ACO+AIRCRAFT OWNER AMADEUS SIX&apos;&amp;
DUM&apos;&amp;
DUM&apos;&amp;
EMS++OT:4+AP+3&apos;&amp;
LFT+3:5+NCE&apos;&amp;
EMS++OT:3+TK+4&apos;&amp;
TKE++OK:020724::NCE6X0100&apos;&amp;
EMS++OT:6+SSR+5&apos;&amp;
SSR+FQTV:HK:1:6X&apos;&amp;
FTI+6X:1001234501&apos;&amp;
REF+PT:2&apos;&amp;
EMS++OT:10+OPC+6&apos;&amp;
OPE+NCE6X0100:200824:1:8:6X CANCELLATION DUE TO NO TICKET NCE TIME ZONE::2300&apos;&amp;
REF+ST:1*PT:2&apos;&amp;
EMS+++SP&apos;&amp;
RCI+1A:9LV2HM:S:020724&apos;&amp;
RSI+SP:YGSU:NCE6X0100]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="24" responseEndLine="185" responseBeginLine="183" endLine="181" beginLine="177" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><COMMENT> Catch the correct envelope number of parent PNR</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:12.304425 - 02 Jul 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[SU&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[9LV2HM]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="10:27:12.555573 - 02 Jul 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:9LV2HM::020724:0827&apos;&amp;
RSI+RP:YGSU:NCE6X0100:00631002+NCE6X0100+NCE+NCE6X0100:0447YG:020724:00631002:0827&apos;&amp;
LFT+3:P12+--- AXR RLR ---&apos;&amp;
STX+AXR*RLR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+00631002:NCE6X0100+A&apos;&amp;
SYS++6X:NCE&apos;&amp;
PRE+FR&apos;&amp;
SEQ++3]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num2%=.{1}}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2024:8:25&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+AMTB::1+ASTI&apos;&amp;
ETI+:1+UN:Y:Y::AMTB:ASTI&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+210824:1000:210824:1100+FRA+LHR+6X+402:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+6X:9LV2HM&apos;&amp;
RPI+1+HK&apos;&amp;
APD+320:0:0200::3+++407:M&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
FSD&apos;&amp;
TVL+210824:1000:210824:1100+FRA+LHR&apos;&amp;
IFT+ACO+AIRCRAFT OWNER AMADEUS SIX&apos;&amp;
DUM&apos;&amp;
DUM&apos;&amp;
EMS++OT:4+AP+3&apos;&amp;
LFT+3:5+NCE&apos;&amp;
EMS++OT:3+TK+4&apos;&amp;
TKE++OK:020724::NCE6X0100&apos;&amp;
EMS++OT:10+OPC+5&apos;&amp;
OPE+NCE6X0100:200824:1:8:6X CANCELLATION DUE TO NO TICKET NCE TIME ZONE::2300&apos;&amp;
REF+ST:1*PT:1&apos;&amp;
EMS+++SP&apos;&amp;
RCI+1A:9LV67Z:P:020724&apos;&amp;
RSI+SP:YGSU:NCE6X0100]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="24"><QUERY filename="" loop="0" sentAt="10:27:12.557121 - 02 Jul 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="25" responseEndLine="216" responseBeginLine="203" endLine="201" beginLine="195" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:12.689416 - 02 Jul 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[++++FR:EUR:FR+A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[0447YG]]></VALUE></VARIABLE><TEXT><![CDATA[SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[9LV2HM]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[02JUL24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON compareAt="10:27:12.780351 - 02 Jul 2024" match="OK"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[9LV2HM]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[02JUL24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc2"><VALUE><![CDATA[9LV2HM]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[20240702\:08\:27\:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%backend%=*}]]></EXPRESSION><VALUE><![CDATA[SONPK4]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num2"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:07:02:08:27:12]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%message_id%=*}]]></EXPRESSION><VALUE><![CDATA[4472472336]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%sdi_date2%=*}]]></EXPRESSION><VALUE><![CDATA[2024:07:02:08:27:12]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="26" responseEndLine="236" responseBeginLine="230" endLine="229" beginLine="225" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:12.845596 - 02 Jul 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[4472472336]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[SONPK4]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[2024:07:02:08:27:12]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="10:27:12.934839 - 02 Jul 2024" match="OK"><TEXT><![CDATA[UNH++PUPIRR:14:1:1A+&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[4472472336]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+SONPK4&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:07:02:08:27:12]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
BLB+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1449]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%raw_binary%=(multi).*}]]></EXPRESSION><VALUE><![CDATA[\x0A\x89\x0B\x12\xAC\x0A\x0A\x119LV2HM-2024-07-02\x12\x03pnr\x1A\x069LV2HM&quot;\x012:h\x1A\x142024-07-02T08:27:00Z&quot;=\x0A&quot;\x0A\x09NCE6X0100\x12\x0800631002\x1A\x026X&quot;\x07AIRLINE\x12\x17\x0A\x040447\x12\x02YG\x1A\x02SU*\x02FR2\x03NCE*\x11TEST-1A/YOANNTESTJ\xAC\x02\x1A\x142024-07-02T08:27:11Z&quot;\x0D\x0A\x0B\x0A\x09NCE6X0100*\x04TEST:\xB1\x01\x12\x0FentityChangeLogB\x9D\x01\x92\x01\x99\x01\x0A\x07service\x12\x1B9LV2HM-2024-07-02-PNR-SSR-5\x1A\x04FQTV \x01*\x04\x0A\x026X2\x02HKZ\x1C\x0A\x0A1001234500\x10\x01\x1A\x04*\x026X&quot;\x04*\x02*O(\x00rA\x0A\x0Bstakeholder\x12\x1A9LV2HM-2024-07-02-PNR-NM-1\x1A\x16processedPnr.travelers:K\x12\x10historyChangeLog\x18\x02&quot;\x1B9LV2HM-2024-07-02-PNR-SSR-5*\x07service2\x0FloyaltyRequestsrH\x0A\x069LV67Z\x10\x02\x18\x02&quot;\x1D\x1A\x132024-07-02T00:00:00&quot;\x06\x0A\x04\x1A\x021A2\x1B9LV2HM-2024-07-02-PNR-SP-12z\x8A\x01\x0A\x0Bstakeholder\x12\x1A9LV2HM-2024-07-02-PNR-NM-1&quot;\x0C\x12\x04ASTI\x1A\x04AMTBr&lt;\x0A\x07contact\x12\x1A9LV2HM-2024-07-02-PNR-AP-4\x1A\x15processedPnr.contacts\xA2\x01\x12\x12\x106107539600007A75\x82\x01\xC8\x02\x0A\x07product\x10\x01\x1A\x1B9LV2HM-2024-07-02-PNR-AIR-1&quot;\x9D\x02\x0A\x1A\x0A\x03FRA\x1A\x132024-08-21T10:00:00\x12\x1A\x0A\x03LHR\x1A\x132024-08-21T11:00:00&quot;O\x0A\x09\x0A\x026X\x12\x03402\x12&apos;&amp;
\x0A\x01Y\x12\x03\x0A\x01M\x1A\x14\x0A\x02\x08\x00\x12\x0C\x0A\x04\x1A\x026X\x12\x04*\x02FR \x01&quot;\x07ECONOMY2\x196X-402-2024-08-21-FRA-LHRJ\x02HKb\x84\x01\x0A\x10segment-delivery\x12\x1B9LV2HM-2024-07-02-PNR-BKG-1\x1A\x106008039600060FFBZA\x0A\x0Bstakeholder\x12\x1A9LV2HM-2024-07-02-PNR-NM-1\x1A\x16processedPnr.travelers\x8A\x01\x01E\x92\x01\x02\x08\x00\xB2\x01q\x0A\x07contact\x12\x1A9LV2HM-2024-07-02-PNR-AP-4@\x01Z\x05\x0A\x03NCEbA\x0A\x0Bstakeholder\x12\x1A9LV2HM-2024-07-02-PNR-NM-1\x1A\x16processedPnr.travelers\xBA\x01\xD5\x01\x0A\x11automated-process\x12\x1A9LV2HM-2024-07-02-PNR-TK-3\x18\x05&quot;\x132024-07-02T00:00:00*\x0B\x0A\x09NCE6X0100ZA\x0A\x0Bstakeholder\x12\x1A9LV2HM-2024-07-02-PNR-NM-1\x1A\x16processedPnr.travelersb=\x0A\x07product\x12\x1B9LV2HM-2024-07-02-PNR-AIR-1\x1A\x15processedPnr.products\x1AX\x0A\x1Fapplication/vnd.google.protobuf\x12\x069LV2HM\x1A\x012&quot;\x03Pnr*\%com.amadeus.models.reservation.pnr.v2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[UNT\x1D2\x1D1\x1C&apos;&amp;
&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="27" responseEndLine="260" responseBeginLine="254" endLine="252" beginLine="247" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:12.938750 - 02 Jul 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header_airline"><VALUE><![CDATA[eyJub25jZSI6Ik5ESXhNakl4TWpJNU5qRXhPREE1Tnc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMDctMDJUMDg6MjY6NDkuMDAwWiIsInVzZXJJZCI6IkNPVEVTVFVTRVIiLCJvZmZpY2VJZCI6IlNZRDZYMDEwMiIsIm9yZ2FuaXphdGlvbiI6IjZYIiwicGFzc3dvcmQiOiJ0d0UzZmFtd2pxU3NJRXF3QzkzMDZJNkRJYk09In0=]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="global_regression.openpnr_payload"><VALUE><![CDATA[ChE5TFYySE0tMjAyNC0wNy0wMhIDcG5yGgY5TFYySE0iATI6aBoUMjAyNC0wNy0wMlQwODoyNzowMFoiPQoiCglOQ0U2WDAxMDASCDAwNjMxMDAyGgI2WCIHQUlSTElORRIXCgQwNDQ3EgJZRxoCU1UqAkZSMgNOQ0UqEVRFU1QtMUEvWU9BTk5URVNUSqwCGhQyMDI0LTA3LTAyVDA4OjI3OjExWiINCgsKCU5DRTZYMDEwMCoEVEVTVDqxARIPZW50aXR5Q2hhbmdlTG9nQp0BkgGZAQoHc2VydmljZRIbOUxWMkhNLTIwMjQtMDctMDItUE5SLVNTUi01GgRGUVRWIAEqBAoCNlgyAkhLWhwKCjEwMDEyMzQ1MDAQARoEKgI2WCIEKgIqTygAckEKC3N0YWtlaG9sZGVyEho5TFYySE0tMjAyNC0wNy0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyczpLEhBoaXN0b3J5Q2hhbmdlTG9nGAIiGzlMVjJITS0yMDI0LTA3LTAyLVBOUi1TU1ItNSoHc2VydmljZTIPbG95YWx0eVJlcXVlc3RzckgKBjlMVjY3WhACGAIiHRoTMjAyNC0wNy0wMlQwMDowMDowMCIGCgQaAjFBMhs5TFYySE0tMjAyNC0wNy0wMi1QTlItU1AtMTJ6igEKC3N0YWtlaG9sZGVyEho5TFYySE0tMjAyNC0wNy0wMi1QTlItTk0tMSIMEgRBU1RJGgRBTVRCcjwKB2NvbnRhY3QSGjlMVjJITS0yMDI0LTA3LTAyLVBOUi1BUC00GhVwcm9jZXNzZWRQbnIuY29udGFjdHOiARISEDYxMDc1Mzk2MDAwMDdBNzWCAcgCCgdwcm9kdWN0EAEaGzlMVjJITS0yMDI0LTA3LTAyLVBOUi1BSVItMSKdAgoaCgNGUkEaEzIwMjQtMDgtMjFUMTA6MDA6MDASGgoDTEhSGhMyMDI0LTA4LTIxVDExOjAwOjAwIk8KCQoCNlgSAzQwMhInCgFZEgMKAU0aFAoCCAASDAoEGgI2WBIEKgJGUiABIgdFQ09OT01ZMhk2WC00MDItMjAyNC0wOC0yMS1GUkEtTEhSSgJIS2KEAQoQc2VnbWVudC1kZWxpdmVyeRIbOUxWMkhNLTIwMjQtMDctMDItUE5SLUJLRy0xGhA2MDA4MDM5NjAwMDYwRkZCWkEKC3N0YWtlaG9sZGVyEho5TFYySE0tMjAyNC0wNy0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQIIALIBcQoHY29udGFjdBIaOUxWMkhNLTIwMjQtMDctMDItUE5SLUFQLTRAAVoFCgNOQ0ViQQoLc3Rha2Vob2xkZXISGjlMVjJITS0yMDI0LTA3LTAyLVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugHVAQoRYXV0b21hdGVkLXByb2Nlc3MSGjlMVjJITS0yMDI0LTA3LTAyLVBOUi1USy0zGAUiEzIwMjQtMDctMDJUMDA6MDA6MDAqCwoJTkNFNlgwMTAwWkEKC3N0YWtlaG9sZGVyEho5TFYySE0tMjAyNC0wNy0wMi1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2I9Cgdwcm9kdWN0Ehs5TFYySE0tMjAyNC0wNy0wMi1QTlItQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0cw==]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="10:27:13.118975 - 02 Jul 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001LC783FZM5D]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2979]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:1&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;9LV2HM-2024-07-02&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;9LV2HM&quot;, &amp;
    &quot;version&quot;: &quot;2&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-07-02T08:27:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;, &amp;
                &quot;iataNumber&quot;: &quot;00631002&quot;, &amp;
                &quot;systemCode&quot;: &quot;6X&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;0447&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;TEST-1A/YOANNTEST&quot;&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-07-02T08:27:11Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;TEST&quot;, &amp;
        &quot;changeLog&quot;: [&amp;
            \{&amp;
                &quot;logType&quot;: &quot;entityChangeLog&quot;, &amp;
                &quot;oldEntity&quot;: \{&amp;
                    &quot;loyaltyRequests&quot;: [&amp;
                        \{&amp;
                            &quot;type&quot;: &quot;service&quot;, &amp;
                            &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-SSR-5&quot;, &amp;
                            &quot;code&quot;: &quot;FQTV&quot;, &amp;
                            &quot;subType&quot;: &quot;SPECIAL_SERVICE_REQUEST&quot;, &amp;
                            &quot;serviceProvider&quot;: \{&amp;
                                &quot;code&quot;: &quot;6X&quot;&amp;
                            \}, &amp;
                            &quot;status&quot;: &quot;HK&quot;, &amp;
                            &quot;membership&quot;: \{&amp;
                                &quot;id&quot;: &quot;1001234500&quot;, &amp;
                                &quot;membershipType&quot;: &quot;INDIVIDUAL&quot;, &amp;
                                &quot;activeTier&quot;: \{&amp;
                                    &quot;companyCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;allianceTier&quot;: \{&amp;
                                    &quot;companyCode&quot;: &quot;*O&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;travelers&quot;: [&amp;
                                \{&amp;
                                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                                    &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-NM-1&quot;, &amp;
                                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                                \}&amp;
                            ]&amp;
                        \}&amp;
                    ]&amp;
                \}&amp;
            \}, &amp;
            \{&amp;
                &quot;logType&quot;: &quot;historyChangeLog&quot;, &amp;
                &quot;operation&quot;: &quot;REMOVE&quot;, &amp;
                &quot;elementId&quot;: &quot;9LV2HM-2024-07-02-PNR-SSR-5&quot;, &amp;
                &quot;elementType&quot;: &quot;service&quot;, &amp;
                &quot;path&quot;: &quot;loyaltyRequests&quot;&amp;
            \}&amp;
        ]&amp;
    \}, &amp;
    &quot;associatedPnrs&quot;: [&amp;
        \{&amp;
            &quot;reference&quot;: &quot;9LV67Z&quot;, &amp;
            &quot;associationType&quot;: &quot;SPLIT&quot;, &amp;
            &quot;direction&quot;: &quot;PARENT&quot;, &amp;
            &quot;creation&quot;: \{&amp;
                &quot;dateTime&quot;: &quot;2024-07-02T00:00:00&quot;, &amp;
                &quot;pointOfSale&quot;: \{&amp;
                    &quot;office&quot;: \{&amp;
                        &quot;systemCode&quot;: &quot;1A&quot;&amp;
                    \}&amp;
                \}&amp;
            \}, &amp;
            &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-SP-12&quot;&amp;
        \}&amp;
    ], &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;ASTI&quot;, &amp;
                    &quot;lastName&quot;: &quot;AMTB&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-AP-4&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;6107539600007A75&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;FRA&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-08-21T10:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-08-21T11:00:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;402&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;M&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-402-2024-08-21-FRA-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;6008039600060FFB&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-AP-4&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;NCE&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-TK-3&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-07-02T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE6X0100&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;9LV2HM-2024-07-02-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="28" endLine="273" beginLine="272" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:13.120660 - 02 Jul 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="10:27:13.581417 - 02 Jul 2024" filename="">--- AXR RLR ---&amp;
RP/NCE6X0100/NCE6X0100            YG/SU   2JUL24/0827Z   9LV2HM&amp;
  1.AMTB/ASTI&amp;
  2 AP NCE&amp;
  3 TK OK02JUL/NCE6X0100&amp;
  * SP 02JUL/YGSU/NCE6X0100-9LV67Z&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="29" endLine="274" beginLine="273" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:13.582087 - 02 Jul 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="10:27:13.985866 - 02 Jul 2024" filename="">END OF TRANSACTION COMPLETE - 9LV2HM&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="30" endLine="275" beginLine="274" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:13.986410 - 02 Jul 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="10:27:14.058761 - 02 Jul 2024" filename="">IGNORED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="31" endLine="278" beginLine="277" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:14.059525 - 02 Jul 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="10:27:14.193877 - 02 Jul 2024" filename="">&amp;
09CC2B44         NCE1A0950&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="32" endLine="279" beginLine="278" filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare(RM_concealment)/Epic_DATALMP_11405_Additional_OpenPNR_fields_for_Order_Codeshare/Scripts/Earlybird/Elements/06_Remove_SSR_FQTV_split_parent_Feed.cry" loop="0" sentAt="10:27:14.194274 - 02 Jul 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="10:27:14.264645 - 02 Jul 2024" filename="">&amp;
09CC2B44         NCE1A0950&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><STATISTIC><STATISTIC_ELEMENT name="Message in">33</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">16986</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">33</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">3337</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">7</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">33</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">32</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.969697</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">20999.2</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">2.621</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">6650.66</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">31</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">10</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">0</STATISTIC_ELEMENT></STATISTIC></xml>