# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lib/document_envelopes.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lib/document_envelopes.proto',
  package='pub.grammar.protoBuf.opendatamultipayload',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x1clib/document_envelopes.proto\x12)pub.grammar.protoBuf.opendatamultipayload\"\xf3\x03\n\x11\x44ocumentEnvelopes\x12`\n\tenvelopes\x18\x01 \x03(\x0b\x32M.pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelope\x1a\xb1\x01\n\x10\x44ocumentEnvelope\x12\x11\n\x07payload\x18\x01 \x01(\tH\x00\x12\x18\n\x0e\x62inary_payload\x18\x02 \x01(\x0cH\x00\x12g\n\x08metadata\x18\x03 \x01(\x0b\x32U.pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadataB\x07\n\x05value\x1a\xc7\x01\n\x18\x44ocumentEnvelopeMetadata\x12\x19\n\x11iana_content_type\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\t\x12\x14\n\x0cgrammar_name\x18\x04 \x01(\t\x12\x16\n\x0egrammar_domain\x18\x05 \x01(\t\x12\x17\n\x0fgrammar_version\x18\x06 \x01(\t\x12\x10\n\x08\x65ncoding\x18\x07 \x01(\t\x12\x18\n\x10\x63ompression_type\x18\x08 \x01(\t')
)




_DOCUMENTENVELOPES_DOCUMENTENVELOPE = _descriptor.Descriptor(
  name='DocumentEnvelope',
  full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelope.payload', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='binary_payload', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelope.binary_payload', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='metadata', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelope.metadata', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelope.value',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=196,
  serialized_end=373,
)

_DOCUMENTENVELOPES_DOCUMENTENVELOPEMETADATA = _descriptor.Descriptor(
  name='DocumentEnvelopeMetadata',
  full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iana_content_type', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.iana_content_type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.version', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grammar_name', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.grammar_name', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grammar_domain', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.grammar_domain', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='grammar_version', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.grammar_version', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='encoding', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.encoding', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='compression_type', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata.compression_type', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=376,
  serialized_end=575,
)

_DOCUMENTENVELOPES = _descriptor.Descriptor(
  name='DocumentEnvelopes',
  full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='envelopes', full_name='pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.envelopes', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DOCUMENTENVELOPES_DOCUMENTENVELOPE, _DOCUMENTENVELOPES_DOCUMENTENVELOPEMETADATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=575,
)

_DOCUMENTENVELOPES_DOCUMENTENVELOPE.fields_by_name['metadata'].message_type = _DOCUMENTENVELOPES_DOCUMENTENVELOPEMETADATA
_DOCUMENTENVELOPES_DOCUMENTENVELOPE.containing_type = _DOCUMENTENVELOPES
_DOCUMENTENVELOPES_DOCUMENTENVELOPE.oneofs_by_name['value'].fields.append(
  _DOCUMENTENVELOPES_DOCUMENTENVELOPE.fields_by_name['payload'])
_DOCUMENTENVELOPES_DOCUMENTENVELOPE.fields_by_name['payload'].containing_oneof = _DOCUMENTENVELOPES_DOCUMENTENVELOPE.oneofs_by_name['value']
_DOCUMENTENVELOPES_DOCUMENTENVELOPE.oneofs_by_name['value'].fields.append(
  _DOCUMENTENVELOPES_DOCUMENTENVELOPE.fields_by_name['binary_payload'])
_DOCUMENTENVELOPES_DOCUMENTENVELOPE.fields_by_name['binary_payload'].containing_oneof = _DOCUMENTENVELOPES_DOCUMENTENVELOPE.oneofs_by_name['value']
_DOCUMENTENVELOPES_DOCUMENTENVELOPEMETADATA.containing_type = _DOCUMENTENVELOPES
_DOCUMENTENVELOPES.fields_by_name['envelopes'].message_type = _DOCUMENTENVELOPES_DOCUMENTENVELOPE
DESCRIPTOR.message_types_by_name['DocumentEnvelopes'] = _DOCUMENTENVELOPES
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DocumentEnvelopes = _reflection.GeneratedProtocolMessageType('DocumentEnvelopes', (_message.Message,), dict(

  DocumentEnvelope = _reflection.GeneratedProtocolMessageType('DocumentEnvelope', (_message.Message,), dict(
    DESCRIPTOR = _DOCUMENTENVELOPES_DOCUMENTENVELOPE,
    __module__ = 'lib.document_envelopes_pb2'
    # @@protoc_insertion_point(class_scope:pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelope)
    ))
  ,

  DocumentEnvelopeMetadata = _reflection.GeneratedProtocolMessageType('DocumentEnvelopeMetadata', (_message.Message,), dict(
    DESCRIPTOR = _DOCUMENTENVELOPES_DOCUMENTENVELOPEMETADATA,
    __module__ = 'lib.document_envelopes_pb2'
    # @@protoc_insertion_point(class_scope:pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes.DocumentEnvelopeMetadata)
    ))
  ,
  DESCRIPTOR = _DOCUMENTENVELOPES,
  __module__ = 'lib.document_envelopes_pb2'
  # @@protoc_insertion_point(class_scope:pub.grammar.protoBuf.opendatamultipayload.DocumentEnvelopes)
  ))
_sym_db.RegisterMessage(DocumentEnvelopes)
_sym_db.RegisterMessage(DocumentEnvelopes.DocumentEnvelope)
_sym_db.RegisterMessage(DocumentEnvelopes.DocumentEnvelopeMetadata)


# @@protoc_insertion_point(module_scope)
