<xml scenarioFilename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry"><SCRIPT type="Initialize">import json
from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.
def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;reference&apos;, &apos;creation&apos;, &apos;travelers&apos;, &apos;flightItinerary&apos;, &apos;products&apos;, &apos;contacts&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=&quot;NCE1A0955&quot;, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;flightItinerary&apos;]), expected=1, item_name=&apos;number of flightItinerary&apos;)
        flightItinerary_1 = openpnr[&apos;flightItinerary&apos;][0]

        #Check service data for flightItinerary section in output json
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;connectionType&apos;], expected=&quot;CONNECTION&quot;, item_name=&apos;flightItinerary/flights/connectionType&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][0][&apos;type&apos;], expected=&quot;product&quot;, item_name=&apos;flightItinerary/flights/flightSegments/type&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][0][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AIR-1&quot;, item_name=&apos;flightItinerary/flights/flightSegments/id&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][1][&apos;type&apos;], expected=&quot;product&quot;, item_name=&apos;flightItinerary/flights/flightSegments/type&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][1][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AIR-2&quot;, item_name=&apos;flightItinerary/flights/flightSegments/id&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-CNX-7&quot;, item_name=&apos;flightItinerary/flights/id&apos;)


    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="82" beginLine="81" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:38.807627 - 14 Nov 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="16:10:38.923110 - 14 Nov 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" responseEndLine="85" responseBeginLine="84" endLine="83" beginLine="82" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:38.924600 - 14 Nov 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><COMPARISON compareAt="16:10:38.999614 - 14 Nov 2024" match="OK"><TEXT><![CDATA[SIGN IN&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="3" endLine="87" beginLine="86" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:38.999743 - 14 Nov 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="16:10:39.086535 - 14 Nov 2024" filename="">&amp;
09CC2B44         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="94" beginLine="93" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:39.087252 - 14 Nov 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="16:10:39.163967 - 14 Nov 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="96" beginLine="95" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:41.171568 - 14 Nov 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0955]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="16:10:41.246493 - 14 Nov 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="100" responseBeginLine="100" endLine="98" beginLine="97" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:41.246727 - 14 Nov 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[GVxyuXx77768bg+-]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="16:10:41.420443 - 14 Nov 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/14NOV/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" responseEndLine="125" responseBeginLine="116" endLine="114" beginLine="109" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:41.424052 - 14 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=json\&amp;output=protobufBase64 HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header"><VALUE><![CDATA[eyJub25jZSI6Ik9EZzNOVGM0TlRRMk5ERXhPVGd6Tnc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MTA6MzQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoidUZ0S1M1SU53LzhJU1dQdm1vSEFBUUR3WU5zPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT><VARIABLE name="input_json_multi_connected_flights"><VALUE><![CDATA[&amp;
\{&amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-10-09T14:13:28Z&quot;&amp;
    \},&amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
            &quot;id&quot;: &quot;NM-1&quot;,&amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JANE&quot;,&amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;,&amp;
                    &quot;id&quot;: &quot;AP-3&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610133F90000A4BC&quot;&amp;
            \}&amp;
        \},&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
            &quot;id&quot;: &quot;NM-2&quot;,&amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JOHNNY&quot;,&amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;,&amp;
                    &quot;id&quot;: &quot;AP-5&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610133F90000A4BD&quot;&amp;
            \}&amp;
        \}&amp;
    ],&amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-1&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T10:17:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T11:00:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;920&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;,&amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \},&amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0,&amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \},&amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \},&amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \},&amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \},&amp;
                    &quot;id&quot;: &quot;6X-920-2025-02-10-NCE-CDG&quot;&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;,&amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;,&amp;
                        &quot;id&quot;: &quot;BKG-1&quot;,&amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CC&quot;,&amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                            &quot;id&quot;: &quot;NM-1&quot;,&amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \},&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;,&amp;
                        &quot;id&quot;: &quot;BKG-2&quot;,&amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CD&quot;,&amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                            &quot;id&quot;: &quot;NM-2&quot;,&amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ],&amp;
                &quot;distributionMethod&quot;: &quot;E&quot;,&amp;
                &quot;notAcknowledged&quot;: false&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \},&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-2&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \},&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-2&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T12:00:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;AMS&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T13:00:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;3902&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;,&amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \},&amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0,&amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \},&amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \},&amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \},&amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \},&amp;
                    &quot;id&quot;: &quot;9S-1550-2025-02-10-CDG-LHR&quot;&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;,&amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;,&amp;
                        &quot;id&quot;: &quot;BKG-3&quot;,&amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CE&quot;,&amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                            &quot;id&quot;: &quot;NM-1&quot;,&amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \},&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;,&amp;
                        &quot;id&quot;: &quot;BKG-4&quot;,&amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CF&quot;,&amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                            &quot;id&quot;: &quot;NM-2&quot;,&amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ],&amp;
                &quot;distributionMethod&quot;: &quot;E&quot;,&amp;
                &quot;notAcknowledged&quot;: false&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \},&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-2&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \},&amp;
\t\t\{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-3&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;AMS&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T14:25:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;TRD&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T16:40:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;KL&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;1153&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;,&amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \},&amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0,&amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;KL&quot;&amp;
                                \},&amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \},&amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \},&amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \},&amp;
                    &quot;id&quot;: &quot;KL-1153-2025-02-10-CDG-LHR&quot;&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;,&amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;,&amp;
                        &quot;id&quot;: &quot;BKG-5&quot;,&amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CE&quot;,&amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                            &quot;id&quot;: &quot;NM-1&quot;,&amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \},&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;,&amp;
                        &quot;id&quot;: &quot;BKG-6&quot;,&amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CF&quot;,&amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                            &quot;id&quot;: &quot;NM-2&quot;,&amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ],&amp;
                &quot;distributionMethod&quot;: &quot;E&quot;,&amp;
                &quot;notAcknowledged&quot;: false&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \},&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-2&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;flightItinerary&quot;: [&amp;
        \{&amp;
            &quot;flights&quot;: [&amp;
                \{&amp;
                    &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-CNX-1&quot;,&amp;
                    &quot;connectedFlights&quot;: \{&amp;
                        &quot;connectionType&quot;: &quot;CONNECTION&quot;,&amp;
                        &quot;flightSegments&quot;: [&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-1&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \},&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-2&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \},&amp;
\t\t\t\t\t\t\t\{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-3&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}&amp;
                        ]&amp;
                    \}&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;,&amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AP-7&quot;,&amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ],&amp;
            &quot;freeFlowFormat&quot;: &quot;NCE&quot;,&amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \},&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-2&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;,&amp;
            &quot;code&quot;: &quot;OK&quot;&amp;
        \}&amp;
    ]&amp;
\}&amp;
]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="16:10:41.668071 - 14 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6GGLMY4TT]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2694]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[ShYaFDIwMjQtMTAtMDlUMTQ6MTM6Mjhael8KC3N0YWtlaG9sZGVyEgROTS0xIg0SBEpBTkUaBVNNSVRIciYKB2NvbnRhY3QSBEFQLTMaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwMTMzRjkwMDAwQTRCQ3phCgtzdGFrZWhvbGRlchIETk0tMiIPEgZKT0hOTlkaBVNNSVRIciYKB2NvbnRhY3QSBEFQLTUaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwMTMzRjkwMDAwQTRCRIIBywMKB3Byb2R1Y3QQARobN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0xIsYCChoKA05DRRoTMjAyNS0wMi0yMFQxMDoxNzowMBIaCgNDREcaEzIwMjUtMDItMjBUMTE6MDA6MDAiTQoJCgI2WBIDOTIwEiUKAVkSAwoBWRoSCgASDAoEGgI2WBIEKgJGUiABIgdFQ09OT01ZMhk2WC05MjAtMjAyNS0wMi0xMC1OQ0UtQ0RHSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMRoQNjAwMUMzRkEwMDAwRTVDQ1orCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMhoQNjAwMUMzRkEwMDAwRTVDRForCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOCAc0DCgdwcm9kdWN0EAEaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BSVItMiLIAgoaCgNDREcaEzIwMjUtMDItMjBUMTI6MDA6MDASGgoDQU1TGhMyMDI1LTAyLTIwVDEzOjAwOjAwIk8KCgoCNlgSBDM5MDISJQoBWRIDCgFZGhIKABIMCgQaAjZYEgQqAkZSIAEiB0VDT05PTVkyGjlTLTE1NTAtMjAyNS0wMi0xMC1DREctTEhSSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMxoQNjAwMUMzRkEwMDAwRTVDRVorCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNBoQNjAwMUMzRkEwMDAwRTVDRlorCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOCAc0DCgdwcm9kdWN0EAEaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BSVItMyLIAgoaCgNBTVMaEzIwMjUtMDItMjBUMTQ6MjU6MDASGgoDVFJEGhMyMDI1LTAyLTIwVDE2OjQwOjAwIk8KCgoCS0wSBDExNTMSJQoBWRIDCgFZGhIKABIMCgQaAktMEgQqAkZSIAEiB0VDT05PTVkyGktMLTExNTMtMjAyNS0wMi0xMC1DREctTEhSSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNRoQNjAwMUMzRkEwMDAwRTVDRVorCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNhoQNjAwMUMzRkEwMDAwRTVDRlorCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAeIBIt8BCr8BCAESPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0xGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMSPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0yGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMSPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0zGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1DTlgtMbIBiQEKB2NvbnRhY3QSGjdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BUC03QgEBWgUKA05DRWIrCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2IrCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBFQoRYXV0b21hdGVkLXByb2Nlc3MYBQ==]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="8" responseEndLine="154" responseBeginLine="143" endLine="141" beginLine="134" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:41.670018 - 14 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/ HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header2"><VALUE><![CDATA[eyJub25jZSI6Ik9UUXlOREk1TkRFME56YzRPVFU1Tnc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MTA6MzQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiR3BMK05Tak9tOHh0TDgxZmkyTUhwbWM5RHVVPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ShYaFDIwMjQtMTAtMDlUMTQ6MTM6Mjhael8KC3N0YWtlaG9sZGVyEgROTS0xIg0SBEpBTkUaBVNNSVRIciYKB2NvbnRhY3QSBEFQLTMaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwMTMzRjkwMDAwQTRCQ3phCgtzdGFrZWhvbGRlchIETk0tMiIPEgZKT0hOTlkaBVNNSVRIciYKB2NvbnRhY3QSBEFQLTUaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwMTMzRjkwMDAwQTRCRIIBywMKB3Byb2R1Y3QQARobN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0xIsYCChoKA05DRRoTMjAyNS0wMi0yMFQxMDoxNzowMBIaCgNDREcaEzIwMjUtMDItMjBUMTE6MDA6MDAiTQoJCgI2WBIDOTIwEiUKAVkSAwoBWRoSCgASDAoEGgI2WBIEKgJGUiABIgdFQ09OT01ZMhk2WC05MjAtMjAyNS0wMi0xMC1OQ0UtQ0RHSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMRoQNjAwMUMzRkEwMDAwRTVDQ1orCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMhoQNjAwMUMzRkEwMDAwRTVDRForCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOCAc0DCgdwcm9kdWN0EAEaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BSVItMiLIAgoaCgNDREcaEzIwMjUtMDItMjBUMTI6MDA6MDASGgoDQU1TGhMyMDI1LTAyLTIwVDEzOjAwOjAwIk8KCgoCNlgSBDM5MDISJQoBWRIDCgFZGhIKABIMCgQaAjZYEgQqAkZSIAEiB0VDT05PTVkyGjlTLTE1NTAtMjAyNS0wMi0xMC1DREctTEhSSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMxoQNjAwMUMzRkEwMDAwRTVDRVorCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNBoQNjAwMUMzRkEwMDAwRTVDRlorCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOCAc0DCgdwcm9kdWN0EAEaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BSVItMyLIAgoaCgNBTVMaEzIwMjUtMDItMjBUMTQ6MjU6MDASGgoDVFJEGhMyMDI1LTAyLTIwVDE2OjQwOjAwIk8KCgoCS0wSBDExNTMSJQoBWRIDCgFZGhIKABIMCgQaAktMEgQqAkZSIAEiB0VDT05PTVkyGktMLTExNTMtMjAyNS0wMi0xMC1DREctTEhSSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNRoQNjAwMUMzRkEwMDAwRTVDRVorCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNhoQNjAwMUMzRkEwMDAwRTVDRlorCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAeIBIt8BCr8BCAESPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0xGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMSPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0yGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMSPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0zGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1DTlgtMbIBiQEKB2NvbnRhY3QSGjdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BUC03QgEBWgUKA05DRWIrCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2IrCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBFQoRYXV0b21hdGVkLXByb2Nlc3MYBQ==]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 9: A character does not match, expected &apos;2&apos;, received &apos;4&apos;." compareAt="16:10:42.689824 - 14 Nov 2024"><TEXT><![CDATA[HTTP/1.1 ]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[201 Created]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[400 Bad Request]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6GGOMY4TT]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[224]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[etag:{*}&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[content-type:application/vnd.amadeus+json; charset=utf-8&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[con]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[tent-type:application/vnd.amadeus+json; charset=utf-8]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[nection:close]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[connection:close]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED></EXPECTED><RECEIVED><TEXT><![CDATA[\{]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[\{]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[    &quot;errors&quot;: []]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;reference&quot;: &quot;{%recloc%=.{6}}&quot;, &amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[    \{&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;version&quot;: &quot;{*}&quot;, &amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[        &quot;status&quot;: 400, &amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;openPnr&quot;: &quot;{%received_protobuf2%=.*}&quot;&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[        &quot;detail&quot;: &quot;Error at PNR Elements creation time&quot;, &amp;
]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[\}]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[            &quot;title&quot;: &quot;NOT AVAILABLE AND WAITLIST CLOSED&quot;, &amp;
            &quot;code&quot;: 5511, &amp;
            &quot;source&quot;: \{&amp;
                &quot;parameter&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-3&quot;, &amp;
                &quot;pointer&quot;: &quot;/openPnr/products/airSegment&quot;&amp;
            \}&amp;
        \}&amp;
    ]&amp;
\}]]></TEXT></RECEIVED></UNMATCH></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="9" responseEndLine="179" responseBeginLine="172" endLine="170" beginLine="164" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:42.691748 - 14 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Debug-Format: debug&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header3"><VALUE><![CDATA[eyJub25jZSI6Ik5EZ3dPREF3TlRjNU1EWXhPRGd6TXc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MTA6MzQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiRWF0RERBdXNTdGxyQXpVbXpjTmVLdmVEYW1RPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON KO="KO" validate="manual" matchMessage="Match failed with error code 1: Callback rejected:Match function exits on unspecified Error." compareAt="16:10:42.931170 - 14 Nov 2024"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6GGSMY4TU]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="10" responseEndLine="198" responseBeginLine="190" endLine="188" beginLine="187" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:42.933032 - 14 Nov 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;-&apos;, received &apos;I&apos;." compareAt="16:10:43.062541 - 14 Nov 2024"><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[--- RLR ---]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[INVALID]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RP/NCE1A0955/NCE1A0955            YG/SU  ]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[{*}Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[&gt;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[  1.SMITH/JANE   2.SMITH/JOHNNY]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&amp;
  3  6X 920 Y 20FEB 4 NCECDG HK2  1017 1100  20FEB  E  6X/]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[  4  6X3902 Y 20FEB 4 CDGAMS HK2  1200 1300  20FEB  E  6X/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[  5  KL1153 Y 20FEB 4 AMSTRD HK2  1425 1640  20FEB  E  KL/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[  6 AP NCE/P1-2]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&amp;
  7 TK OK]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><VARIABLE name="today_ddmmm"><VALUE><![CDATA[14NOV]]></VALUE></VARIABLE><TEXT><![CDATA[/NCE1A0955&amp;
]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&gt;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="11" responseEndLine="222" responseBeginLine="211" endLine="210" beginLine="206" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:43.063490 - 14 Nov 2024"><TEXT><![CDATA[GET /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[ HTTP/1.1&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header4"><VALUE><![CDATA[eyJub25jZSI6Ik1UZ3dOakkxTWpjMU1EYzFNekE0TlE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MTA6MzQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiWFpSZXJWUVdQNDRuODk0NWsvSUlua2hUMlZVPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 9: A character does not match, expected &apos;2&apos;, received &apos;4&apos;." compareAt="16:10:43.289226 - 14 Nov 2024"><TEXT><![CDATA[HTTP/1.1 ]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[200 OK]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[400 Bad Request]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6GGVMY4TV]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[102]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[etag:{*}&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[content-type:application/vnd.amadeus+json; charset=utf-8&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[con]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[tent-type:application/vnd.amadeus+json; charset=utf-8]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[nection:close]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[connection:close]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED></EXPECTED><RECEIVED><TEXT><![CDATA[\{]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[\{]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[    &quot;errors&quot;: []]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;reference&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;, &amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[    \{&amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;version&quot;: &quot;{*}&quot;, &amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[        &quot;status&quot;: 400, &amp;
]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[    ]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[&quot;openPnr&quot;: &quot;{%received_protobuf%=.*}&quot;&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[        &quot;detail&quot;: &quot;No PNR reference provided&quot;, &amp;
]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[\}]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[            &quot;title&quot;: &quot;UNABLE TO PROCESS&quot;, &amp;
            &quot;code&quot;: 11&amp;
        \}&amp;
    ]&amp;
\}]]></TEXT></RECEIVED></UNMATCH></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="12" responseEndLine="245" responseBeginLine="238" endLine="236" beginLine="232" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:43.290268 - 14 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header5"><VALUE><![CDATA[eyJub25jZSI6Ik5USTNPVGcyTlRJNE5EZ3pNamd4T1E9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTRUMTU6MTA6MzQuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiZWttZTEvK0U0U3FhNlZ2NUthNEpDSzQ1R3pBPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ShYaFDIwMjQtMTAtMDlUMTQ6MTM6Mjhael8KC3N0YWtlaG9sZGVyEgROTS0xIg0SBEpBTkUaBVNNSVRIciYKB2NvbnRhY3QSBEFQLTMaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwMTMzRjkwMDAwQTRCQ3phCgtzdGFrZWhvbGRlchIETk0tMiIPEgZKT0hOTlkaBVNNSVRIciYKB2NvbnRhY3QSBEFQLTUaFXByb2Nlc3NlZFBuci5jb250YWN0c6IBEhIQNjEwMTMzRjkwMDAwQTRCRIIBywMKB3Byb2R1Y3QQARobN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0xIsYCChoKA05DRRoTMjAyNS0wMi0yMFQxMDoxNzowMBIaCgNDREcaEzIwMjUtMDItMjBUMTE6MDA6MDAiTQoJCgI2WBIDOTIwEiUKAVkSAwoBWRoSCgASDAoEGgI2WBIEKgJGUiABIgdFQ09OT01ZMhk2WC05MjAtMjAyNS0wMi0xMC1OQ0UtQ0RHSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMRoQNjAwMUMzRkEwMDAwRTVDQ1orCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMhoQNjAwMUMzRkEwMDAwRTVDRForCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOCAc0DCgdwcm9kdWN0EAEaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BSVItMiLIAgoaCgNDREcaEzIwMjUtMDItMjBUMTI6MDA6MDASGgoDQU1TGhMyMDI1LTAyLTIwVDEzOjAwOjAwIk8KCgoCNlgSBDM5MDISJQoBWRIDCgFZGhIKABIMCgQaAjZYEgQqAkZSIAEiB0VDT05PTVkyGjlTLTE1NTAtMjAyNS0wMi0xMC1DREctTEhSSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctMxoQNjAwMUMzRkEwMDAwRTVDRVorCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNBoQNjAwMUMzRkEwMDAwRTVDRlorCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOCAc0DCgdwcm9kdWN0EAEaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BSVItMyLIAgoaCgNBTVMaEzIwMjUtMDItMjBUMTQ6MjU6MDASGgoDVFJEGhMyMDI1LTAyLTIwVDE2OjQwOjAwIk8KCgoCS0wSBDExNTMSJQoBWRIDCgFZGhIKABIMCgQaAktMEgQqAkZSIAEiB0VDT05PTVkyGktMLTExNTMtMjAyNS0wMi0xMC1DREctTEhSSgJOTmJYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNRoQNjAwMUMzRkEwMDAwRTVDRVorCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2JYChBzZWdtZW50LWRlbGl2ZXJ5EgVCS0ctNhoQNjAwMUMzRkEwMDAwRTVDRlorCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQBCKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnNCKwoLc3Rha2Vob2xkZXISBE5NLTIaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAeIBIt8BCr8BCAESPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0xGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMSPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0yGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMSPQoHcHJvZHVjdBIbN0tGNEJHLTIwMjQtMTAtMDktUE5SLUFJUi0zGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMaGzdLRjRCRy0yMDI0LTEwLTA5LVBOUi1DTlgtMbIBiQEKB2NvbnRhY3QSGjdLRjRCRy0yMDI0LTEwLTA5LVBOUi1BUC03QgEBWgUKA05DRWIrCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2IrCgtzdGFrZWhvbGRlchIETk0tMhoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc7oBFQoRYXV0b21hdGVkLXByb2Nlc3MYBQ==]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON KO="KO" validate="manual" matchMessage="Match failed with error code 1: Callback rejected:Match function exits on unspecified Error." compareAt="16:10:43.524782 - 14 Nov 2024"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001E6GGXMY4TV]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[4481]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-10-09T14:13:28Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JANE&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;AP-3&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610133F90000A4BC&quot;&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;NM-2&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JOHNNY&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;AP-5&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610133F90000A4BD&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T10:17:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T11:00:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;920&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-920-2025-02-10-NCE-CDG&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CC&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}, &amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;BKG-2&quot;, &amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CD&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;NM-2&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-2&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T12:00:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;AMS&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T13:00:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;3902&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;6X&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;9S-1550-2025-02-10-CDG-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;BKG-3&quot;, &amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CE&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}, &amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;BKG-4&quot;, &amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CF&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;NM-2&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-3&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;AMS&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T14:25:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;TRD&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2025-02-20T16:40:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;KL&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;1153&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;KL&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;KL-1153-2025-02-10-CDG-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;BKG-5&quot;, &amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CE&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}, &amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;BKG-6&quot;, &amp;
                        &quot;distributionId&quot;: &quot;6001C3FA0000E5CF&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;NM-2&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;flightItinerary&quot;: [&amp;
        \{&amp;
            &quot;flights&quot;: [&amp;
                \{&amp;
                    &quot;connectedFlights&quot;: \{&amp;
                        &quot;connectionType&quot;: &quot;CONNECTION&quot;, &amp;
                        &quot;flightSegments&quot;: [&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-1&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}, &amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-2&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}, &amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AIR-3&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}&amp;
                        ]&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-CNX-1&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;7KF4BG-2024-10-09-PNR-AP-7&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;NCE&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;NM-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="13" responseEndLine="267" responseBeginLine="265" endLine="263" beginLine="259" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:43.606705 - 14 Nov 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: The global pattern match failed (3 patterns, RE result: -1)." compareAt="16:10:43.746993 - 14 Nov 2024"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[{(multi).*}&apos;&amp;
PNH++{%env_num%=.{1}}&apos;&amp;
{(multi).*}&apos;&amp;
]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[MSG+:M&apos;&amp;
ERC+1:EC:1A&apos;&amp;
IFT+C:50:::EN+CHECK FORMAT&apos;]]></TEXT></RECEIVED></UNMATCH></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14" endLine="276" beginLine="275" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="N/A"><SCRIPT type="Exec">env_num = int (env_num)
env_num = env_num - 0
</SCRIPT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:43.749725 - 14 Nov 2024"><TEXT><![CDATA[UNH++::&apos;&amp;
print(env_num)]]></TEXT></QUERY><REPLY receiveAt="16:10:43.834178 - 14 Nov 2024" filename="">UNB+IATB:1+1AAPITES3+TESAPI3+241114:1510+01KKEDW7C40002+00LH2EJ7JN0002++E&apos;&amp;
UNH+1+CONTRL:2:1:UN+09CC2B44&apos;&amp;
UCI+00LH2EJ7JN0002+TESAPI3+1AAPITES3+7&apos;&amp;
UCM+1+UNKMSG:XX:X:XX+4+17&apos;&amp;
UNT+4+1&apos;&amp;
UNZ+1+01KKEDW7C40002&apos;</REPLY></TRANSACTION><ERROR filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" line="275" severity="Error">Python Error in exec script</ERROR><TRANSACTION transactionCounter="14"><QUERY filename="" loop="0" sentAt="16:10:43.834559 - 14 Nov 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="15" responseEndLine="306" responseBeginLine="293" endLine="291" beginLine="285" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="looping"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:44.001850 - 14 Nov 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE6X0100++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;P&apos;, received &apos;C&apos;." compareAt="16:10:44.070014 - 14 Nov 2024"><TEXT><![CDATA[UNH++]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[PURCRR]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[CONTRL]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[14]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[2]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:1:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[1A]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UN]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCI+01BGMZZ5BF0001+1ASI+NONE+7&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCM+1+PURCRQ:14:1:1A+4+18&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[SPR+++2005:8:8+2100:12:12]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+{%backend%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{%message_id%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{%sdi_date2%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="15" responseEndLine="306" responseBeginLine="293" endLine="291" beginLine="285" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="1" sentAt="16:10:47.084159 - 14 Nov 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE6X0100++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;P&apos;, received &apos;C&apos;." compareAt="16:10:47.156738 - 14 Nov 2024"><TEXT><![CDATA[UNH++]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[PURCRR]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[CONTRL]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[14]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[2]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:1:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[1A]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UN]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[14NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCI+001OFZD9UW0001+1ASI+NONE+7&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCM+1+PURCRQ:14:1:1A+4+18&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[SPR+++2005:8:8+2100:12:12]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><VARIABLE name="recloc"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[::{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+{%backend%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{%message_id%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{%sdi_date2%=*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="16" responseEndLine="326" responseBeginLine="320" endLine="319" beginLine="315" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" match="KO"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Multi_CNX_Create_Feed.cry" loop="0" sentAt="16:10:50.233435 - 14 Nov 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON KO="KO" matchMessage="Match failed in body at index 0: A character does not match, expected &apos;P&apos;, received &apos;C&apos;." compareAt="16:10:50.303327 - 14 Nov 2024"><TEXT><![CDATA[UNH++]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[PUPIRR]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[CONTRL]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[14]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[2]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[:1:]]></TEXT><UNMATCH validate="automatic"><EXPECTED><TEXT><![CDATA[1A]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UN]]></TEXT></RECEIVED></UNMATCH><TEXT><![CDATA[+&apos;&amp;
]]></TEXT><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+ID+{*}&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCI+001VCL9GRV0001+1ASI+NONE+7&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[IRV+OBE+SONPK{*}&apos;]]></TEXT></EXPECTED><RECEIVED><TEXT><![CDATA[UCM+1+PUPIRQ:14:1:1A+4+18&apos;]]></TEXT></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[SDI+++{*}&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><UNMATCH validate="manual"><EXPECTED><TEXT><![CDATA[BLB+{*}+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C{%raw_binary%=(multi).*}UNT\x1D2\x1D1\x1C&apos;]]></TEXT></EXPECTED><RECEIVED></RECEIVED></UNMATCH><TEXT><![CDATA[&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION></TRANSACTION><ERROR filename="" line="340" severity="Fatal Error">The variable &apos;global_regression.openpnr_payload&apos; is not defined</ERROR><STATISTIC><STATISTIC_ELEMENT name="Message in">18</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">17820</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">18</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">19947</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">11</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">18</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">17</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.944444</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">11498.6</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">1.277</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">3184.41</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">27</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">12</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">8</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">8</STATISTIC_ELEMENT></STATISTIC></xml>