<xml scenarioFilename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry"><SCRIPT type="Initialize">import json
from lib.openpnr import extract_binary_payload
from lib.json_match import assert_equal, assert_found, assert_not_found, parse_json

execfile(global_regression.TTS_RootDir + &apos;/data/data_&apos; + global_regression.TEST_SYSTEM + &apos;.py&apos;)

TTS_OK = TTServer.currentMessage.TTS_MATCH_COMPARISON_OK
TTS_KO = TTServer.currentMessage.TTS_MATCH_COMPARISON_FAILURE

# As the specific conditions to evaluate depend on the test, the comparison function is in the individual script
# In case of match error, find the error details in TTS logs (not available in .log or in .rex file)
# Variables defined in data files (e.g., test user data) or in the current scripts (e.g., recloc)
# are directly available from inside the function.
def validate_openpnr(openpnr_json):
    try:
        openpnr = parse_json(openpnr_json)
        for field in [&apos;reference&apos;, &apos;creation&apos;, &apos;travelers&apos;, &apos;flightItinerary&apos;, &apos;products&apos;, &apos;contacts&apos;]:
            assert_found(field, container=openpnr)

        expected_openpnr_id = recloc + &apos;-&apos; + today
        assert_equal(actual=openpnr[&apos;id&apos;], expected=expected_openpnr_id, item_name=&apos;OpenPNR id field&apos;)
        assert_not_found(&apos;creation/date&apos;, container=openpnr)
        assert_found(&apos;creation/dateTime&apos;, container=openpnr)
        assert_found(&apos;creation/pointOfSale/office/id&apos;, container=openpnr)
        assert_equal(expected=&quot;NCE1A0955&quot;, actual=openpnr[&apos;creation&apos;][&apos;pointOfSale&apos;][&apos;office&apos;][&apos;id&apos;], item_name=&apos;creator office&apos;)

        assert_equal(actual=len(openpnr[&apos;flightItinerary&apos;]), expected=1, item_name=&apos;number of flightItinerary&apos;)
        flightItinerary_1 = openpnr[&apos;flightItinerary&apos;][0]

        #Check service data for flightItinerary section in output json
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;connectionType&apos;], expected=&quot;CONNECTION&quot;, item_name=&apos;flightItinerary/flights/connectionType&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][0][&apos;type&apos;], expected=&quot;product&quot;, item_name=&apos;flightItinerary/flights/flightSegments/type&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][0][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AIR-1&quot;, item_name=&apos;flightItinerary/flights/flightSegments/id&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][1][&apos;type&apos;], expected=&quot;product&quot;, item_name=&apos;flightItinerary/flights/flightSegments/type&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;connectedFlights&apos;][&apos;flightSegments&apos;][1][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-AIR-2&quot;, item_name=&apos;flightItinerary/flights/flightSegments/id&apos;)
        assert_equal(actual=flightItinerary_1[&apos;flights&apos;][0][&apos;id&apos;], expected= recloc+&quot;-&quot;+today+&quot;-PNR-CNX-3&quot;, item_name=&apos;flightItinerary/flights/id&apos;)


    except Exception as e:
        print(&apos;OpenPNR validation failed: {}&apos;.format(e))
        return TTS_KO

    print(&apos;OpenPNR validation successful&apos;)
    return TTS_OK

</SCRIPT><TRANSACTION transactionCounter="1" endLine="82" beginLine="81" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:48.734898 - 15 Nov 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="09:32:48.854430 - 15 Nov 2024" filename="">SIGN IN&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="2" responseEndLine="85" responseBeginLine="84" endLine="83" beginLine="82" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:48.857041 - 15 Nov 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><COMPARISON compareAt="09:32:48.945553 - 15 Nov 2024" match="OK"><TEXT><![CDATA[SIGN IN&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="3" endLine="87" beginLine="86" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:48.946387 - 15 Nov 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="09:32:49.048165 - 15 Nov 2024" filename="">&amp;
09CC2B44         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="4" endLine="94" beginLine="93" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><COMMENT> 1. Sign in with test_user_1A_sign in office test_user_1A_office</COMMENT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:49.049278 - 15 Nov 2024"><TEXT><![CDATA[OK-WE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="09:32:49.132760 - 15 Nov 2024" filename="">  NETWORK 09 SUB-SYS FE DELETION LIST&amp;
     CC2B44    DELETED OK&amp;
  DELETION FINISHED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="5" endLine="96" beginLine="95" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:51.140793 - 15 Nov 2024"><TEXT><![CDATA[OK-WY/C-C5AGY/W-AMAD/S-80X22/O-]]></TEXT><VARIABLE name="test_user_1A_office"><VALUE><![CDATA[NCE1A0955]]></VALUE></VARIABLE><TEXT><![CDATA[/T-NCE/A-NCE/L-]]></TEXT><VARIABLE name="ATID"><VALUE><![CDATA[09CC2B44]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="09:32:51.224392 - 15 Nov 2024" filename="">&amp;
LEIDS:   CC2B44&amp;
INITIALIZED FOR: NETWORK 09&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="6" responseEndLine="100" responseBeginLine="100" endLine="98" beginLine="97" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:51.224791 - 15 Nov 2024"><TEXT><![CDATA[Jia]]></TEXT><VARIABLE name="test_user_1A_sign"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[/SU.]]></TEXT><VARIABLE name="test_user_1A_extended_office"><VALUE><![CDATA[NCE6X0100]]></VALUE></VARIABLE><TEXT><![CDATA[-]]></TEXT><VARIABLE name="test_user_1A_pwd"><VALUE><![CDATA[GVxyuXx77768bg+-]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="09:32:51.443191 - 15 Nov 2024" match="OK"><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{.*}]]></EXPRESSION><VALUE><![CDATA[&amp;
]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[A-SIGN COMPLETE]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/15NOV/SU&amp;
************  AMADEUS PRODUCT NEWS  ***********  SEE GGNEWS&amp;
AIR2 INSELAIR INTERNATIONAL (7I) ENJOYS ISM IASR GGNEWSAIR2&amp;
HTL  BALLADINS (BL) ENJOY HTL DYNAMIC ACCESS     GGNEWSHTL&amp;
AIR1 PULLMANTUR AIR (EB) ENJOYS AAS              GGNEWSAIR1&amp;
AIR  UTAIR UKRAINE (QU) ENJOYS AAS               GGNEWSAIR&amp;
&gt;]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="7" responseEndLine="125" responseBeginLine="116" endLine="114" beginLine="109" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:51.444830 - 15 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=json\&amp;output=protobufBase64 HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header"><VALUE><![CDATA[eyJub25jZSI6Ik5ESXhOemswTURNeE1UWXdOVEkzTkE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTVUMDg6MzI6NDIuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiUnl5aFJQRkwwQ3JjMXpVTzRjTmtZTDI1QVBjPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT><VARIABLE name="input_json_single_connected_flights"><VALUE><![CDATA[&amp;
\{&amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-10-09T14:13:28Z&quot;&amp;
    \},&amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;,&amp;
            &quot;id&quot;: &quot;NM-1&quot;,&amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JANE&quot;,&amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ],&amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610133F90000A4BC&quot;&amp;
            \}&amp;
        \}&amp;
    ],&amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;AIR-1&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T09:30:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T10:30:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;7725&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;&amp;
                    \}&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \},&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;,&amp;
            &quot;subType&quot;: &quot;AIR&quot;,&amp;
            &quot;id&quot;: &quot;AIR-2&quot;,&amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \},&amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;,&amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \},&amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;,&amp;
                        &quot;flightNumber&quot;: &quot;7726&quot;&amp;
                    \},&amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;&amp;
                    \}&amp;
                \},&amp;
                &quot;bookingStatusCode&quot;: &quot;NN&quot;&amp;
            \},&amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;flightItinerary&quot;: [&amp;
        \{&amp;
            &quot;flights&quot;: [&amp;
                \{&amp;
                    &quot;connectedFlights&quot;: \{&amp;
                        &quot;connectionType&quot;: &quot;CONNECTION&quot;,&amp;
                        &quot;flightSegments&quot;: [&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;AIR-1&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \},&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;,&amp;
                                &quot;id&quot;: &quot;AIR-2&quot;,&amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}&amp;
                        ]&amp;
                    \},&amp;
                    &quot;id&quot;: &quot;CNX-5&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;,&amp;
            &quot;id&quot;: &quot;AP-3&quot;,&amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ],&amp;
            &quot;freeFlowFormat&quot;: &quot;NCE&quot;,&amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;,&amp;
                    &quot;id&quot;: &quot;NM-1&quot;,&amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ],&amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;,&amp;
            &quot;code&quot;: &quot;OK&quot;&amp;
        \}&amp;
    ]&amp;
\}&amp;
]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="09:32:51.702690 - 15 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001EEIUJMZH2R]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[778]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[ShYaFDIwMjQtMTAtMDlUMTQ6MTM6MjhaejcKC3N0YWtlaG9sZGVyEgROTS0xIg0SBEpBTkUaBVNNSVRIogESEhA2MTAxMzNGOTAwMDBBNEJDggGQAQoHcHJvZHVjdBABGgVBSVItMSJPChoKA05DRRoTMjAyNC0xMi0yOVQwOTozMDowMBIaCgNDREcaEzIwMjQtMTItMjlUMTA6MzA6MDAiEQoKCgI2WBIENzcyNRIDCgFZSgJOTkIrCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4IBkAEKB3Byb2R1Y3QQARoFQUlSLTIiTwoaCgNDREcaEzIwMjQtMTItMjlUMTE6MzA6MDASGgoDTEhSGhMyMDI0LTEyLTI5VDExOjMwOjAwIhEKCgoCNlgSBDc3MjYSAwoBWUoCTk5CKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAV8iXQpUCAESJwoHcHJvZHVjdBIFQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0cxInCgdwcm9kdWN0EgVBSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzGgVDTlgtNbIBRgoHY29udGFjdBIEQVAtM0IBAVoFCgNOQ0ViKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6ARUKEWF1dG9tYXRlZC1wcm9jZXNzGAU=]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="8" responseEndLine="154" responseBeginLine="143" endLine="141" beginLine="134" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:51.703634 - 15 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/ HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header2"><VALUE><![CDATA[eyJub25jZSI6Ik9UYzFNamMyT1RNNE1qYzRNek00TXc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTVUMDg6MzI6NDIuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiTXAyZUxXZytaTk9BOGRhNXhabHU5STkrNkVZPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ShYaFDIwMjQtMTAtMDlUMTQ6MTM6MjhaejcKC3N0YWtlaG9sZGVyEgROTS0xIg0SBEpBTkUaBVNNSVRIogESEhA2MTAxMzNGOTAwMDBBNEJDggGQAQoHcHJvZHVjdBABGgVBSVItMSJPChoKA05DRRoTMjAyNC0xMi0yOVQwOTozMDowMBIaCgNDREcaEzIwMjQtMTItMjlUMTA6MzA6MDAiEQoKCgI2WBIENzcyNRIDCgFZSgJOTkIrCgtzdGFrZWhvbGRlchIETk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4IBkAEKB3Byb2R1Y3QQARoFQUlSLTIiTwoaCgNDREcaEzIwMjQtMTItMjlUMTE6MzA6MDASGgoDTEhSGhMyMDI0LTEyLTI5VDExOjMwOjAwIhEKCgoCNlgSBDc3MjYSAwoBWUoCTk5CKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAV8iXQpUCAESJwoHcHJvZHVjdBIFQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0cxInCgdwcm9kdWN0EgVBSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzGgVDTlgtNbIBRgoHY29udGFjdBIEQVAtM0IBAVoFCgNOQ0ViKwoLc3Rha2Vob2xkZXISBE5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6ARUKEWF1dG9tYXRlZC1wcm9jZXNzGAU=]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></QUERY><COMPARISON compareAt="09:32:53.454325 - 15 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 201 Created&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001EEIUMMZH2R]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2065]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%recloc%=.{6}}]]></EXPRESSION><VALUE><![CDATA[ANWKIB]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf2%=.*}]]></EXPRESSION><VALUE><![CDATA[ChFBTldLSUItMjAyNC0xMS0xNRIDcG5yGgZBTldLSUIiATA6VRoUMjAyNC0xMS0xNVQwODozMjowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0xMS0xNVQwODozMjo1Mlp6iwEKC3N0YWtlaG9sZGVyEhpBTldLSUItMjAyNC0xMS0xNS1QTlItTk0tMSINEgRKQU5FGgVTTUlUSHI8Cgdjb250YWN0EhpBTldLSUItMjAyNC0xMS0xNS1QTlItQVAtNRoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBOTQxRTAwMDMxNDA5ggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTEimwIKGgoDTkNFGhMyMDI0LTEyLTI5VDA5OjMwOjAwEhoKA0NERxoTMjAyNC0xMi0yOVQxMDozMDowMCJPCgoKAjZYEgQ3NzI1EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI1LTIwMjQtMTItMjktTkNFLUNER0oCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMRoQNjAwQTI0MUUwMDA1NDQzRlpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTIimwIKGgoDQ0RHGhMyMDI0LTEyLTI5VDExOjMwOjAwEhoKA0xIUhoTMjAyNC0xMi0yOVQxMTozMDowMCJPCgoKAjZYEgQ3NzI2EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI2LTIwMjQtMTItMjktQ0RHLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMhoQNjAwQTI0MUUwMDA1NDQ0MFpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAigGjASKgAQqAAQgBEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQ05YLTOyAXIKB2NvbnRhY3QSGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1BUC01QgEBWgUKA05DRWJBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AZQCChFhdXRvbWF0ZWQtcHJvY2VzcxIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLVRLLTYYBSITMjAyNC0xMS0xNVQwMDowMDowMCoLCglOQ0UxQTA5NTVaQQoLc3Rha2Vob2xkZXISGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="9" responseEndLine="179" responseBeginLine="172" endLine="170" beginLine="164" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:53.455715 - 15 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Debug-Format: debug&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header3"><VALUE><![CDATA[eyJub25jZSI6Ik1UQXpNVGc1T0RrNE1qRTROVFk1T1E9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTVUMDg6MzI6NDIuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoicEdlWUU1V1lWN1JydktvMmdPZEtmYklBWDlvPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf2"><VALUE><![CDATA[ChFBTldLSUItMjAyNC0xMS0xNRIDcG5yGgZBTldLSUIiATA6VRoUMjAyNC0xMS0xNVQwODozMjowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0xMS0xNVQwODozMjo1Mlp6iwEKC3N0YWtlaG9sZGVyEhpBTldLSUItMjAyNC0xMS0xNS1QTlItTk0tMSINEgRKQU5FGgVTTUlUSHI8Cgdjb250YWN0EhpBTldLSUItMjAyNC0xMS0xNS1QTlItQVAtNRoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBOTQxRTAwMDMxNDA5ggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTEimwIKGgoDTkNFGhMyMDI0LTEyLTI5VDA5OjMwOjAwEhoKA0NERxoTMjAyNC0xMi0yOVQxMDozMDowMCJPCgoKAjZYEgQ3NzI1EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI1LTIwMjQtMTItMjktTkNFLUNER0oCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMRoQNjAwQTI0MUUwMDA1NDQzRlpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTIimwIKGgoDQ0RHGhMyMDI0LTEyLTI5VDExOjMwOjAwEhoKA0xIUhoTMjAyNC0xMi0yOVQxMTozMDowMCJPCgoKAjZYEgQ3NzI2EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI2LTIwMjQtMTItMjktQ0RHLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMhoQNjAwQTI0MUUwMDA1NDQ0MFpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAigGjASKgAQqAAQgBEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQ05YLTOyAXIKB2NvbnRhY3QSGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1BUC01QgEBWgUKA05DRWJBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AZQCChFhdXRvbWF0ZWQtcHJvY2VzcxIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLVRLLTYYBSITMjAyNC0xMS0xNVQwMDowMDowMCoLCglOQ0UxQTA5NTVaQQoLc3Rha2Vob2xkZXISGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="09:32:53.709379 - 15 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001EEIUYMZH2T]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[3293]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;ANWKIB-2024-11-15&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;ANWKIB&quot;, &amp;
    &quot;version&quot;: &quot;0&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-15T08:32:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;, &amp;
                &quot;iataNumber&quot;: &quot;12345675&quot;, &amp;
                &quot;systemCode&quot;: &quot;1A&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-15T08:32:52Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JANE&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AP-5&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610A941E00031409&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T09:30:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T10:30:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7725&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7725-2024-12-29-NCE-CDG&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600A241E0005443F&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7726&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7726-2024-12-29-CDG-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-BKG-2&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600A241E00054440&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;flightItinerary&quot;: [&amp;
        \{&amp;
            &quot;flights&quot;: [&amp;
                \{&amp;
                    &quot;connectedFlights&quot;: \{&amp;
                        &quot;connectionType&quot;: &quot;CONNECTION&quot;, &amp;
                        &quot;flightSegments&quot;: [&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}, &amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}&amp;
                        ]&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-CNX-3&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AP-5&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;NCE&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-TK-6&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-11-15T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="10" responseEndLine="197" responseBeginLine="190" endLine="188" beginLine="187" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:53.710268 - 15 Nov 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE></QUERY><COMPARISON compareAt="09:32:54.024196 - 15 Nov 2024" match="OK"><TEXT><![CDATA[--- RLR ---&amp;
RP/NCE1A0955/NCE1A0955            YG/SU  ]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[15NOV24]]></VALUE></VARIABLE><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[/0832]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[Z   ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  1.SMITH/JANE&amp;
  2  6X7725 Y 29DEC 7 NCECDG HK1  0930 1030  29DEC  E  6X/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  3  6X7726 Y 29DEC 7 CDGLHR HK1  1130 1130  29DEC  E  6X/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
  4 AP NCE&amp;
  5 TK OK]]></TEXT><VARIABLE name="today_ddmmm"><VALUE><![CDATA[15NOV]]></VALUE></VARIABLE><TEXT><![CDATA[/NCE1A0955&amp;
&gt;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="11" responseEndLine="221" responseBeginLine="210" endLine="209" beginLine="205" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:54.025620 - 15 Nov 2024"><TEXT><![CDATA[GET /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[ HTTP/1.1&amp;
Authorization: 1AAuth ]]></TEXT><VARIABLE name="auth_header4"><VALUE><![CDATA[eyJub25jZSI6Ik1EazRPRFF4TURBMk56QXpOREV4TXc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTVUMDg6MzI6NDIuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiai9XWm1lK3RLT3M3WDA3d0dpWXM5Z2JGMWNnPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
]]></TEXT></QUERY><COMPARISON compareAt="09:32:54.435806 - 15 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001EEIV8MZH2T]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2065]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
\{&amp;
    &quot;reference&quot;: &quot;]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;, &amp;
    &quot;version&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;, &amp;
    &quot;openPnr&quot;: &quot;]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_protobuf%=.*}]]></EXPRESSION><VALUE><![CDATA[ChFBTldLSUItMjAyNC0xMS0xNRIDcG5yGgZBTldLSUIiATE6VRoUMjAyNC0xMS0xNVQwODozMjowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0xMS0xNVQwODozMjo1M1p6iwEKC3N0YWtlaG9sZGVyEhpBTldLSUItMjAyNC0xMS0xNS1QTlItTk0tMSINEgRKQU5FGgVTTUlUSHI8Cgdjb250YWN0EhpBTldLSUItMjAyNC0xMS0xNS1QTlItQVAtNRoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBOTQxRTAwMDMxNDA5ggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTEimwIKGgoDTkNFGhMyMDI0LTEyLTI5VDA5OjMwOjAwEhoKA0NERxoTMjAyNC0xMi0yOVQxMDozMDowMCJPCgoKAjZYEgQ3NzI1EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI1LTIwMjQtMTItMjktTkNFLUNER0oCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMRoQNjAwQTI0MUUwMDA1NDQzRlpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTIimwIKGgoDQ0RHGhMyMDI0LTEyLTI5VDExOjMwOjAwEhoKA0xIUhoTMjAyNC0xMi0yOVQxMTozMDowMCJPCgoKAjZYEgQ3NzI2EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI2LTIwMjQtMTItMjktQ0RHLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMhoQNjAwQTI0MUUwMDA1NDQ0MFpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAigGjASKgAQqAAQgBEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQ05YLTOyAXIKB2NvbnRhY3QSGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1BUC01QgEBWgUKA05DRWJBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AZQCChFhdXRvbWF0ZWQtcHJvY2VzcxIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLVRLLTYYBSITMjAyNC0xMS0xNVQwMDowMDowMCoLCglOQ0UxQTA5NTVaQQoLc3Rha2Vob2xkZXISGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&quot;&amp;
\}]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="12" responseEndLine="244" responseBeginLine="237" endLine="235" beginLine="231" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:54.436521 - 15 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header5"><VALUE><![CDATA[eyJub25jZSI6Ik1UWTROakF3TURnMU1qUXpPREV6TVE9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTVUMDg6MzI6NDIuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiVGU1S1VnQkE2aTZOWmI0SDZnNVdMYlcvS2hNPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="received_protobuf"><VALUE><![CDATA[ChFBTldLSUItMjAyNC0xMS0xNRIDcG5yGgZBTldLSUIiATE6VRoUMjAyNC0xMS0xNVQwODozMjowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0VKFhoUMjAyNC0xMS0xNVQwODozMjo1M1p6iwEKC3N0YWtlaG9sZGVyEhpBTldLSUItMjAyNC0xMS0xNS1QTlItTk0tMSINEgRKQU5FGgVTTUlUSHI8Cgdjb250YWN0EhpBTldLSUItMjAyNC0xMS0xNS1QTlItQVAtNRoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBOTQxRTAwMDMxNDA5ggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTEimwIKGgoDTkNFGhMyMDI0LTEyLTI5VDA5OjMwOjAwEhoKA0NERxoTMjAyNC0xMi0yOVQxMDozMDowMCJPCgoKAjZYEgQ3NzI1EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI1LTIwMjQtMTItMjktTkNFLUNER0oCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMRoQNjAwQTI0MUUwMDA1NDQzRlpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAggHGAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTIimwIKGgoDQ0RHGhMyMDI0LTEyLTI5VDExOjMwOjAwEhoKA0xIUhoTMjAyNC0xMi0yOVQxMTozMDowMCJPCgoKAjZYEgQ3NzI2EiUKAVkSAwoBWRoSCgASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI2LTIwMjQtMTItMjktQ0RHLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMhoQNjAwQTI0MUUwMDA1NDQ0MFpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgEAigGjASKgAQqAAQgBEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzEj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQ05YLTOyAXIKB2NvbnRhY3QSGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1BUC01QgEBWgUKA05DRWJBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnO6AZQCChFhdXRvbWF0ZWQtcHJvY2VzcxIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLVRLLTYYBSITMjAyNC0xMS0xNVQwMDowMDowMCoLCglOQ0UxQTA5NTVaQQoLc3Rha2Vob2xkZXISGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMRoVcHJvY2Vzc2VkUG5yLnByb2R1Y3RzYj0KB3Byb2R1Y3QSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1BSVItMhoVcHJvY2Vzc2VkUG5yLnByb2R1Y3Rz]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="09:32:54.708929 - 15 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001EEIVAMZH2U]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[3293]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;ANWKIB-2024-11-15&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;ANWKIB&quot;, &amp;
    &quot;version&quot;: &quot;1&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-15T08:32:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;, &amp;
                &quot;iataNumber&quot;: &quot;12345675&quot;, &amp;
                &quot;systemCode&quot;: &quot;1A&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-15T08:32:53Z&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JANE&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AP-5&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610A941E00031409&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T09:30:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T10:30:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7725&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7725-2024-12-29-NCE-CDG&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600A241E0005443F&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7726&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7726-2024-12-29-CDG-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-BKG-2&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600A241E00054440&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;flightItinerary&quot;: [&amp;
        \{&amp;
            &quot;flights&quot;: [&amp;
                \{&amp;
                    &quot;connectedFlights&quot;: \{&amp;
                        &quot;connectionType&quot;: &quot;CONNECTION&quot;, &amp;
                        &quot;flightSegments&quot;: [&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}, &amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}&amp;
                        ]&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-CNX-3&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AP-5&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;NCE&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-TK-6&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-11-15T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="13" responseEndLine="266" responseBeginLine="264" endLine="262" beginLine="258" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:54.787275 - 15 Nov 2024"><TEXT><![CDATA[UNH++PNRRET:]]></TEXT><VARIABLE name="PNRRET_Version"><VALUE><![CDATA[14]]></VALUE></VARIABLE><TEXT><![CDATA[:]]></TEXT><VARIABLE name="PNRRET_Release"><VALUE><![CDATA[2]]></VALUE></VARIABLE><TEXT><![CDATA[:1A&apos;&amp;
ORG+00+:]]></TEXT><VARIABLE name="DESTINATION_OFFICE"><VALUE><![CDATA[NCE1A0950]]></VALUE></VARIABLE><TEXT><![CDATA[+++++A]]></TEXT><VARIABLE name="MY_SIGN"><VALUE><![CDATA[1127YG]]></VALUE></VARIABLE><TEXT><![CDATA[SUCKS&apos;&amp;
RET+2&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="09:32:55.231285 - 15 Nov 2024" match="OK"><TEXT><![CDATA[UNH++:::+&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[RCI+1A:ANWKIB::151124:0832&apos;&amp;
RSI+RP:AASU:NCE1A0955:12345675+NCE1A0955+NCE+NCE1A0955:1127YG:151124:12345675:0832&apos;&amp;
LFT+3:P12+--- RLR ---&apos;&amp;
STX+RLR&apos;&amp;
UID+12345675:NCE1A0955+A&apos;&amp;
SYS++1A:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+12345675:NCE1A0955+A&apos;&amp;
SYS++1A:NCE&apos;&amp;
PRE+FR&apos;&amp;
UID+12345675:NCE1A0955+A&apos;&amp;
SYS++1A:NCE&apos;&amp;
PRE+FR&apos;&amp;
SEQ++2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
PNH++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%env_num%=.{1}}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{(multi).*}]]></EXPRESSION><VALUE><![CDATA[SDI+++2025:1:2&apos;&amp;
EMS++PT:1+NM+1&apos;&amp;
TIF+SMITH::1+JANE&apos;&amp;
ETI+:1+UN:Y:Y::SMITH:JANE&apos;&amp;
ODI&apos;&amp;
EMS++ST:1+AIR+2&apos;&amp;
TVL+291224:0930:291224:1030+NCE+CDG+6X+7725:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+6X:ANWKIB&apos;&amp;
RPI+1+HK&apos;&amp;
APD+ERJ:0:0100::7+++432:M&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
FSD&apos;&amp;
TVL+291224:0930:291224:1030+NCE+CDG&apos;&amp;
IFT+ACO+AIRCRAFT OWNER AMADEUS SIX&apos;&amp;
DUM&apos;&amp;
REF+PT:1&apos;&amp;
EMS++ST:2+AIR+3&apos;&amp;
TVL+291224:1130:291224:1130+CDG+LHR+6X+7726:Y+ET&apos;&amp;
MSG+1&apos;&amp;
RCI+6X:ANWKIB&apos;&amp;
RPI+1+HK&apos;&amp;
APD+ERJ:0:0100::7+++216:M&apos;&amp;
CBD+M&apos;&amp;
SDT+P2&apos;&amp;
FSD&apos;&amp;
TVL+291224:1130:291224:1130+CDG+LHR&apos;&amp;
IFT+ACO+AIRCRAFT OWNER AMADEUS SIX&apos;&amp;
DUM&apos;&amp;
REF+PT:1&apos;&amp;
SGR+CNX+:1*:2&apos;&amp;
DUM&apos;&amp;
EMS++OT:5+AP+4&apos;&amp;
LFT+3:5+NCE&apos;&amp;
REF+PT:1&apos;&amp;
EMS++OT:6+TK+5&apos;&amp;
TKE++OK:151124::NCE1A0955&apos;&amp;
EMS++OT:11+OPC+6&apos;&amp;
OPE+NCE1A0955:161124:1:8:6X CANCELLATION DUE TO NO TICKET NCE TIME ZONE::2300&apos;&amp;
REF+ST:1*ST:2*PT:1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="14" endLine="275" beginLine="274" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><SCRIPT type="Exec">env_num = int (env_num)
env_num = env_num - 0
</SCRIPT><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:55.234383 - 15 Nov 2024"><TEXT><![CDATA[UNH++::&apos;&amp;
print(env_num)]]></TEXT></QUERY><REPLY receiveAt="09:32:55.314348 - 15 Nov 2024" filename="">UNB+IATB:1+1AAPITES3+TESAPI3+241115:0832+00JCQTRAWD0002+00LH2EKJSM0002++E&apos;&amp;
UNH+1+CONTRL:2:1:UN+09CC2B44&apos;&amp;
UCI+00LH2EKJSM0002+TESAPI3+1AAPITES3+7&apos;&amp;
UCM+1+UNKMSG:XX:X:XX+4+17&apos;&amp;
UNT+4+1&apos;&amp;
UNZ+1+00JCQTRAWD0002&apos;</REPLY></TRANSACTION><TRANSACTION transactionCounter="14"><QUERY filename="" loop="0" sentAt="09:32:55.314701 - 15 Nov 2024"></QUERY></TRANSACTION><TRANSACTION transactionCounter="15" responseEndLine="305" responseBeginLine="292" endLine="290" beginLine="284" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:55.511991 - 15 Nov 2024"><TEXT><![CDATA[UNH++PURCRQ:14:1:1A&apos;&amp;
ORG+1A+:NCE6X0100++++FR:EUR:FR+A001SU&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[15NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12++&apos;]]></TEXT></QUERY><COMPARISON compareAt="09:32:56.313234 - 15 Nov 2024" match="OK"><TEXT><![CDATA[UNH++PURCRR:14:1:1A+&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><VARIABLE name="today_ddmmyy"><VALUE><![CDATA[15NOV24]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SPR+++2005:8:8+2100:12:12&apos;&amp;
DUM&apos;&amp;
RCI+:]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE><TEXT><![CDATA[::]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[20241115\:08\:32\:00]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%backend%=*}]]></EXPRESSION><VALUE><![CDATA[SONPK1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ENV+]]></TEXT><VARIABLE name="env_num"><VALUE><![CDATA[1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
ATC++]]></TEXT><VARIABLE name="openpnr_publication"><VALUE><![CDATA[604]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:11:15:08:32:54]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%message_id%=*}]]></EXPRESSION><VALUE><![CDATA[8337074073]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%sdi_date2%=*}]]></EXPRESSION><VALUE><![CDATA[2024:11:15:08:32:54]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="16" responseEndLine="325" responseBeginLine="319" endLine="318" beginLine="314" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:56.402543 - 15 Nov 2024"><TEXT><![CDATA[UNH++PUPIRQ:14:1:1A&apos;&amp;
IRV+ID+]]></TEXT><VARIABLE name="message_id"><VALUE><![CDATA[8337074073]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
IRV+OBE+]]></TEXT><VARIABLE name="backend"><VALUE><![CDATA[SONPK1]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><VARIABLE name="sdi_date2"><VALUE><![CDATA[2024:11:15:08:32:54]]></VALUE></VARIABLE><TEXT><![CDATA[&apos;]]></TEXT></QUERY><COMPARISON compareAt="09:32:56.512124 - 15 Nov 2024" match="OK"><TEXT><![CDATA[UNH++PUPIRR:14:1:1A+&apos;&amp;
IRV+ID+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[8337074073]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
IRV+OBE+SONPK]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
SDI+++]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[2024:11:15:08:32:54]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&apos;&amp;
BLB+]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1698]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[+E+UNH\x1D1\x1DDUMMYY\x1F01\x1F1\x1F1A\x1C]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%raw_binary%=(multi).*}]]></EXPRESSION><VALUE><![CDATA[\x0A\x82\x0D\x12\xA5\x0C\x0A\x11ANWKIB-2024-11-15\x12\x03pnr\x1A\x06ANWKIB&quot;\x011:q\x1A\x142024-11-15T08:32:00Z&quot;=\x0A&quot;\x0A\x09NCE1A0955\x12\x0812345675\x1A\x021A&quot;\x07AIRLINE\x12\x17\x0A\x041127\x12\x02YG\x1A\x02SU*\x02FR2\x03NCE*\x1A1APUB/ATL-0001AA/NCE1A0955J0\x1A\x142024-11-15T08:32:53Z&quot;\x0D\x0A\x0B\x0A\x09NCE1A0238*\x091APUB/ATLz\x8B\x01\x0A\x0Bstakeholder\x12\x1AANWKIB-2024-11-15-PNR-NM-1&quot;\x0D\x12\x04JANE\x1A\x05SMITHr&lt;\x0A\x07contact\x12\x1AANWKIB-2024-11-15-PNR-AP-5\x1A\x15processedPnr.contacts\xA2\x01\x12\x12\x10610A941E00031409\x82\x01\xCA\x02\x0A\x07product\x10\x01\x1A\x1BANWKIB-2024-11-15-PNR-AIR-1&quot;\x9F\x02\x0A\x1A\x0A\x03NCE\x1A\x132024-12-29T09:30:00\x12\x1A\x0A\x03CDG\x1A\x132024-12-29T10:30:00&quot;Q\x0A\x0A\x0A\x026X\x12\x047725\x12&apos;&amp;
\x0A\x01Y\x12\x03\x0A\x01Y\x1A\x14\x0A\x02\x08\x00\x12\x0C\x0A\x04\x1A\x021A\x12\x04*\x02FR \x01&quot;\x07ECONOMY2\x1A6X-7725-2024-12-29-NCE-CDGJ\x02HKb\x84\x01\x0A\x10segment-delivery\x12\x1BANWKIB-2024-11-15-PNR-BKG-1\x1A\x10600A241E0005443FZA\x0A\x0Bstakeholder\x12\x1AANWKIB-2024-11-15-PNR-NM-1\x1A\x16processedPnr.travelers\x8A\x01\x01E\x92\x01\x02\x08\x00\x82\x01\xCA\x02\x0A\x07product\x10\x01\x1A\x1BANWKIB-2024-11-15-PNR-AIR-2&quot;\x9F\x02\x0A\x1A\x0A\x03CDG\x1A\x132024-12-29T11:30:00\x12\x1A\x0A\x03LHR\x1A\x132024-12-29T11:30:00&quot;Q\x0A\x0A\x0A\x026X\x12\x047726\x12&apos;&amp;
\x0A\x01Y\x12\x03\x0A\x01Y\x1A\x14\x0A\x02\x08\x00\x12\x0C\x0A\x04\x1A\x021A\x12\x04*\x02FR \x01&quot;\x07ECONOMY2\x1A6X-7726-2024-12-29-CDG-LHRJ\x02HKb\x84\x01\x0A\x10segment-delivery\x12\x1BANWKIB-2024-11-15-PNR-BKG-2\x1A\x10600A241E00054440ZA\x0A\x0Bstakeholder\x12\x1AANWKIB-2024-11-15-PNR-NM-1\x1A\x16processedPnr.travelers\x8A\x01\x01E\x92\x01\x02\x08\x00\x8A\x01\xA3\x01&quot;\xA0\x01\x0A\x80\x01\x08\x01\x12=\x0A\x07product\x12\x1BANWKIB-2024-11-15-PNR-AIR-1\x1A\x15processedPnr.products\x12=\x0A\x07product\x12\x1BANWKIB-2024-11-15-PNR-AIR-2\x1A\x15processedPnr.products\x1A\x1BANWKIB-2024-11-15-PNR-CNX-3\xB2\x01q\x0A\x07contact\x12\x1AANWKIB-2024-11-15-PNR-AP-5@\x01Z\x05\x0A\x03NCEbA\x0A\x0Bstakeholder\x12\x1AANWKIB-2024-11-15-PNR-NM-1\x1A\x16processedPnr.travelers\xBA\x01\x94\x02\x0A\x11automated-process\x12\x1AANWKIB-2024-11-15-PNR-TK-6\x18\x05&quot;\x132024-11-15T00:00:00*\x0B\x0A\x09NCE1A0955ZA\x0A\x0Bstakeholder\x12\x1AANWKIB-2024-11-15-PNR-NM-1\x1A\x16processedPnr.travelersb=\x0A\x07product\x12\x1BANWKIB-2024-11-15-PNR-AIR-1\x1A\x15processedPnr.productsb=\x0A\x07product\x12\x1BANWKIB-2024-11-15-PNR-AIR-2\x1A\x15processedPnr.products\x1AX\x0A\x1Fapplication/vnd.google.protobuf\x12\x06ANWKIB\x1A\x011&quot;\x03Pnr*\%com.amadeus.models.reservation.pnr.v2]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[UNT\x1D2\x1D1\x1C&apos;&amp;
&amp;
UNT+6+1&apos;]]></TEXT></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="17" responseEndLine="353" responseBeginLine="346" endLine="344" beginLine="339" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="OK"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:56.513002 - 15 Nov 2024"><TEXT><![CDATA[POST /]]></TEXT><VARIABLE name="SAP"><VALUE><![CDATA[1ASIUTOPLEGU]]></VALUE></VARIABLE><TEXT><![CDATA[/v2/open-pnrs/conversion?input=protobufBase64\&amp;output=json HTTP/1.1&amp;
Content-Type: application/json&amp;
Authorization:1AAuth ]]></TEXT><VARIABLE name="auth_header6"><VALUE><![CDATA[eyJub25jZSI6Ik1EazVPVFkwTkRnME5qQTJPRFkxTXc9PSIsInRpbWVzdGFtcCI6IjIwMjQtMTEtMTVUMDg6MzI6NDIuMDAwWiIsInVzZXJJZCI6IllHQVJOSUVSIiwib2ZmaWNlSWQiOiJOQ0UxQTA5NTUiLCJvcmdhbml6YXRpb24iOiIxQSIsInBhc3N3b3JkIjoiY09ZOTkxektYdEtFZG95UnVFNVIzVHJKaHlJPSJ9]]></VALUE></VARIABLE><TEXT><![CDATA[&amp;
&amp;
\{&quot;openPnr&quot;:&quot;]]></TEXT><VARIABLE name="global_regression.openpnr_payload"><VALUE><![CDATA[ChFBTldLSUItMjAyNC0xMS0xNRIDcG5yGgZBTldLSUIiATE6cRoUMjAyNC0xMS0xNVQwODozMjowMFoiPQoiCglOQ0UxQTA5NTUSCDEyMzQ1Njc1GgIxQSIHQUlSTElORRIXCgQxMTI3EgJZRxoCU1UqAkZSMgNOQ0UqGjFBUFVCL0FUTC0wMDAxQUEvTkNFMUEwOTU1SjAaFDIwMjQtMTEtMTVUMDg6MzI6NTNaIg0KCwoJTkNFMUEwMjM4KgkxQVBVQi9BVEx6iwEKC3N0YWtlaG9sZGVyEhpBTldLSUItMjAyNC0xMS0xNS1QTlItTk0tMSINEgRKQU5FGgVTTUlUSHI8Cgdjb250YWN0EhpBTldLSUItMjAyNC0xMS0xNS1QTlItQVAtNRoVcHJvY2Vzc2VkUG5yLmNvbnRhY3RzogESEhA2MTBBOTQxRTAwMDMxNDA5ggHKAgoHcHJvZHVjdBABGhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTEinwIKGgoDTkNFGhMyMDI0LTEyLTI5VDA5OjMwOjAwEhoKA0NERxoTMjAyNC0xMi0yOVQxMDozMDowMCJRCgoKAjZYEgQ3NzI1EicKAVkSAwoBWRoUCgIIABIMCgQaAjFBEgQqAkZSIAEiB0VDT05PTVkyGjZYLTc3MjUtMjAyNC0xMi0yOS1OQ0UtQ0RHSgJIS2KEAQoQc2VnbWVudC1kZWxpdmVyeRIbQU5XS0lCLTIwMjQtMTEtMTUtUE5SLUJLRy0xGhA2MDBBMjQxRTAwMDU0NDNGWkEKC3N0YWtlaG9sZGVyEhpBTldLSUItMjAyNC0xMS0xNS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc4oBAUWSAQIIAIIBygIKB3Byb2R1Y3QQARobQU5XS0lCLTIwMjQtMTEtMTUtUE5SLUFJUi0yIp8CChoKA0NERxoTMjAyNC0xMi0yOVQxMTozMDowMBIaCgNMSFIaEzIwMjQtMTItMjlUMTE6MzA6MDAiUQoKCgI2WBIENzcyNhInCgFZEgMKAVkaFAoCCAASDAoEGgIxQRIEKgJGUiABIgdFQ09OT01ZMho2WC03NzI2LTIwMjQtMTItMjktQ0RHLUxIUkoCSEtihAEKEHNlZ21lbnQtZGVsaXZlcnkSG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1CS0ctMhoQNjAwQTI0MUUwMDA1NDQ0MFpBCgtzdGFrZWhvbGRlchIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLU5NLTEaFnByb2Nlc3NlZFBuci50cmF2ZWxlcnOKAQFFkgECCACKAaMBIqABCoABCAESPQoHcHJvZHVjdBIbQU5XS0lCLTIwMjQtMTEtMTUtUE5SLUFJUi0xGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMSPQoHcHJvZHVjdBIbQU5XS0lCLTIwMjQtMTEtMTUtUE5SLUFJUi0yGhVwcm9jZXNzZWRQbnIucHJvZHVjdHMaG0FOV0tJQi0yMDI0LTExLTE1LVBOUi1DTlgtM7IBcQoHY29udGFjdBIaQU5XS0lCLTIwMjQtMTEtMTUtUE5SLUFQLTVAAVoFCgNOQ0ViQQoLc3Rha2Vob2xkZXISGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1OTS0xGhZwcm9jZXNzZWRQbnIudHJhdmVsZXJzugGUAgoRYXV0b21hdGVkLXByb2Nlc3MSGkFOV0tJQi0yMDI0LTExLTE1LVBOUi1USy02GAUiEzIwMjQtMTEtMTVUMDA6MDA6MDAqCwoJTkNFMUEwOTU1WkEKC3N0YWtlaG9sZGVyEhpBTldLSUItMjAyNC0xMS0xNS1QTlItTk0tMRoWcHJvY2Vzc2VkUG5yLnRyYXZlbGVyc2I9Cgdwcm9kdWN0EhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTEaFXByb2Nlc3NlZFBuci5wcm9kdWN0c2I9Cgdwcm9kdWN0EhtBTldLSUItMjAyNC0xMS0xNS1QTlItQUlSLTIaFXByb2Nlc3NlZFBuci5wcm9kdWN0cw==]]></VALUE></VARIABLE><TEXT><![CDATA[&quot;\}]]></TEXT></QUERY><COMPARISON compareAt="09:32:56.775979 - 15 Nov 2024" match="OK"><TEXT><![CDATA[HTTP/1.1 200 OK&amp;
ama-request-id:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[0001EEIVMMZH2W]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-length:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[3398]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
etag:]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{*}]]></EXPRESSION><VALUE><![CDATA[1]]></VALUE></REGULAR_EXPRESSION><TEXT><![CDATA[&amp;
content-type:application/vnd.amadeus+json; charset=utf-8&amp;
connection:close&amp;
&amp;
]]></TEXT><REGULAR_EXPRESSION matchStatus="success"><EXPRESSION><![CDATA[{%received_json%=.*}]]></EXPRESSION><VALUE><![CDATA[\{&amp;
    &quot;id&quot;: &quot;ANWKIB-2024-11-15&quot;, &amp;
    &quot;type&quot;: &quot;pnr&quot;, &amp;
    &quot;reference&quot;: &quot;ANWKIB&quot;, &amp;
    &quot;version&quot;: &quot;1&quot;, &amp;
    &quot;creation&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-15T08:32:00Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;, &amp;
                &quot;iataNumber&quot;: &quot;12345675&quot;, &amp;
                &quot;systemCode&quot;: &quot;1A&quot;, &amp;
                &quot;agentType&quot;: &quot;AIRLINE&quot;&amp;
            \}, &amp;
            &quot;login&quot;: \{&amp;
                &quot;numericSign&quot;: &quot;1127&quot;, &amp;
                &quot;initials&quot;: &quot;YG&quot;, &amp;
                &quot;dutyCode&quot;: &quot;SU&quot;, &amp;
                &quot;countryCode&quot;: &quot;FR&quot;, &amp;
                &quot;cityCode&quot;: &quot;NCE&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;1APUB/ATL-0001AA/NCE1A0955&quot;&amp;
    \}, &amp;
    &quot;lastModification&quot;: \{&amp;
        &quot;dateTime&quot;: &quot;2024-11-15T08:32:53Z&quot;, &amp;
        &quot;pointOfSale&quot;: \{&amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0238&quot;&amp;
            \}&amp;
        \}, &amp;
        &quot;comment&quot;: &quot;1APUB/ATL&quot;&amp;
    \}, &amp;
    &quot;travelers&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
            &quot;names&quot;: [&amp;
                \{&amp;
                    &quot;firstName&quot;: &quot;JANE&quot;, &amp;
                    &quot;lastName&quot;: &quot;SMITH&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;contacts&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;contact&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AP-5&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.contacts&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;passenger&quot;: \{&amp;
                &quot;uniqueIdentifier&quot;: &quot;610A941E00031409&quot;&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;products&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;NCE&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T09:30:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T10:30:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7725&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7725-2024-12-29-NCE-CDG&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-BKG-1&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600A241E0005443F&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}, &amp;
        \{&amp;
            &quot;type&quot;: &quot;product&quot;, &amp;
            &quot;subType&quot;: &quot;AIR&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
            &quot;airSegment&quot;: \{&amp;
                &quot;departure&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;CDG&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \}, &amp;
                &quot;arrival&quot;: \{&amp;
                    &quot;iataCode&quot;: &quot;LHR&quot;, &amp;
                    &quot;localDateTime&quot;: &quot;2024-12-29T11:30:00&quot;&amp;
                \}, &amp;
                &quot;marketing&quot;: \{&amp;
                    &quot;flightDesignator&quot;: \{&amp;
                        &quot;carrierCode&quot;: &quot;6X&quot;, &amp;
                        &quot;flightNumber&quot;: &quot;7726&quot;&amp;
                    \}, &amp;
                    &quot;bookingClass&quot;: \{&amp;
                        &quot;code&quot;: &quot;Y&quot;, &amp;
                        &quot;cabin&quot;: \{&amp;
                            &quot;code&quot;: &quot;Y&quot;&amp;
                        \}, &amp;
                        &quot;subClass&quot;: \{&amp;
                            &quot;code&quot;: 0, &amp;
                            &quot;pointOfSale&quot;: \{&amp;
                                &quot;office&quot;: \{&amp;
                                    &quot;systemCode&quot;: &quot;1A&quot;&amp;
                                \}, &amp;
                                &quot;login&quot;: \{&amp;
                                    &quot;countryCode&quot;: &quot;FR&quot;&amp;
                                \}&amp;
                            \}, &amp;
                            &quot;sourceOfSubClassCode&quot;: &quot;SOURCE_COUNTRY&quot;&amp;
                        \}, &amp;
                        &quot;levelOfService&quot;: &quot;ECONOMY&quot;&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;6X-7726-2024-12-29-CDG-LHR&quot;&amp;
                \}, &amp;
                &quot;bookingStatusCode&quot;: &quot;HK&quot;, &amp;
                &quot;deliveries&quot;: [&amp;
                    \{&amp;
                        &quot;type&quot;: &quot;segment-delivery&quot;, &amp;
                        &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-BKG-2&quot;, &amp;
                        &quot;distributionId&quot;: &quot;600A241E00054440&quot;, &amp;
                        &quot;traveler&quot;: \{&amp;
                            &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                            &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                        \}&amp;
                    \}&amp;
                ], &amp;
                &quot;distributionMethod&quot;: &quot;E&quot;, &amp;
                &quot;notAcknowledged&quot;: false&amp;
            \}&amp;
        \}&amp;
    ], &amp;
    &quot;flightItinerary&quot;: [&amp;
        \{&amp;
            &quot;flights&quot;: [&amp;
                \{&amp;
                    &quot;connectedFlights&quot;: \{&amp;
                        &quot;connectionType&quot;: &quot;CONNECTION&quot;, &amp;
                        &quot;flightSegments&quot;: [&amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}, &amp;
                            \{&amp;
                                &quot;type&quot;: &quot;product&quot;, &amp;
                                &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
                                &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                            \}&amp;
                        ]&amp;
                    \}, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-CNX-3&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;contacts&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;contact&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AP-5&quot;, &amp;
            &quot;purpose&quot;: [&amp;
                &quot;STANDARD&quot;&amp;
            ], &amp;
            &quot;freeFlowFormat&quot;: &quot;NCE&quot;, &amp;
            &quot;travelerRefs&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ], &amp;
    &quot;automatedProcesses&quot;: [&amp;
        \{&amp;
            &quot;type&quot;: &quot;automated-process&quot;, &amp;
            &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-TK-6&quot;, &amp;
            &quot;code&quot;: &quot;OK&quot;, &amp;
            &quot;dateTime&quot;: &quot;2024-11-15T00:00:00&quot;, &amp;
            &quot;office&quot;: \{&amp;
                &quot;id&quot;: &quot;NCE1A0955&quot;&amp;
            \}, &amp;
            &quot;travelers&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;stakeholder&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-NM-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.travelers&quot;&amp;
                \}&amp;
            ], &amp;
            &quot;products&quot;: [&amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-1&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}, &amp;
                \{&amp;
                    &quot;type&quot;: &quot;product&quot;, &amp;
                    &quot;id&quot;: &quot;ANWKIB-2024-11-15-PNR-AIR-2&quot;, &amp;
                    &quot;ref&quot;: &quot;processedPnr.products&quot;&amp;
                \}&amp;
            ]&amp;
        \}&amp;
    ]&amp;
\}]]></VALUE></REGULAR_EXPRESSION></COMPARISON></TRANSACTION><TRANSACTION transactionCounter="18" endLine="364" beginLine="363" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:56.777920 - 15 Nov 2024"><TEXT><![CDATA[RT ]]></TEXT><VARIABLE name="recloc"><VALUE><![CDATA[ANWKIB]]></VALUE></VARIABLE></QUERY><REPLY receiveAt="09:32:57.399908 - 15 Nov 2024" filename="">--- RLR ---&amp;
RP/NCE1A0955/NCE1A0955            AA/SU  15NOV24/0832Z   ANWKIB&amp;
  1.SMITH/JANE&amp;
  2  6X7725 Y 29DEC 7 NCECDG HK1  0930 1030  29DEC  E  6X/ANWKIB&amp;
  3  6X7726 Y 29DEC 7 CDGLHR HK1  1130 1130  29DEC  E  6X/ANWKIB&amp;
  4 AP NCE&amp;
  5 TK OK15NOV/NCE1A0955&amp;
  6 OPC-16NOV:2300/1C8/6X CANCELLATION DUE TO NO TICKET NCE TIME&amp;
        ZONE/TKT/S2-3&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="19" endLine="365" beginLine="364" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:57.400188 - 15 Nov 2024"><TEXT><![CDATA[XI]]></TEXT></QUERY><REPLY receiveAt="09:32:57.777354 - 15 Nov 2024" filename="">--- RLR ---&amp;
RP/NCE1A0955/NCE1A0955            AA/SU  15NOV24/0832Z   ANWKIB&amp;
  1.SMITH/JANE&amp;
  2 AP NCE&amp;
  3 TK OK15NOV/NCE6X0100&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="20" endLine="366" beginLine="365" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:57.778014 - 15 Nov 2024"><TEXT><![CDATA[ET]]></TEXT></QUERY><REPLY receiveAt="09:32:58.334584 - 15 Nov 2024" filename="">END OF TRANSACTION COMPLETE - ANWKIB&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="21" endLine="367" beginLine="366" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:58.335072 - 15 Nov 2024"><TEXT><![CDATA[IG]]></TEXT></QUERY><REPLY receiveAt="09:32:58.477883 - 15 Nov 2024" filename="">IGNORED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="22" endLine="372" beginLine="371" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:58.478296 - 15 Nov 2024"><TEXT><![CDATA[JO]]></TEXT></QUERY><REPLY receiveAt="09:32:58.628641 - 15 Nov 2024" filename="">&amp;
09CC2B44         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><TRANSACTION transactionCounter="23" endLine="373" beginLine="372" filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" match="N/A"><QUERY filename="/mnt/c/Users/ygarnier/open_pnr_validation - Copy(sauvegarde)/SCOOP_10597_Support_for_CNX_Prime_Booking_BPT/SCOOP_10597_Support_CNX_Prime_Booking_BPT/Scripts/CNX/Create/Single_CNX_Create_Feed.cry" loop="0" sentAt="09:32:58.628785 - 15 Nov 2024"><TEXT><![CDATA[JD]]></TEXT></QUERY><REPLY receiveAt="09:32:58.723750 - 15 Nov 2024" filename="">&amp;
09CC2B44         NCE1A0955&amp;
&amp;
AREA  TM  MOD SG/DT.LG TIME      ACT.Q   STATUS     NAME&amp;
A                       24             NOT SIGNED&amp;
B                                      NOT SIGNED&amp;
C                                      NOT SIGNED&amp;
D                                      NOT SIGNED&amp;
E                                      NOT SIGNED&amp;
F                                      NOT SIGNED&amp;
&gt;</REPLY></TRANSACTION><STATISTIC><STATISTIC_ELEMENT name="Message in">24</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes in">36013</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages out">24</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="bytes" name="Bytes out">13897</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Conversations">12</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions">24</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Transactions parsed">23</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Ratio">0.958333</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Total duration">9990</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Parse duration">1.534</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Parse percentage">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="ms" name="Wait duration">7619.44</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="%" name="Wait percentage">76</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="CPS" name="Conversations/s">1</STATISTIC_ELEMENT><STATISTIC_ELEMENT unit="TPS" name="Transactions/s">2</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Number of Timeouts">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Messages compared">12</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="Python errors found">0</STATISTIC_ELEMENT><STATISTIC_ELEMENT name="No match counter">0</STATISTIC_ELEMENT></STATISTIC></xml>